// ============================================================================
//  data-06-b.js — Chapter 06 (Temporal-Difference Learning) expansion pool
// ============================================================================
QUESTIONS["06"].push(
  {
    q: "TD learning is often described as a combination of ideas from...",
    options: [
      "Supervised and unsupervised learning",
      "Monte Carlo (sampling) and dynamic programming (bootstrapping)",
      "Evolutionary methods and search",
      "Planning and imitation",
    ],
    answer: 1,
    explain: "TD samples experience like Monte Carlo but updates estimates from other estimates (bootstraps) like DP. This blend gives it online, model-free, low-variance learning.",
  },
  {
    q: "The TD error δ_t is defined as...",
    options: [
      "R_{t+1} − V(S_t)",
      "R_{t+1} + γV(S_{t+1}) − V(S_t)",
      "G_t − V(S_t)",
      "V(S_t) − V(S_{t+1})",
    ],
    answer: 1,
    explain: "δ_t = R_{t+1} + γV(S_{t+1}) − V(S_t) is the difference between the TD target (bootstrapped) and the current estimate. It drives the TD(0) update V(S_t) ← V(S_t) + αδ_t.",
  },
  {
    q: "The Monte Carlo error can be written as a sum of TD errors when...",
    options: [
      "The value estimates change during the episode",
      "The value estimates don't change during the episode (then G_t − V(S_t) = Σ γ^{k−t} δ_k)",
      "γ = 0",
      "Rewards are zero",
    ],
    answer: 1,
    explain: "If V is held fixed across the episode, the Monte Carlo error equals a discounted sum of TD errors. This identity connects the two methods and is useful in analysis.",
  },
  {
    q: "A key practical advantage of TD over MC is that TD can...",
    options: [
      "Only work with a model",
      "Learn online after every step and handle continuing (non-terminating) tasks",
      "Avoid using rewards",
      "Guarantee zero bias",
    ],
    answer: 1,
    explain: "TD updates each step from a single transition, so it learns online and works in continuing tasks. MC must wait for the episode's return, limiting it to episodic tasks.",
  },
  {
    q: "Relative to Monte Carlo, TD(0) estimates typically have...",
    options: [
      "Higher variance and no bias",
      "Lower variance but some bias (from bootstrapping off imperfect estimates)",
      "Zero variance",
      "Higher variance and higher bias",
    ],
    answer: 1,
    explain: "TD's one-step target depends on fewer random quantities than a full return, giving lower variance; but bootstrapping off a possibly-wrong V(S_{t+1}) introduces bias. MC is unbiased but higher variance.",
  },
  {
    q: "In the 'driving home' example, TD learning lets you update your estimate...",
    options: [
      "Only after arriving home",
      "During the trip, as each new prediction is made, rather than waiting for the final outcome",
      "Never",
      "Only with a model",
    ],
    answer: 1,
    explain: "The driving-home example shows TD updating each leg's time estimate from the next estimate as the trip unfolds, instead of waiting until arrival (as MC would). Learning happens continuously.",
  },
  {
    q: "For a fixed policy, tabular TD(0) is guaranteed to converge to v_π if...",
    options: [
      "The step size is constant and large",
      "The step size satisfies the usual stochastic-approximation conditions (decreasing appropriately)",
      "γ = 1 in a continuing task",
      "There is no exploration",
    ],
    answer: 1,
    explain: "TD(0) converges to v_π (in the mean, and w.p.1 under standard conditions) when the step-size sequence satisfies Σα=∞, Σα²<∞. A small constant α converges in the mean and tracks changes.",
  },
  {
    q: "Batch TD(0) (repeatedly presenting a finite batch until convergence) computes the value function that is...",
    options: [
      "The one minimizing training-set error like batch MC",
      "The maximum-likelihood / certainty-equivalence estimate — the value function of the MDP that best fits the batch",
      "Random",
      "Identical to batch MC always",
    ],
    answer: 1,
    explain: "Batch TD(0) converges to the certainty-equivalence estimate: it implicitly builds the maximum-likelihood MDP model from the data and computes its exact value function. Batch MC instead minimizes mean-squared error on the observed returns.",
  },
  {
    q: "In the batch (finite-data) setting, why can batch TD(0) outperform batch MC on future data?",
    options: [
      "It has no bias",
      "It exploits the Markov structure (certainty-equivalence), giving better estimates of future returns than minimizing past-return error",
      "It uses a larger step size",
      "It ignores the data",
    ],
    answer: 1,
    explain: "Batch MC minimizes error on the observed returns, but batch TD leverages the Markov property to estimate the underlying MDP, often generalizing better to future experience — a classic illustration of bootstrapping's benefit.",
  },
  {
    q: "Sarsa is on-policy because its update target uses...",
    options: [
      "The max over next actions",
      "the action A_{t+1} actually selected by the current policy (including exploration)",
      "a model of the environment",
      "the Monte Carlo return",
    ],
    answer: 1,
    explain: "Sarsa updates Q(S_t,A_t) toward R_{t+1}+γQ(S_{t+1},A_{t+1}) using the next action the policy actually takes. Evaluating the policy it follows makes Sarsa on-policy.",
  },
  {
    q: "The name 'Sarsa' comes from the quintuple used in its update:",
    options: [
      "State, Action, Reward, State, Action (S_t, A_t, R_{t+1}, S_{t+1}, A_{t+1})",
      "Sample, Average, Return, State, Action",
      "State, Advantage, Reward, Signal, Action",
      "Sum, Action, Reward, Step, Alpha",
    ],
    answer: 0,
    explain: "Sarsa uses the tuple (S_t, A_t, R_{t+1}, S_{t+1}, A_{t+1}) — hence the acronym. All five elements appear in its update.",
  },
  {
    q: "Q-learning's update is Q(S_t,A_t) ← Q(S_t,A_t) + α[R_{t+1} + γ max_a Q(S_{t+1},a) − Q(S_t,A_t)]. It learns...",
    options: [
      "v_π for the behavior policy",
      "q* directly, independent of the policy being followed (off-policy)",
      "the model",
      "the average reward",
    ],
    answer: 1,
    explain: "By using max_a in the target, Q-learning approximates q* regardless of the exploratory behavior policy — an off-policy TD control method. This was a landmark early breakthrough.",
  },
  {
    q: "On the cliff-walking task, Q-learning learns the optimal path along the cliff edge but earns LOWER online reward than Sarsa because...",
    options: [
      "It cannot find the optimal path",
      "Its ε-greedy exploration occasionally steps off the cliff from that risky optimal path, incurring large penalties during learning",
      "It uses a model",
      "It has a larger step size",
    ],
    answer: 1,
    explain: "Q-learning targets the greedy optimal (edge) path, but while behaving ε-greedily it sometimes falls off the cliff. Sarsa, being on-policy, accounts for exploration and learns a safer path with higher online reward.",
  },
  {
    q: "Expected Sarsa's target replaces Q(S_{t+1},A_{t+1}) with...",
    options: [
      "max_a Q(S_{t+1},a)",
      "Σ_a π(a|S_{t+1}) Q(S_{t+1},a) — the expectation over next actions under the policy",
      "a random Q value",
      "0",
    ],
    answer: 1,
    explain: "Expected Sarsa uses the policy-weighted expectation of next-action values, eliminating the variance due to randomly sampling A_{t+1}. It generally performs at least as well as Sarsa for the same computation-per-step budget.",
  },
  {
    q: "Expected Sarsa can be used off-policy: if the target policy is greedy, Expected Sarsa becomes...",
    options: [
      "Monte Carlo",
      "Q-learning (the expectation under a greedy policy is the max)",
      "Sarsa",
      "Dynamic programming",
    ],
    answer: 1,
    explain: "If the target policy is greedy, Σ_a π(a|S')Q(S',a) = max_a Q(S',a), so Expected Sarsa reduces exactly to Q-learning. Expected Sarsa thus generalizes both Sarsa and Q-learning.",
  },
  {
    q: "A benefit of Expected Sarsa over Sarsa (same data) is that it...",
    options: [
      "Has higher variance",
      "Removes the variance from the random selection of A_{t+1}, allowing larger step sizes and more stable learning",
      "Requires a model",
      "Cannot be off-policy",
    ],
    answer: 1,
    explain: "By averaging over next actions instead of sampling one, Expected Sarsa reduces update variance. This often lets it use a larger α and learn more reliably, at slightly higher per-step computational cost.",
  },
  {
    q: "Maximization bias arises when...",
    options: [
      "The step size is too small",
      "A maximum over noisy estimated values is used to estimate the maximum of the true values, producing a positive bias",
      "Rewards are negative",
      "The discount factor is 1",
    ],
    answer: 1,
    explain: "E[max of estimates] ≥ max of true values when estimates are noisy, so using max (as in Q-learning) systematically overestimates action values — the maximization bias.",
  },
  {
    q: "Double learning combats maximization bias by...",
    options: [
      "Averaging two rewards",
      "Learning two value estimates (Q1, Q2), using one to SELECT the maximizing action and the other to EVALUATE it",
      "Doubling γ",
      "Using two step sizes",
    ],
    answer: 1,
    explain: "Double Q-learning decorrelates action selection from evaluation: argmax uses Q1 while the value used is Q2 (and vice versa on alternating updates). This removes the systematic overestimation of a single maximizing estimator.",
  },
  {
    q: "In Double Q-learning, on each step you typically...",
    options: [
      "Update both Q1 and Q2 with the same target",
      "Randomly choose to update either Q1 or Q2, using the other for the value of the selected greedy action",
      "Update neither",
      "Use the max of Q1 and Q2",
    ],
    answer: 1,
    explain: "You flip a coin: if updating Q1, the target is R+γQ2(S', argmax_a Q1(S',a)); if updating Q2, roles swap. Each estimate is unbiased for the value of the action the OTHER selected, avoiding maximization bias.",
  },
  {
    q: "The example maximizing-bias MDP (state A → left leads to states with mean-zero but noisy rewards) shows that Q-learning...",
    options: [
      "Avoids the bad action",
      "Initially favors the 'left' action too often because the noisy negative-mean rewards occasionally look positive under the max",
      "Never explores",
      "Requires a model",
    ],
    answer: 1,
    explain: "Because the max over noisy near-zero rewards is biased positive, Q-learning is lured into the 'left' action more than it should be. Double Q-learning corrects this and quickly learns to prefer the better action.",
  },
  {
    q: "An 'afterstate' value function is useful in domains like tic-tac-toe/board games because...",
    options: [
      "It ignores the board",
      "Different state–action pairs can lead to the same resulting position, so evaluating the position (afterstate) is more efficient than (state, action)",
      "It requires a model of the opponent",
      "It removes rewards",
    ],
    answer: 1,
    explain: "Afterstate value functions evaluate the board position AFTER the agent's move. Since many (state, action) pairs produce identical afterstates, this sharing makes learning more efficient in such domains.",
  },
  {
    q: "TD(0)'s backup diagram is best described as...",
    options: [
      "A deep sample path to termination",
      "A one-step sample backup: from a state to one sampled successor state (and its value estimate)",
      "A one-step full-width backup over all successors",
      "No backup at all",
    ],
    answer: 1,
    explain: "TD(0) backs up from one sampled next state, combining the shallow (one-step) depth of DP with the sampling of MC — a one-step sample backup, as opposed to DP's full-width or MC's deep sample.",
  },
  {
    q: "Which is TRUE about TD methods and models?",
    options: [
      "They require a model like DP",
      "They are model-free: they learn directly from experience without knowing p(s',r|s,a)",
      "They require the reward function in closed form",
      "They can only work offline",
    ],
    answer: 1,
    explain: "TD is model-free — it learns from sampled transitions without any environment model, unlike DP. This makes it broadly applicable to problems where the dynamics are unknown.",
  },
  {
    q: "Which sentence correctly ranks online applicability?",
    options: [
      "MC updates every step; TD updates at episode end",
      "TD updates every step (online); MC updates only at episode end",
      "Both update only at episode end",
      "Neither updates online",
    ],
    answer: 1,
    explain: "TD updates incrementally after each transition (online), while MC must wait for the complete return at the episode's end. This is a central practical distinction.",
  },
  {
    q: "For control, Sarsa converges to an optimal policy under GPI provided...",
    options: [
      "ε is fixed forever",
      "all state–action pairs are visited infinitely often AND the policy converges to greedy in the limit (e.g., ε→0 appropriately, 'GLIE')",
      "γ = 0",
      "the model is known",
    ],
    answer: 1,
    explain: "Sarsa converges to the optimal policy/value under conditions like GLIE (Greedy in the Limit with Infinite Exploration): infinite visits to all pairs and gradual reduction of exploration to greedy.",
  },
  {
    q: "Why is Q-learning called 'off-policy' even though it may follow an ε-greedy behavior policy?",
    options: [
      "Because it never explores",
      "Because it learns about the greedy (target) policy via the max, independent of the exploratory behavior policy that generates actions",
      "Because it uses a model",
      "Because it updates offline",
    ],
    answer: 1,
    explain: "The learned target (via max_a) is the greedy policy, which differs from the exploratory behavior policy actually taking actions — hence off-policy. No importance sampling is needed because of the max/expectation structure.",
  },
  {
    q: "Compared to Sarsa, Q-learning's use of the max makes it...",
    options: [
      "Learn the value of the policy it follows",
      "Learn the optimal action-value function directly, potentially with a riskier greedy policy during learning",
      "Impossible to implement",
      "Require complete returns",
    ],
    answer: 1,
    explain: "Q-learning targets q* (via max), so it learns the optimal values directly. The resulting greedy policy may be riskier online (cf. cliff walking) than Sarsa's on-policy, exploration-aware policy.",
  },
  {
    q: "The step-size parameter α in TD updates controls...",
    options: [
      "The discount",
      "How much each update moves the estimate toward the TD target (the learning rate)",
      "The exploration probability",
      "The number of states",
    ],
    answer: 1,
    explain: "α scales the correction αδ_t. Larger α means faster but noisier learning; smaller α means slower, smoother learning. Decreasing α over time (per Robbins–Monro) yields convergence in stationary problems.",
  },
  {
    q: "A defining property TD shares with DP (but not MC) is...",
    options: [
      "Requiring a model",
      "Bootstrapping — updating value estimates from other value estimates",
      "Using complete returns",
      "Being offline",
    ],
    answer: 1,
    explain: "Both TD and DP bootstrap (update from successor estimates). MC does not bootstrap. What TD shares with MC (but not DP) is learning from samples without a model.",
  },
  {
    q: "In Expected Sarsa, the extra computation per step (versus Sarsa) is the cost of...",
    options: [
      "Storing more returns",
      "Summing over all actions to compute the expected next-action value",
      "Running a model",
      "Sampling many trajectories",
    ],
    answer: 1,
    explain: "Expected Sarsa must sum π(a|S')Q(S',a) over all actions each step. This modest extra cost buys reduced variance and often better performance than plain Sarsa.",
  },
  {
    q: "Which best describes TD as a 'sample' method?",
    options: [
      "It averages over all successors using the model",
      "It updates using a single sampled next state and reward (a sample backup), not a full expectation over successors",
      "It uses no successors",
      "It waits for the full return",
    ],
    answer: 1,
    explain: "TD performs sample backups: it uses the actually-observed next state/reward (one sample) to form the target, unlike DP's expected (full-width) backup that averages over all successors.",
  },
  {
    q: "For a random-walk prediction task, TD(0) typically...",
    options: [
      "Fails to learn",
      "Learns the state values faster and more accurately than constant-α MC for a range of step sizes",
      "Requires a model",
      "Only works offline",
    ],
    answer: 1,
    explain: "On the classic random-walk example, TD(0) generally outperforms constant-α MC (lower error, faster) because it bootstraps and has lower variance, illustrating TD's practical advantage.",
  },
  {
    q: "The 'TD target' in TD(0) is...",
    options: [
      "V(S_t)",
      "R_{t+1} + γV(S_{t+1})",
      "The full return G_t",
      "max_a Q(S_t,a)",
    ],
    answer: 1,
    explain: "The TD target is the bootstrapped estimate R_{t+1}+γV(S_{t+1}) toward which V(S_t) is moved. The difference between this target and V(S_t) is the TD error.",
  },
  {
    q: "Which is a correct statement about bias in Q-learning versus Expected Sarsa (on-policy target)?",
    options: [
      "Both always overestimate",
      "Q-learning's max introduces maximization bias; on-policy Expected Sarsa (expectation, not max) avoids that particular bias",
      "Neither ever has bias",
      "Expected Sarsa always overestimates more",
    ],
    answer: 1,
    explain: "The maximization bias specifically comes from taking a max over noisy estimates (Q-learning). Expected Sarsa's expectation under a fixed policy does not take a max, so it avoids maximization bias (though bootstrapping bias remains).",
  },
  {
    q: "TD methods can be viewed within GPI as performing...",
    options: [
      "Only policy improvement",
      "Sample-based, bootstrapped policy evaluation, combined with greedy(-ish) improvement for control",
      "Full-width evaluation",
      "No evaluation",
    ],
    answer: 1,
    explain: "TD control (Sarsa, Q-learning, Expected Sarsa) is GPI where evaluation is done by sampled, bootstrapped TD updates and improvement is (ε-)greedy — mirroring DP and MC control but model-free and online.",
  },
  {
    q: "The certainty-equivalence estimate that batch TD(0) converges to is optimal in the sense that it...",
    options: [
      "Minimizes past-return error",
      "Is the exact value function of the maximum-likelihood MDP built from the observed data",
      "Ignores the data",
      "Equals the batch-MC estimate",
    ],
    answer: 1,
    explain: "Batch TD forms the maximum-likelihood estimate of transition/reward statistics and computes that model's exact values — the certainty-equivalence estimate — which typically predicts future returns better than batch MC.",
  },
  {
    q: "Which of these is off-policy?",
    options: ["Sarsa", "Q-learning", "TD(0) prediction for the behavior policy", "On-policy Expected Sarsa"],
    answer: 1,
    explain: "Q-learning is off-policy (learns q* via max while behaving exploratorily). Sarsa and on-policy Expected Sarsa are on-policy; TD(0) prediction evaluates the policy generating the data (on-policy).",
  },
  {
    q: "A reason TD control is central to modern RL is that it...",
    options: [
      "Requires a perfect model",
      "Learns online, model-free, from incomplete sequences, and scales (with function approximation) to large problems like Atari",
      "Only works on tiny tabular problems",
      "Cannot handle exploration",
    ],
    answer: 1,
    explain: "TD control's online, model-free, incremental nature — combined with function approximation — underlies scalable algorithms (e.g., DQN builds on Q-learning), making it foundational to modern RL.",
  },
  {
    q: "If γ = 0, the TD(0) target reduces to...",
    options: [
      "The full return",
      "R_{t+1} (purely the immediate reward; no bootstrapping into the future)",
      "V(S_{t+1})",
      "max_a Q(S_t,a)",
    ],
    answer: 1,
    explain: "With γ=0 the target R_{t+1}+γV(S_{t+1}) becomes just R_{t+1}: the agent is myopic and V(S_t) simply estimates the expected immediate reward.",
  },
  {
    q: "The main takeaway of Chapter 6 is that TD learning...",
    options: [
      "Is inferior to both DP and MC",
      "Provides model-free, online, bootstrapping methods for prediction (TD(0)) and control (Sarsa, Q-learning, Expected Sarsa) that are central to RL",
      "Requires exploring starts",
      "Only applies to bandits",
    ],
    answer: 1,
    explain: "Chapter 6 establishes TD as a cornerstone: model-free, incremental, bootstrapping prediction and control, including the influential Sarsa and Q-learning algorithms, and addresses issues like maximization bias.",
  },
  {
    q: "Which correctly summarizes the sampling/bootstrapping identity of the three basic methods?",
    options: [
      "DP: sample+bootstrap; MC: expected+bootstrap; TD: expected only",
      "DP: expected+bootstrap; MC: sample, no bootstrap; TD: sample+bootstrap",
      "All three bootstrap and sample identically",
      "MC and TD both use expected updates",
    ],
    answer: 1,
    explain: "DP uses expected (full-width) updates and bootstraps; MC uses sample updates and does NOT bootstrap; TD uses sample updates AND bootstraps — occupying the fourth corner and combining the others' strengths.",
  }
);
