// ============================================================================
//  data-15-b.js — Chapter 15 (Neuroscience) expansion pool
// ============================================================================
QUESTIONS["15"].push(
  {
    q: "The reward prediction error hypothesis of dopamine proposes that phasic dopamine signals...",
    options: [
      "the absolute reward received",
      "a reward PREDICTION ERROR, closely resembling the TD error δ",
      "the current state",
      "motor commands only",
    ],
    answer: 1,
    explain: "The hypothesis (Montague, Dayan, Schultz) is that phasic dopamine activity encodes a reward prediction error — like the TD error R+γV(S')−V(S) — not reward itself. This is a landmark RL–neuroscience link.",
  },
  {
    q: "Before learning, dopamine neurons respond most strongly to...",
    options: [
      "the predictive cue",
      "the (unexpected) reward itself",
      "nothing",
      "the omission of reward",
    ],
    answer: 1,
    explain: "For an unexpected reward, dopamine fires at reward delivery (a positive prediction error). With learning, this response shifts earlier to the predictive cue.",
  },
  {
    q: "AFTER learning a cue that reliably predicts reward, dopamine neurons respond most strongly to...",
    options: [
      "the now-predicted reward",
      "the earliest reliable predictive cue (the prediction error moves to the cue)",
      "random events",
      "the motor action",
    ],
    answer: 1,
    explain: "Once the reward is predicted, its delivery carries no error, so the phasic dopamine response transfers to the earliest reliable predictor — exactly as a TD error propagates back to the first predictive state.",
  },
  {
    q: "If a predicted reward is OMITTED, dopamine neurons show...",
    options: [
      "a burst above baseline",
      "a dip (pause) BELOW baseline at the expected time of reward",
      "no change",
      "a response to the cue only",
    ],
    answer: 1,
    explain: "Omission of an expected reward yields a negative prediction error: dopamine activity dips below baseline at the expected reward time — the sign pattern predicted by the TD error hypothesis.",
  },
  {
    q: "The three signature dopamine response patterns (unexpected reward → burst; predicted reward → no response; omitted reward → dip) collectively match...",
    options: [
      "the reward magnitude",
      "the SIGN and timing of a temporal-difference prediction error",
      "random noise",
      "the value function directly",
    ],
    answer: 1,
    explain: "These three patterns are exactly what a TD prediction error predicts: positive error for unexpected reward, zero for predicted reward, negative for omission. This correspondence is the core evidence for the hypothesis.",
  },
  {
    q: "The brain region most associated with actor–critic-style RL is the...",
    options: [
      "cerebellum",
      "basal ganglia (with the striatum implicated as actor/critic)",
      "occipital cortex",
      "brainstem respiratory center",
    ],
    answer: 1,
    explain: "The basal ganglia, modulated by dopaminergic prediction errors, are widely modeled as implementing actor–critic RL, with striatal subregions proposed to serve critic (value) and actor (action-selection) roles.",
  },
  {
    q: "In neural actor–critic models, which striatal region is often proposed as the 'critic'?",
    options: [
      "The dorsal striatum",
      "The ventral striatum (value/prediction)",
      "The cerebellum",
      "The hippocampus only",
    ],
    answer: 1,
    explain: "The ventral striatum is commonly linked to the critic (learning value predictions), while the dorsal striatum is linked to the actor (action selection/policy). Dopamine provides the shared teaching signal.",
  },
  {
    q: "In neural actor–critic models, which region is often proposed as the 'actor'?",
    options: [
      "The ventral striatum",
      "The dorsal striatum (action selection/policy)",
      "The retina",
      "The spinal cord",
    ],
    answer: 1,
    explain: "The dorsal striatum is associated with the actor — learning which actions to take (policy) — updated by the dopaminergic prediction error, paralleling the actor in the actor–critic algorithm.",
  },
  {
    q: "The dopaminergic prediction-error signal is thought to train...",
    options: [
      "only the critic",
      "BOTH the critic (value predictions) and the actor (action tendencies)",
      "only the actor",
      "neither",
    ],
    answer: 1,
    explain: "As in the algorithmic actor–critic, the same prediction-error (dopamine) signal is proposed to update both value predictions (critic) and action propensities (actor) — increasing tendencies for actions that yielded positive error.",
  },
  {
    q: "Wolfram Schultz's monkey experiments are famous for...",
    options: [
      "mapping the visual cortex",
      "recording dopamine neurons and revealing the reward-prediction-error firing patterns",
      "discovering the hippocampus",
      "measuring muscle activity",
    ],
    answer: 1,
    explain: "Schultz's single-unit recordings of midbrain dopamine neurons revealed the cue-shift and omission-dip patterns, providing the empirical basis for the reward-prediction-error hypothesis.",
  },
  {
    q: "The TD error's temporal structure (bootstrapping from the next state's value) helps explain WHY dopamine responses...",
    options: [
      "stay at reward delivery",
      "shift backward in time to the earliest predictor as learning proceeds",
      "disappear entirely",
      "encode motor commands",
    ],
    answer: 1,
    explain: "Because the TD error backs up value from later to earlier predictors, the error (and thus dopamine) migrates to the earliest reliable cue — precisely the backward temporal shift observed in the recordings.",
  },
  {
    q: "The neuroscience evidence suggests dopamine functions as a...",
    options: [
      "pure reward signal",
      "teaching/learning signal (prediction error) that modulates synaptic plasticity to update predictions and policies",
      "sensory relay",
      "clock",
    ],
    answer: 1,
    explain: "Dopamine is cast as a teaching signal: the prediction error it carries is thought to gate plasticity in target structures, updating value predictions and action tendencies — the biological analog of the TD error driving updates.",
  },
  {
    q: "The correspondence between the TD error and dopamine is significant because it links...",
    options: [
      "two unrelated ideas",
      "a specific RL algorithmic quantity (TD error) to a specific neural signal (phasic dopamine), a rare algorithm-to-brain mapping",
      "vision and hearing",
      "reward and punishment only",
    ],
    answer: 1,
    explain: "It connects a precise computational quantity (the TD error) to a measurable neural signal (phasic dopamine), one of the clearest examples of an RL algorithm illuminating brain function — and vice versa.",
  },
  {
    q: "Which is TRUE about tonic vs. phasic dopamine in these theories?",
    options: [
      "Only tonic dopamine matters",
      "Phasic (fast, burst) dopamine is linked to the prediction-error teaching signal; tonic levels have been linked to other roles (e.g., motivation/average reward)",
      "They are identical",
      "Neither relates to RL",
    ],
    answer: 1,
    explain: "The prediction-error hypothesis concerns PHASIC dopamine bursts/dips. Tonic dopamine has been proposed to relate to motivation or the average reward rate — connecting to the average-reward RL formulation.",
  },
  {
    q: "A proposed link between tonic dopamine and RL is that it may encode something like the...",
    options: [
      "discount factor",
      "average reward rate (relevant to the average-reward/differential setting)",
      "policy",
      "state representation",
    ],
    answer: 1,
    explain: "Some theories link tonic dopamine to the average reward rate, which sets the opportunity cost of time and vigor of responding — connecting neuroscience to the average-reward formulation of RL.",
  },
  {
    q: "The reward-prediction-error account provides a computational explanation for aspects of ADDICTION by suggesting drugs...",
    options: [
      "have no effect on dopamine",
      "can artificially inflate the dopamine prediction-error signal, hijacking normal reinforcement learning",
      "block all learning",
      "only affect vision",
    ],
    answer: 1,
    explain: "Some drugs of abuse increase dopamine directly, producing a persistent positive prediction error that never extinguishes, which can pathologically overvalue drug-associated actions/cues — a computational-level account of addiction.",
  },
  {
    q: "The neuroscience chapter reinforces the idea that RL is...",
    options: [
      "only an engineering tool",
      "a plausible computational account of how brains learn from reward, supported by neural data",
      "unrelated to biology",
      "purely about games",
    ],
    answer: 1,
    explain: "By connecting TD errors to dopamine and actor–critic architectures to the basal ganglia, Chapter 15 supports RL as a computational theory of biological reward learning, not merely an AI technique.",
  },
  {
    q: "In the actor–critic brain model, a POSITIVE dopamine prediction error at an action should...",
    options: [
      "decrease the tendency to repeat that action",
      "increase the tendency to repeat that action (and raise the value estimate)",
      "have no effect",
      "erase the policy",
    ],
    answer: 1,
    explain: "A positive prediction error (things went better than expected) strengthens the responsible action's tendency (actor) and raises value estimates (critic) — reinforcing behavior that led to the surprise reward.",
  },
  {
    q: "Which best describes the relationship the chapter draws between algorithm and biology?",
    options: [
      "Biology contradicts RL",
      "RL algorithms (TD, actor–critic) provide mechanistic hypotheses that are tested against and supported by neural recordings",
      "They are unrelated",
      "RL only describes the retina",
    ],
    answer: 1,
    explain: "The chapter treats RL algorithms as sources of testable neural hypotheses. The striking fit between TD errors and dopamine, and actor–critic and basal ganglia, exemplifies this productive interplay.",
  },
  {
    q: "The migration of the dopamine response from reward to cue is analogous, in RL, to...",
    options: [
      "the discount factor changing",
      "value/prediction being backed up from later states to earlier predictive states via TD updates",
      "the policy becoming random",
      "the reward increasing",
    ],
    answer: 1,
    explain: "TD updates back up value from rewarded states to earlier predictors; correspondingly, the prediction error (dopamine) moves from the reward to the earliest cue — the same backward propagation in algorithm and brain.",
  },
  {
    q: "Which statement about reward signals in the brain is consistent with the RL framework?",
    options: [
      "Rewards are external numbers given to the brain",
      "Reward signals are generated internally by the nervous system, matching RL's placement of reward at the agent–environment interface",
      "The brain ignores reward",
      "Reward equals raw sensory input",
    ],
    answer: 1,
    explain: "Biological rewards are internally computed evaluative signals. This is consistent with RL treating the reward signal as arising at the agent–environment boundary, reflecting the organism's own valuation systems.",
  },
  {
    q: "The dopamine prediction-error signal is broadcast to target regions in a way that suggests it acts as a...",
    options: [
      "detailed sensory image",
      "global scalar teaching signal modulating plasticity across many synapses",
      "motor command",
      "clock pulse",
    ],
    answer: 1,
    explain: "Dopamine's diffuse projections deliver a broadly-distributed scalar signal, well-suited to acting as a global teaching signal (like the scalar TD error) that gates learning at many target synapses.",
  },
  {
    q: "Which experimental manipulation would produce a NEGATIVE dopamine prediction error?",
    options: [
      "Delivering a larger-than-expected reward",
      "Omitting an expected reward (or delivering less than expected)",
      "Presenting a fully predicted reward",
      "Doing nothing",
    ],
    answer: 1,
    explain: "A worse-than-expected outcome — an omitted or smaller reward — yields a negative prediction error, seen as a dip in dopamine firing below baseline at the expected reward time.",
  },
  {
    q: "The neuroscience findings support which computational component being implemented biologically?",
    options: [
      "The environment model only",
      "The TD prediction error and an actor–critic-like value/policy learning architecture",
      "Importance sampling",
      "Exploring starts",
    ],
    answer: 1,
    explain: "The evidence supports biological implementation of a TD-like prediction error (dopamine) driving value and policy learning in an actor–critic-like architecture (basal ganglia) — core RL components realized in the brain.",
  },
  {
    q: "One reason the dopamine–TD link is considered so compelling is that the TD theory made...",
    options: [
      "no predictions",
      "specific, testable predictions (cue shift, omission dip) that matched neural recordings not obvious a priori",
      "only vague analogies",
      "predictions about vision",
    ],
    answer: 1,
    explain: "The TD account predicted precise, non-obvious response patterns (backward shift to cues, dips on omission) that were subsequently confirmed in dopamine recordings — strong support beyond mere analogy.",
  },
  {
    q: "In the brain-RL correspondence, the 'critic' computes something analogous to...",
    options: [
      "the policy",
      "a value function / prediction of future reward",
      "the raw reward",
      "the discount factor",
    ],
    answer: 1,
    explain: "The critic computes value predictions (expected future reward), enabling the prediction error. Biologically, ventral striatal circuits are proposed to perform this value-prediction (critic) role.",
  },
  {
    q: "The chapter suggests studying the brain can, in turn, benefit RL by...",
    options: [
      "proving RL wrong",
      "inspiring new algorithms and representations grounded in how biological systems solve RL problems",
      "removing the need for reward",
      "eliminating exploration",
    ],
    answer: 1,
    explain: "The RL–neuroscience relationship is bidirectional: just as RL explains neural data, neuroscience can inspire algorithmic ideas (representations, architectures) — a mutually enriching exchange the chapter highlights.",
  },
  {
    q: "The correspondence 'TD error ↔ phasic dopamine' is an example of RL contributing to which field?",
    options: [
      "Astronomy",
      "Neuroscience (a computational theory of a neural signal)",
      "Linguistics",
      "Thermodynamics",
    ],
    answer: 1,
    explain: "It is a prime example of RL contributing a computational theory to neuroscience: identifying the computational role (prediction error) of a specific neuromodulator signal (phasic dopamine).",
  },
  {
    q: "Which is TRUE about the actor–critic interpretation of the basal ganglia?",
    options: [
      "It is fully proven and complete",
      "It is an influential, evidence-supported hypothesis (not a settled fact), mapping value learning and action selection onto striatal circuits",
      "It has no empirical support",
      "It concerns the cerebellum",
    ],
    answer: 1,
    explain: "The actor–critic/basal-ganglia mapping is a well-supported and influential hypothesis, consistent with much data, though the brain's mechanisms are complex and not fully settled — the chapter presents it as a strong model.",
  },
  {
    q: "The dopamine prediction error at an unexpected reward reflects, in RL terms, a large...",
    options: [
      "negative TD error",
      "positive TD error (outcome much better than the current value estimate)",
      "zero TD error",
      "discount factor",
    ],
    answer: 1,
    explain: "An unexpected reward means the outcome greatly exceeds the predicted value, giving a large positive TD error — matching the strong phasic dopamine burst observed for unpredicted rewards.",
  },
  {
    q: "Which best summarizes Chapter 15?",
    options: [
      "The brain does not use RL",
      "Neural data (especially phasic dopamine as a TD-like reward prediction error, and basal-ganglia actor–critic circuits) provide strong support for RL as a model of biological reward learning",
      "RL only models the visual system",
      "Dopamine encodes raw reward",
    ],
    answer: 1,
    explain: "Chapter 15 marshals neuroscience evidence — dopamine as a TD prediction error, basal-ganglia actor–critic — to argue that RL captures core aspects of how brains learn from reward.",
  },
  {
    q: "The fact that a predicted reward elicits NO phasic dopamine response corresponds to a TD error of...",
    options: [
      "large positive",
      "approximately zero (the outcome matched the prediction)",
      "large negative",
      "undefined",
    ],
    answer: 1,
    explain: "When reward is fully predicted, the TD error is ~0 (no surprise), and correspondingly dopamine neurons show little phasic response at reward delivery — one of the three signature patterns.",
  },
  {
    q: "Which computational idea from earlier chapters is MOST directly mirrored by dopamine responses?",
    options: [
      "Importance sampling",
      "The temporal-difference error and its backward propagation to predictors",
      "Prioritized sweeping",
      "Tile coding",
    ],
    answer: 1,
    explain: "Dopamine's response patterns mirror the TD error and its backup to earlier predictors — the central mechanism of TD learning — making the TD error the most directly reflected computational idea.",
  },
  {
    q: "The neuroscience chapter, together with the psychology chapter, supports the thesis that RL is...",
    options: [
      "only relevant to computers",
      "a unifying computational framework spanning artificial and biological learning",
      "unrelated to intelligence",
      "purely mathematical with no applications",
    ],
    answer: 1,
    explain: "Chapters 14–15 argue RL unifies accounts of learning across artificial and biological systems, with shared error-driven mechanisms (Rescorla–Wagner/TD) and neural correlates (dopamine, basal ganglia).",
  },
  {
    q: "A key caveat the chapter acknowledges is that...",
    options: [
      "RL perfectly explains all brain function",
      "the brain is complex and the RL correspondences, while compelling, are models/hypotheses that continue to be refined",
      "dopamine is unrelated to reward",
      "the basal ganglia do not exist",
    ],
    answer: 1,
    explain: "The chapter presents the RL–brain correspondences as strong, evidence-backed models rather than complete explanations, recognizing the brain's complexity and ongoing refinement of these theories.",
  },
  {
    q: "In RL terms, a dopamine dip below baseline at an expected-but-omitted reward implements...",
    options: [
      "a positive learning signal to strengthen the prediction",
      "a negative teaching signal that decreases the overly-high value/prediction",
      "no learning",
      "an increase in the discount",
    ],
    answer: 1,
    explain: "The dip is a negative prediction error, which (as a teaching signal) drives down the erroneously high value estimate — extinguishing the prediction, exactly as a negative TD error would.",
  },
  {
    q: "The chapter's discussion implies that value learning in the brain is at least partly...",
    options: [
      "supervised by an external teacher",
      "self-supervised via internally computed prediction errors (bootstrapped predictions), like TD learning",
      "purely random",
      "based on a full world model only",
    ],
    answer: 1,
    explain: "The dopamine-as-TD-error account implies the brain learns values through internally generated, bootstrapped prediction errors — a self-supervised, TD-like process rather than external supervision.",
  },
  {
    q: "Which is a correct statement about the scope of the dopamine hypothesis?",
    options: [
      "It claims dopamine does only one thing everywhere",
      "It specifically concerns phasic dopamine as a reward prediction error; dopamine has other roles, and the hypothesis is a computational account of this signaling",
      "It says dopamine encodes vision",
      "It denies dopamine relates to reward",
    ],
    answer: 1,
    explain: "The hypothesis targets phasic dopamine's role as a reward prediction error. Dopamine participates in many functions; the hypothesis is a precise computational claim about this particular signaling role.",
  },
  {
    q: "The strong RL–neuroscience correspondence is often cited as evidence that...",
    options: [
      "RL is biologically implausible",
      "evolution may have discovered RL-like solutions, and RL is a good normative and mechanistic framework for reward learning",
      "brains avoid prediction errors",
      "reward is unnecessary",
    ],
    answer: 1,
    explain: "The fit suggests biological systems implement RL-like computations, supporting RL as both a normative theory (what should be computed) and a mechanistic model (how brains do it) of learning from reward.",
  },
  {
    q: "Which pairing is correct for the neural actor–critic model?",
    options: [
      "Dopamine = policy; striatum = reward",
      "Dopamine = prediction-error teaching signal; striatum = actor/critic (policy/value)",
      "Dopamine = state; cortex = reward",
      "Dopamine = discount; cerebellum = actor",
    ],
    answer: 1,
    explain: "In the model, dopamine carries the prediction-error teaching signal while striatal circuits implement the actor (policy) and critic (value) — the biological counterpart of the actor–critic algorithm.",
  },
  {
    q: "Overall, Chapter 15 exemplifies which kind of contribution?",
    options: [
      "RL borrowing nothing from and giving nothing to science",
      "A two-way bridge: RL theory explains neural signals, and neuroscience validates and inspires RL",
      "A purely philosophical argument",
      "An unrelated engineering result",
    ],
    answer: 1,
    explain: "Chapter 15 showcases the two-way bridge between RL and neuroscience: RL explains dopamine/basal-ganglia function, and neural evidence validates and can inspire RL — reinforcing RL's status as a theory of learning.",
  },
  {
    q: "The prediction-error interpretation helps explain why animals (and agents) respond to unexpected rewards more than expected ones because...",
    options: [
      "expected rewards are larger",
      "only UNEXPECTED outcomes carry a prediction error (information), so they drive learning and elicit the dopamine response",
      "expected rewards are ignored by the environment",
      "the discount is higher for expected rewards",
    ],
    answer: 1,
    explain: "Learning is driven by prediction error, which is nonzero only for unexpected outcomes. Fully predicted rewards carry no new information (zero error), so they neither drive much learning nor elicit a phasic dopamine burst.",
  }
);
