// ============================================================================
//  data-07-b.js — Chapter 07 (n-step Bootstrapping) expansion pool
// ============================================================================
QUESTIONS["07"].push(
  {
    q: "The n-step return G_{t:t+n} is defined as...",
    options: [
      "R_{t+1} only",
      "R_{t+1} + γR_{t+2} + … + γ^{n−1}R_{t+n} + γ^n V(S_{t+n})",
      "The full Monte Carlo return",
      "max_a Q(S_t,a)",
    ],
    answer: 1,
    explain: "The n-step return sums n real (discounted) rewards and then bootstraps with γ^n V(S_{t+n}). n=1 gives the TD(0) target; n=∞ (to termination) gives the Monte Carlo return.",
  },
  {
    q: "n-step methods form a spectrum with which two methods at the extremes?",
    options: [
      "DP and supervised learning",
      "One-step TD (n=1) and Monte Carlo (n=∞)",
      "Sarsa and Q-learning",
      "Policy iteration and value iteration",
    ],
    answer: 1,
    explain: "n-step bootstrapping interpolates between one-step TD (n=1, heavy bootstrapping) and Monte Carlo (n=∞, no bootstrapping). Intermediate n often works best.",
  },
  {
    q: "The n-step TD update is V(S_t) ← V(S_t) + α[G_{t:t+n} − V(S_t)], applied...",
    options: [
      "Immediately at time t",
      "At time t+n, once the n-step return is available",
      "Only at episode end",
      "Before any rewards are seen",
    ],
    answer: 1,
    explain: "The n-step return requires waiting n steps, so the update for S_t is made at time t+n. This delay is a practical cost of n-step methods (addressed later by eligibility traces).",
  },
  {
    q: "The 'error reduction property' of n-step returns states that the worst-case expected error of the n-step return is...",
    options: [
      "Larger than that of the current estimate",
      "At most γ^n times the worst-case error of V, guaranteeing improvement for appropriate step sizes",
      "Always zero",
      "Independent of n",
    ],
    answer: 1,
    explain: "The maximum expected error under the n-step return is ≤ γ^n times the max error of V. This property guarantees that n-step TD converges to v_π under appropriate conditions, for any fixed n.",
  },
  {
    q: "Empirically, on tasks like the random walk, the best performance is usually obtained with...",
    options: [
      "n = 1",
      "an intermediate n (larger than 1 but not ∞)",
      "n = ∞",
      "n equal to the number of states",
    ],
    answer: 1,
    explain: "Intermediate n balances the bias of bootstrapping (small n) against the variance of long returns (large n), typically giving the lowest error — motivating eligibility traces that average over n.",
  },
  {
    q: "n-step Sarsa updates action values toward...",
    options: [
      "R_{t+1} + γQ(S_{t+1},A_{t+1})",
      "G_{t:t+n} ending in γ^n Q(S_{t+n},A_{t+n})",
      "max over all actions",
      "the Monte Carlo return only",
    ],
    answer: 1,
    explain: "n-step Sarsa forms an n-step return that bootstraps off Q(S_{t+n},A_{t+n}) and updates Q(S_t,A_t) toward it, speeding credit assignment across the n intervening state–action pairs.",
  },
  {
    q: "A key benefit of n-step Sarsa over one-step Sarsa is faster...",
    options: [
      "Exploration",
      "Credit assignment — a reward can update the values of the previous n state–action pairs in one shot",
      "Model learning",
      "Convergence of the step size",
    ],
    answer: 1,
    explain: "With n-step returns, a single informative reward propagates back to the last n state–action pairs immediately, rather than needing n separate one-step updates over many episodes.",
  },
  {
    q: "n-step Expected Sarsa bootstraps at step t+n using...",
    options: [
      "the sampled action A_{t+n}",
      "the expected value Σ_a π(a|S_{t+n})Q(S_{t+n},a) over actions",
      "the max over actions",
      "zero",
    ],
    answer: 1,
    explain: "n-step Expected Sarsa uses n sampled rewards/actions then bootstraps with the expectation over next actions at the final state, reducing variance from the terminal action sample.",
  },
  {
    q: "Off-policy n-step Sarsa corrects for the policy mismatch by multiplying the update by...",
    options: [
      "a constant",
      "the product of importance-sampling ratios ρ over the relevant steps",
      "the discount factor only",
      "the reward",
    ],
    answer: 1,
    explain: "Off-policy n-step methods weight the n-step return by Π π(A_k|S_k)/b(A_k|S_k) over the steps, correcting for generating data under b. This works but increases variance with n.",
  },
  {
    q: "The n-step tree-backup algorithm performs off-policy learning WITHOUT importance sampling by...",
    options: [
      "ignoring the target policy",
      "backing up, at each level, the expected values of the non-taken actions (weighted by the target policy) plus the sampled taken action's continued backup",
      "using the max only",
      "requiring a model",
    ],
    answer: 1,
    explain: "Tree backup builds a tree of one-step expectations: at each step it adds the target-policy-weighted values of actions NOT taken, and continues the backup only along the action that WAS taken — no importance-sampling ratios needed.",
  },
  {
    q: "Why is tree backup attractive compared to importance-sampling-based off-policy methods?",
    options: [
      "It is on-policy",
      "It avoids the high variance introduced by importance-sampling ratios",
      "It requires a model",
      "It only works for n=1",
    ],
    answer: 1,
    explain: "Because it uses expectations over actions rather than ratio products, tree backup sidesteps the variance blow-up of importance sampling, making off-policy multi-step learning more stable.",
  },
  {
    q: "The unifying algorithm n-step Q(σ) lets σ control...",
    options: [
      "the discount factor",
      "the degree of sampling vs. expectation at each step (σ=1 sample like Sarsa, σ=0 expectation like tree backup)",
      "the number of arms",
      "the reward scale",
    ],
    answer: 1,
    explain: "Q(σ) interpolates between fully sampling the next action (σ=1, Sarsa-like, needs IS off-policy) and taking the full expectation (σ=0, tree-backup). σ can even vary per step, unifying the chapter's algorithms.",
  },
  {
    q: "A practical drawback of n-step methods relative to one-step TD is...",
    options: [
      "They cannot bootstrap",
      "They incur a delay of n steps and must store the last n states, actions, and rewards",
      "They require a model",
      "They cannot do control",
    ],
    answer: 1,
    explain: "You must wait n steps and remember the recent trajectory before making an update. Eligibility traces (Ch. 12) achieve the multi-step effect incrementally without this explicit delay/storage.",
  },
  {
    q: "As n increases in n-step TD, the variance of the target generally...",
    options: [
      "Decreases",
      "Increases (more random rewards accumulate), while bootstrapping bias decreases",
      "Stays constant",
      "Becomes zero",
    ],
    answer: 1,
    explain: "Larger n includes more sampled rewards, raising variance, but relies less on the (biased) bootstrap term, lowering bias. This bias–variance trade-off is why an intermediate n is often best.",
  },
  {
    q: "At n = ∞ (episodic task run to termination), n-step TD becomes equivalent to...",
    options: [
      "DP",
      "Monte Carlo (the full return, no bootstrapping)",
      "Q-learning",
      "Prioritized sweeping",
    ],
    answer: 1,
    explain: "When n reaches the end of the episode, γ^n V(S_{t+n}) drops out and the target is the full return — exactly Monte Carlo. So n-step TD spans TD(0) to MC.",
  },
  {
    q: "For off-policy n-step methods, the variance introduced by importance sampling grows...",
    options: [
      "Not at all",
      "with n, because more per-step ratios are multiplied together",
      "only for n=1",
      "with the discount factor only",
    ],
    answer: 1,
    explain: "Each additional step adds another π/b ratio to the product, so variance can grow rapidly with n. This is a key motivation for ratio-free methods like tree backup.",
  },
  {
    q: "The n-step return can be written recursively as G_{t:t+n} = R_{t+1} + γ G_{t+1:t+n}, with the base case...",
    options: [
      "G_{t:t} = 0",
      "G_{t+n:t+n} = V(S_{t+n}) (bootstrap when the horizon is reached)",
      "G = R_{t+1}",
      "G = max_a Q",
    ],
    answer: 1,
    explain: "The recursion bottoms out by bootstrapping: when the n-step horizon is reached, the remaining return is estimated by the value function V(S_{t+n}) (or Q for action-value versions).",
  },
  {
    q: "Which statement about n-step methods and eligibility traces is correct?",
    options: [
      "They are unrelated",
      "Eligibility traces (TD(λ)) can be seen as a smooth, incremental average over all n-step returns, avoiding the fixed-n delay",
      "n-step methods require traces",
      "Traces only work for n=1",
    ],
    answer: 1,
    explain: "TD(λ) averages n-step returns with weights (1−λ)λ^{n−1} and implements this online via eligibility traces — achieving the multi-step benefit without committing to a single n or waiting n steps.",
  },
  {
    q: "In n-step Sarsa, increasing n tends to help most when...",
    options: [
      "rewards are dense and immediate",
      "rewards are delayed/sparse, so multi-step returns carry information back faster",
      "the state space is tiny",
      "there is no discounting",
    ],
    answer: 1,
    explain: "When rewards are delayed or sparse, one-step updates propagate information slowly. Multi-step returns carry a distant reward back to earlier state–action pairs quickly, accelerating learning.",
  },
  {
    q: "A correct summary of Chapter 7 is that n-step bootstrapping...",
    options: [
      "abandons bootstrapping entirely",
      "generalizes one-step TD and Monte Carlo into a family parameterized by n, often outperforming both extremes, and includes off-policy variants (IS and tree backup)",
      "requires a model",
      "only applies to prediction",
    ],
    answer: 1,
    explain: "Chapter 7 presents n-step methods as a unifying family between TD(0) and MC for prediction and control, with off-policy versions via importance sampling and the ratio-free tree-backup algorithm, and the general Q(σ).",
  },
  {
    q: "Which is TRUE about the update timing in n-step prediction within an episode of length T?",
    options: [
      "Updates for the last few states use the full available return (n effectively shrinks near termination)",
      "No updates occur near the end",
      "Updates always use exactly n steps even past termination",
      "Only the first state is updated",
    ],
    answer: 0,
    explain: "Near the end of an episode fewer than n steps remain, so the return naturally uses whatever rewards are available up to termination (the horizon is capped at T) — effectively behaving like a shorter return there.",
  },
  {
    q: "n-step tree backup with n=1 reduces to...",
    options: [
      "Monte Carlo",
      "Expected Sarsa (a one-step expected backup over next actions)",
      "Sarsa",
      "Q-learning only when off-policy",
    ],
    answer: 1,
    explain: "With n=1, tree backup's single level is just the expectation over next-state actions under the target policy — exactly the Expected Sarsa update.",
  },
  {
    q: "Which correctly describes the trade-off tuned by n?",
    options: [
      "Exploration vs exploitation",
      "Bootstrapping bias (favored by small n) vs sampling variance and update delay (grow with n)",
      "On-policy vs off-policy",
      "Model vs model-free",
    ],
    answer: 1,
    explain: "n trades bootstrapping bias (dominant at small n) against variance and update delay (which grow with n). Choosing n is a bias–variance/latency trade-off, often best at an intermediate value.",
  },
  {
    q: "In n-step TD, the quantity γ^n V(S_{t+n}) in the target is the...",
    options: [
      "immediate reward",
      "bootstrapping term (discounted estimate of the remaining return beyond n steps)",
      "importance-sampling ratio",
      "step size",
    ],
    answer: 1,
    explain: "After n real rewards, γ^n V(S_{t+n}) bootstraps the rest of the return using the current value estimate. As n grows, this term is discounted more heavily and matters less.",
  },
  {
    q: "Which is the correct control-method analogue of n-step TD prediction?",
    options: [
      "n-step Sarsa (and n-step Expected Sarsa / tree backup)",
      "Value iteration",
      "Prioritized sweeping",
      "REINFORCE",
    ],
    answer: 0,
    explain: "For control, n-step TD prediction becomes n-step Sarsa (on-policy), with off-policy variants via importance sampling and the ratio-free n-step tree backup, plus the unifying Q(σ).",
  },
  {
    q: "When would n=1 (one-step TD) be preferable to a large n?",
    options: [
      "When rewards are extremely delayed",
      "When low variance and immediate online updates matter more than fast multi-step credit assignment, and bootstrapping is reliable",
      "Never",
      "Only with a model",
    ],
    answer: 1,
    explain: "One-step TD has the lowest variance and updates immediately with no delay/storage. It is preferable when the value estimates are reliable enough that heavy bootstrapping is not too biased.",
  },
  {
    q: "The importance-sampling ratio ρ_{t:h} used in off-policy n-step returns equals...",
    options: [
      "a single term π/b",
      "the product Π_{k=t}^{min(h,T−1)} π(A_k|S_k)/b(A_k|S_k)",
      "the sum of rewards",
      "γ^n",
    ],
    answer: 1,
    explain: "The relevant ratio is the product of per-step target/behavior probabilities over the steps whose actions are being corrected — larger products (more steps) mean higher variance.",
  },
  {
    q: "If an off-policy n-step Sarsa importance ratio for some step is 0, the effect is that...",
    options: [
      "the update is amplified",
      "that trajectory's contribution is zeroed (the target action had zero probability under π)",
      "the reward doubles",
      "the discount changes",
    ],
    answer: 1,
    explain: "A zero ratio (target policy would never take that action) zeroes the correction, discarding that data for the target policy — this can waste much off-policy data and slow learning.",
  },
  {
    q: "n-step tree backup is 'off-policy' in the sense that it...",
    options: [
      "requires the behavior and target policies to match",
      "can learn about a target policy different from the behavior policy, using expected action values instead of ratios",
      "cannot learn any policy",
      "needs a model",
    ],
    answer: 1,
    explain: "Tree backup evaluates the target policy by weighting untaken actions with the target policy's probabilities, so it learns about π while data comes from b — off-policy, but without importance-sampling variance.",
  },
  {
    q: "Which best describes the memory needed by an n-step algorithm during an episode?",
    options: [
      "Memory for the entire episode",
      "Memory for the most recent n steps (states, actions, rewards) awaiting their delayed updates",
      "No memory",
      "Memory for all state values only",
    ],
    answer: 1,
    explain: "n-step methods buffer the last n transitions so the delayed update for S_t can be made at t+n. This bounded window (n) is more than one-step TD but far less than storing the whole episode.",
  },
  {
    q: "For a fixed policy, n-step TD converges to v_π for any n because of...",
    options: [
      "the exploration bonus",
      "the error-reduction property (worst-case error shrinks by γ^n each application)",
      "the maximization operator",
      "a model",
    ],
    answer: 1,
    explain: "The n-step error-reduction property guarantees the expected worst-case error contracts by γ^n, so repeated n-step updates converge to v_π for any valid fixed n (with suitable step sizes).",
  },
  {
    q: "Increasing n changes the backup diagram by...",
    options: [
      "making it wider (more branches)",
      "making it deeper (more real steps before the bootstrap node)",
      "removing the bootstrap node",
      "removing rewards",
    ],
    answer: 1,
    explain: "n-step backups are deeper sample paths: n sampled transitions followed by a single bootstrap node. Larger n = deeper path (toward the full-depth Monte Carlo backup).",
  },
  {
    q: "A reason intermediate n often beats both n=1 and n=∞ is that it...",
    options: [
      "removes all bias and variance",
      "achieves a favorable middle point in the bias–variance trade-off",
      "requires no computation",
      "uses a model",
    ],
    answer: 1,
    explain: "n=1 is low-variance but heavily biased by bootstrapping; n=∞ is unbiased but high-variance. Intermediate n often lands at a sweet spot minimizing total error.",
  },
  {
    q: "In n-step Expected Sarsa, using the expectation at the final bootstrap step (vs sampling) primarily...",
    options: [
      "increases bias",
      "reduces the variance contributed by the last action selection",
      "requires importance sampling",
      "removes the discount",
    ],
    answer: 1,
    explain: "Taking the expected value over next actions at the horizon removes the randomness of sampling that final action, lowering variance — the same benefit Expected Sarsa has over Sarsa, applied at n steps.",
  },
  {
    q: "The n-step methods chapter is a stepping stone toward which later chapter's mechanism?",
    options: [
      "Policy gradients",
      "Eligibility traces (a unified, incremental way to blend all n-step returns)",
      "Dynamic programming",
      "Neuroscience",
    ],
    answer: 1,
    explain: "n-step returns motivate eligibility traces (Ch. 12): TD(λ) averages n-step returns geometrically and implements it online with traces, removing the fixed-n choice and update delay.",
  },
  {
    q: "Which is TRUE about combining n-step returns?",
    options: [
      "You may only use a single n",
      "You can average n-step returns of different lengths (a 'compound update'), e.g., the λ-return",
      "Averaging returns is invalid",
      "Only n=1 and n=∞ can be combined",
    ],
    answer: 1,
    explain: "Compound updates average multiple n-step returns; as long as the weights sum to 1, the result is a valid update target. The λ-return is the specific geometric average used by TD(λ).",
  },
  {
    q: "For sparse-reward navigation tasks, n-step Sarsa helps by...",
    options: [
      "making rewards denser",
      "propagating the terminal reward back to many recent state–action pairs at once, so the path's values form faster",
      "removing exploration",
      "requiring a model",
    ],
    answer: 1,
    explain: "When reward comes only at a goal, a multi-step return spreads that signal back over the last n steps in a single update, dramatically accelerating value formation along successful paths compared with one-step updates.",
  },
  {
    q: "Which statement about n-step off-policy learning is MOST accurate?",
    options: [
      "It is always lower variance than on-policy",
      "Importance-sampling versions are correct but can suffer high variance; tree backup avoids that by using expectations",
      "It cannot be done",
      "It requires exploring starts",
    ],
    answer: 1,
    explain: "Off-policy n-step learning via importance sampling is unbiased but high-variance (products of ratios); tree backup provides a lower-variance, ratio-free alternative by backing up expected action values.",
  },
  {
    q: "The parameter n in n-step methods is analogous to which parameter in TD(λ)?",
    options: [
      "The step size α",
      "The trace-decay λ (both control how far credit propagates / how much bootstrapping)",
      "The discount γ",
      "The exploration ε",
    ],
    answer: 1,
    explain: "Both n (in n-step methods) and λ (in TD(λ)) govern the balance between bootstrapping and using longer returns. λ gives a smooth geometric blend, while n picks a single fixed horizon.",
  },
  {
    q: "Which is a correct statement about n-step returns near the start of learning?",
    options: [
      "They are useless early on",
      "When value estimates are poor, larger n (relying less on the bad bootstrap) can learn faster initially",
      "Only n=1 works early",
      "n has no effect early",
    ],
    answer: 1,
    explain: "Early on, bootstrapped estimates are inaccurate, so leaning on more actual reward (larger n) can help. As estimates improve, smaller n (more bootstrapping) becomes advantageous — a reason adaptive schemes are appealing.",
  },
  {
    q: "The n-step return target used in control (n-step Sarsa) bootstraps off which quantity?",
    options: [
      "V(S_{t+n})",
      "Q(S_{t+n}, A_{t+n})",
      "max_a Q(S_{t+n}, a)",
      "the reward R_{t+n}",
    ],
    answer: 1,
    explain: "n-step Sarsa bootstraps off the action value Q(S_{t+n}, A_{t+n}) of the state–action pair reached after n steps, consistent with its on-policy, action-value nature.",
  },
  {
    q: "Which correctly pairs σ values in Q(σ) with behavior?",
    options: [
      "σ=1 → full expectation (tree backup); σ=0 → sampling (Sarsa)",
      "σ=1 → sampling (Sarsa-like); σ=0 → full expectation (tree backup)",
      "σ has no effect",
      "σ controls the discount",
    ],
    answer: 1,
    explain: "In Q(σ), σ=1 means fully sample the next action (Sarsa-style), σ=0 means take the full expectation over actions (tree backup). Intermediate σ mixes the two, and it can vary by step.",
  },
  {
    q: "A concise takeaway: n-step bootstrapping shows that the choice between TD and Monte Carlo is...",
    options: [
      "binary and fixed",
      "a continuum, and intermediate multi-step methods frequently outperform either extreme",
      "irrelevant",
      "determined solely by the model",
    ],
    answer: 1,
    explain: "Rather than TD-vs-MC being a binary choice, n-step methods reveal a spectrum; picking an intermediate degree of bootstrapping usually yields the best performance, a theme completed by eligibility traces.",
  },
  {
    q: "Why might one still prefer eligibility traces over explicit n-step methods in practice?",
    options: [
      "Traces require a model",
      "Traces blend all n-step returns and update online/incrementally, avoiding both the fixed-n choice and the n-step delay/storage",
      "Traces only work for prediction",
      "n-step methods cannot bootstrap",
    ],
    answer: 1,
    explain: "Eligibility traces implement a geometric average over all n-step returns with a single λ, updating every step with bounded per-step cost — no need to pick n or buffer/delay updates by n steps.",
  }
);
