// ============================================================================
//  data-05-b.js — Chapter 05 (Monte Carlo Methods) expansion pool
// ============================================================================
QUESTIONS["05"].push(
  {
    q: "Monte Carlo methods estimate value functions by...",
    options: [
      "Bootstrapping from successor estimates",
      "Averaging complete sample returns observed after visiting states",
      "Solving the Bellman optimality equation",
      "Using the model's transition probabilities",
    ],
    answer: 1,
    explain: "MC methods average the actual returns that follow visits to a state. They learn from complete episodes of experience and, crucially, do NOT bootstrap.",
  },
  {
    q: "A requirement for Monte Carlo prediction is that the task be...",
    options: [
      "Continuing (no terminal states)",
      "Episodic, so that returns are well-defined and episodes terminate",
      "Deterministic",
      "Markovian",
    ],
    answer: 1,
    explain: "MC needs complete returns, so episodes must terminate. It is naturally suited to episodic tasks; continuing tasks require other treatment (e.g., TD or average-reward methods).",
  },
  {
    q: "First-visit MC estimates v_π(s) as the average of returns following...",
    options: [
      "Every visit to s in each episode",
      "Only the first visit to s in each episode",
      "The last visit to s",
      "All states equally",
    ],
    answer: 1,
    explain: "First-visit MC averages returns after the first time s is reached in each episode. Every-visit MC averages returns after all visits. Both converge to v_π, with different theoretical properties.",
  },
  {
    q: "Unlike DP, a Monte Carlo estimate of one state's value...",
    options: [
      "Requires estimates of all other states",
      "Is independent of estimates of other states (no bootstrapping)",
      "Requires the model",
      "Cannot be computed",
    ],
    answer: 1,
    explain: "Because MC uses full returns rather than successor estimates, each state's value estimate is independent of others. This lets you estimate the value of a subset of states without sweeping the whole space.",
  },
  {
    q: "Why does MC control estimate ACTION values q(s,a) rather than state values v(s)?",
    options: [
      "Action values are cheaper",
      "Without a model, state values alone cannot determine the best action; action values can be used greedily directly",
      "State values cannot be estimated by MC",
      "Rewards are unavailable",
    ],
    answer: 1,
    explain: "For control without a model, you need q(s,a) so you can pick argmax_a q(s,a). State values would require a model to look ahead one step, which model-free MC lacks.",
  },
  {
    q: "The 'exploring starts' assumption guarantees that...",
    options: [
      "Every episode ends quickly",
      "Every state–action pair has nonzero probability of starting an episode, ensuring all pairs are visited",
      "The policy is deterministic",
      "Returns are undiscounted",
    ],
    answer: 1,
    explain: "Exploring starts ensures each (s,a) can begin an episode, so all pairs are eventually sampled — necessary for estimating q for every action under a deterministic policy. It is often impractical in real interaction.",
  },
  {
    q: "Monte Carlo ES (Exploring Starts) interleaves...",
    options: [
      "Only policy evaluation",
      "MC policy evaluation of q with greedy policy improvement, an instance of GPI",
      "Value iteration sweeps",
      "Gradient ascent",
    ],
    answer: 1,
    explain: "MC ES alternates estimating q for the current policy (from returns) and improving the policy greedily w.r.t. q — GPI realized with Monte Carlo evaluation and exploring starts for exploration.",
  },
  {
    q: "To avoid exploring starts, on-policy MC control uses ε-soft policies, meaning...",
    options: [
      "All actions get zero probability except the greedy one",
      "Every action has probability ≥ ε/|A(s)|, ensuring continual exploration",
      "The policy is deterministic",
      "Only the worst action is chosen",
    ],
    answer: 1,
    explain: "ε-soft policies keep exploring by assigning at least ε/|A(s)| to every action. On-policy MC control converges to the best ε-soft policy (not necessarily the overall optimal deterministic policy).",
  },
  {
    q: "In off-policy learning, the policy that generates the data is the ___ policy and the one being learned is the ___ policy.",
    options: [
      "target; behavior",
      "behavior; target",
      "greedy; random",
      "optimal; ε-soft",
    ],
    answer: 1,
    explain: "The behavior policy b generates the episodes; the target policy π is the one whose value we want to learn. Off-policy methods learn about π while behaving according to b.",
  },
  {
    q: "The coverage (assumption of coverage) requirement for off-policy MC is that...",
    options: [
      "π and b are identical",
      "Every action taken under π must have nonzero probability under b (b covers π)",
      "b is deterministic",
      "π is greedy",
    ],
    answer: 1,
    explain: "For importance sampling to work, wherever π(a|s)>0 we need b(a|s)>0 — the behavior policy must be able to produce every action the target policy might take, so we get samples for all relevant behavior.",
  },
  {
    q: "The importance-sampling ratio for a trajectory from t to T−1 is ρ = Π π(A_k|S_k)/b(A_k|S_k). It is used to...",
    options: [
      "Discard episodes",
      "Reweight returns generated under b so their expectation equals the value under π",
      "Increase exploration",
      "Compute the reward",
    ],
    answer: 1,
    explain: "Multiplying returns by ρ corrects for the mismatch between the behavior and target policies, so the reweighted average of behavior-generated returns estimates the target-policy value.",
  },
  {
    q: "Ordinary importance sampling forms the estimate by...",
    options: [
      "A simple average of ρ-weighted returns (dividing by the count of visits)",
      "Dividing by the sum of the weights ρ",
      "Ignoring the ratios",
      "Bootstrapping",
    ],
    answer: 0,
    explain: "Ordinary IS averages ρ·G over the number of visits (divides by n). It is unbiased but can have very large or infinite variance.",
  },
  {
    q: "Weighted importance sampling forms the estimate by...",
    options: [
      "Dividing the sum of ρ·G by the sum of the weights ρ",
      "Dividing by the number of visits",
      "Ignoring returns",
      "Using the max return",
    ],
    answer: 0,
    explain: "Weighted IS is a weighted average: (Σ ρ_k G_k)/(Σ ρ_k). It is biased (bias → 0 with more samples) but has much lower, bounded variance, so it is usually preferred.",
  },
  {
    q: "A single very large importance-sampling ratio ρ can cause ordinary IS to...",
    options: [
      "Become perfectly accurate",
      "Have enormous variance (a single episode can dominate the estimate)",
      "Ignore that episode",
      "Converge instantly",
    ],
    answer: 1,
    explain: "Because ordinary IS divides by the count (not the weights), a huge ρ makes one episode's contribution enormous, inflating variance — potentially to infinity. Weighted IS mitigates this by normalizing by the weights.",
  },
  {
    q: "For off-policy MC estimation, using an incremental update with weighted importance sampling requires tracking...",
    options: [
      "Only the number of visits",
      "A cumulative sum C of the weights, updating Q ← Q + (W/C)[G − Q]",
      "The model",
      "The discount only",
    ],
    answer: 1,
    explain: "The incremental weighted-IS update keeps a cumulative weight C_n = C_{n−1}+W_n and updates Q ← Q + (W_n/C_n)(G_n − Q). This gives an online, memory-efficient weighted average of returns.",
  },
  {
    q: "In off-policy MC control, the behavior policy b is typically ε-soft so that...",
    options: [
      "The target must be random",
      "It explores all actions (coverage), while the target policy π can be the greedy (deterministic) policy",
      "π equals b",
      "No exploration occurs",
    ],
    answer: 1,
    explain: "An ε-soft behavior policy guarantees coverage/exploration, while the target policy being learned can be the greedy, potentially optimal, deterministic policy — separating exploration from the learned policy.",
  },
  {
    q: "A limitation of off-policy MC control is that learning from an episode's tail may be cut short because...",
    options: [
      "Episodes are too short",
      "Once the behavior policy takes a non-greedy action, the target policy's probability is 0, so the return's importance weight (and learning from earlier steps) is zeroed for a greedy target",
      "The reward is negative",
      "The model is inaccurate",
    ],
    answer: 1,
    explain: "With a greedy deterministic target, any exploratory (non-greedy) action makes π(a|s)=0, zeroing ρ for that and prior steps in the trajectory — so only the tails after the last non-greedy action contribute, slowing learning.",
  },
  {
    q: "The Blackjack example is well-suited to Monte Carlo because...",
    options: [
      "Its dynamics are simple to model",
      "Although the environment is known, computing the dynamics for DP is awkward, whereas sampling complete game episodes is easy",
      "It is a continuing task",
      "It has no rewards",
    ],
    answer: 1,
    explain: "Blackjack episodes are easy to simulate (deal cards, play out the hand), but the DP dynamics are cumbersome to compute. MC just plays games and averages returns — a natural fit.",
  },
  {
    q: "A practical advantage of Monte Carlo over DP is that MC...",
    options: [
      "Requires a model",
      "Requires no model of the environment — only the ability to generate sample experience",
      "Bootstraps",
      "Needs the full state space swept",
    ],
    answer: 1,
    explain: "MC learns from sample episodes without any model of transition probabilities or rewards — a major advantage when a model is unavailable but interaction/simulation is possible.",
  },
  {
    q: "Another advantage: MC can focus computation on...",
    options: [
      "The entire state space equally",
      "A subset of states of interest, estimating their values without evaluating all other states",
      "Only terminal states",
      "Only the start state",
    ],
    answer: 1,
    explain: "Because MC estimates each state's value from returns independently, you can estimate values only for the states you care about, ignoring the rest — impossible for full-sweep DP.",
  },
  {
    q: "Monte Carlo methods may be LESS harmed by violations of the Markov property than TD because...",
    options: [
      "They bootstrap heavily",
      "They do not bootstrap; they use actual returns, so errors from a non-Markov state estimate don't propagate through successor estimates",
      "They use a model",
      "They ignore rewards",
    ],
    answer: 1,
    explain: "Since MC does not bootstrap off successor value estimates, it doesn't compound the errors that a non-Markov (aliased) state representation causes in bootstrapping methods like TD.",
  },
  {
    q: "The MC estimate's variance comes primarily from...",
    options: [
      "Bootstrapping bias",
      "The randomness of full returns over many steps (many random rewards and transitions accumulate)",
      "The model error",
      "The step size",
    ],
    answer: 1,
    explain: "A full return sums many random rewards along a long trajectory, so MC estimates have high variance. TD, using a one-step target, has lower variance but adds bootstrapping bias.",
  },
  {
    q: "Every-visit MC's estimates are...",
    options: [
      "Always unbiased for finite data",
      "Biased for finite samples but converge to v_π (its returns from multiple visits are not independent)",
      "Never convergent",
      "Identical to DP",
    ],
    answer: 1,
    explain: "Every-visit MC uses correlated returns from multiple visits within an episode, making finite-sample estimates biased; the bias vanishes asymptotically and it converges to v_π. First-visit MC is unbiased.",
  },
  {
    q: "In Monte Carlo control, policy improvement is done by...",
    options: [
      "Averaging over actions",
      "Making the policy greedy with respect to the current action-value estimates: π(s) = argmax_a Q(s,a)",
      "Random reassignment",
      "Solving the model",
    ],
    answer: 1,
    explain: "As in GPI, MC control improves the policy by making it greedy w.r.t. the estimated action values Q(s,a). Combined with sufficient exploration, this converges toward optimal (or best ε-soft) behavior.",
  },
  {
    q: "The convergence of MC ES to the optimal policy relies on which two idealizations?",
    options: [
      "A model and discounting",
      "Infinitely many episodes (accurate evaluation) and exploring starts (all pairs visited)",
      "Bootstrapping and ε-greedy",
      "A perfect value function",
    ],
    answer: 1,
    explain: "The classic convergence argument assumes infinite episodes for accurate policy evaluation and exploring starts for adequate exploration. Practical versions relax these (e.g., ε-soft policies, incremental improvement).",
  },
  {
    q: "Per-decision importance sampling reduces variance by...",
    options: [
      "Using the whole-trajectory ratio for every reward",
      "Recognizing that a reward at step k need only be weighted by ratios up to step k, not the entire trajectory",
      "Discarding late rewards",
      "Ignoring the target policy",
    ],
    answer: 1,
    explain: "Since a reward R_{k} depends only on the trajectory up to that point, it need only be scaled by the importance ratios up to time k. This per-decision formulation lowers variance compared with weighting every reward by the full ρ.",
  },
  {
    q: "Which best contrasts MC and DP backup diagrams?",
    options: [
      "Both are one step deep",
      "The MC backup extends all the way to the terminal state (a full sample trajectory); the DP backup is one step but full-width over successors",
      "MC is full-width; DP is a sample",
      "They are identical",
    ],
    answer: 1,
    explain: "MC's backup diagram is a single deep sample path to termination; DP's is a shallow (one-step) but full-width branch over all successors. TD combines the shallow depth with sampling.",
  },
  {
    q: "Off-policy methods are valuable because they can learn the optimal policy while...",
    options: [
      "Never exploring",
      "Following an exploratory behavior policy, and can learn from data generated by any (e.g., human or old) policy",
      "Requiring the target to be random",
      "Ignoring returns",
    ],
    answer: 1,
    explain: "Off-policy learning decouples the policy improved from the policy that acts, enabling learning an optimal target policy from exploratory or externally-provided data — a powerful and general capability.",
  },
  {
    q: "In first-visit MC prediction, as the number of episodes → ∞, the estimate converges to v_π by...",
    options: [
      "Bootstrapping",
      "The law of large numbers, since each first-visit return is an unbiased sample of v_π(s)",
      "Gradient descent",
      "The Bellman equation",
    ],
    answer: 1,
    explain: "Each first-visit return is an independent, unbiased sample of the expected return v_π(s); their average converges to v_π(s) by the law of large numbers.",
  },
  {
    q: "Which statement about MC and bootstrapping is correct?",
    options: [
      "MC bootstraps like DP and TD",
      "MC does NOT bootstrap — it uses complete returns instead of successor value estimates",
      "MC bootstraps only in control",
      "Bootstrapping is required for MC",
    ],
    answer: 1,
    explain: "Monte Carlo is the canonical non-bootstrapping method: it forms targets from actual returns, not from estimated successor values. This is a defining contrast with DP and TD.",
  },
  {
    q: "A downside of MC control relative to TD control is that MC...",
    options: [
      "Requires a model",
      "Must wait until an episode ends to update, and cannot learn online step-by-step",
      "Cannot handle stochastic policies",
      "Always diverges",
    ],
    answer: 1,
    explain: "MC updates only after complete returns are available (episode end), so it cannot learn during an episode and is unsuitable for very long or continuing tasks — a gap that TD fills.",
  },
  {
    q: "In off-policy MC with weighted importance sampling, the first return contributes to the estimate with weight...",
    options: [
      "1/2",
      "1 (the weighted average of a single sample is just that sample)",
      "0",
      "ρ²",
    ],
    answer: 1,
    explain: "With one sample, weighted IS gives (ρ₁G₁)/(ρ₁) = G₁, so the estimate equals the first return regardless of its weight — highlighting the bias that shrinks as more samples arrive.",
  },
  {
    q: "The book uses the infinite-variance example to show that ordinary importance sampling can...",
    options: [
      "Always converge quickly",
      "Have infinite variance even when weighted IS behaves well, so estimates fail to settle",
      "Ignore the target policy",
      "Require a model",
    ],
    answer: 1,
    explain: "In a simple example, ordinary IS estimates have infinite variance and never stabilize, whereas weighted IS converges nicely — motivating the practical preference for weighted importance sampling.",
  },
  {
    q: "Monte Carlo methods can be combined with GPI to produce control algorithms that...",
    options: [
      "Need a full model",
      "Learn optimal (or near-optimal) policies purely from sampled episodes",
      "Only evaluate a fixed policy",
      "Require bootstrapping",
    ],
    answer: 1,
    explain: "By alternating MC evaluation of action values with greedy improvement (and adequate exploration), MC control learns good policies from sampled experience alone — no model required.",
  },
  {
    q: "Which is a correct reason MC methods estimate q rather than v for control, restated?",
    options: [
      "To save memory",
      "Because to be useful for choosing actions without a model, one must compare actions, which requires action values",
      "Because v cannot be sampled",
      "Because rewards are hidden",
    ],
    answer: 1,
    explain: "Choosing among actions model-free requires knowing each action's value; hence q(s,a). With only v(s), you couldn't determine which action leads to the best successor without a model.",
  },
  {
    q: "In the incremental off-policy update, W is the...",
    options: [
      "Reward",
      "Importance-sampling ratio (weight) for the current return",
      "Discount factor",
      "Number of visits",
    ],
    answer: 1,
    explain: "W denotes the importance-sampling weight (the product of π/b ratios) for the return being processed. It is accumulated into C and used to update Q incrementally.",
  },
  {
    q: "Which pair correctly matches method to what it needs?",
    options: [
      "DP needs episodes; MC needs a model",
      "DP needs a model; MC needs episodes (sample experience)",
      "Both need a model",
      "Neither needs anything",
    ],
    answer: 1,
    explain: "DP requires a model to compute expected updates; MC requires only sample episodes and no model. This complementary contrast motivates combining their strengths (leading to TD).",
  },
  {
    q: "The main variance-reduction technique for off-policy MC discussed in Chapter 5 is...",
    options: [
      "Bootstrapping",
      "Weighted importance sampling (and per-decision importance sampling)",
      "Increasing γ",
      "Using a deterministic behavior policy",
    ],
    answer: 1,
    explain: "Weighted importance sampling dramatically reduces variance versus ordinary IS, and per-decision IS reduces it further by not over-weighting rewards with irrelevant future ratios.",
  },
  {
    q: "A concise summary of Monte Carlo methods is that they learn from...",
    options: [
      "One-step bootstrapped targets",
      "Complete sampled returns, model-free, updating only at episode boundaries",
      "The model's expectations",
      "Supervised labels",
    ],
    answer: 1,
    explain: "MC = model-free learning from complete returns, no bootstrapping, updates at episode end. Its strengths (no model, no Markov reliance, focus on subsets) and weaknesses (episodic only, high variance, no online updates) frame the move to TD.",
  },
  {
    q: "Which statement about first-visit vs every-visit MC convergence is correct?",
    options: [
      "Only every-visit converges",
      "Both converge to v_π; first-visit uses independent unbiased returns, every-visit uses correlated returns and is asymptotically unbiased",
      "Neither converges",
      "They converge to different values",
    ],
    answer: 1,
    explain: "Both estimators converge to the true v_π. First-visit averages i.i.d. unbiased samples; every-visit averages correlated returns (biased for finite n, consistent in the limit).",
  }
);
