// ============================================================================
//  data-14-b.js — Chapter 14 (Psychology) expansion pool
// ============================================================================
QUESTIONS["14"].push(
  {
    q: "Classical (Pavlovian) conditioning corresponds most closely to which RL problem?",
    options: [
      "Control (improving a policy)",
      "Prediction (learning to predict a biologically significant event)",
      "Planning",
      "Exploration",
    ],
    answer: 1,
    explain: "Classical conditioning is about learning predictions: a neutral CS comes to predict a US. This maps onto RL's prediction (value-estimation) problem, not control.",
  },
  {
    q: "Instrumental (operant) conditioning corresponds most closely to which RL problem?",
    options: [
      "Prediction",
      "Control (behavior is shaped by its consequences)",
      "Model learning",
      "Value estimation only",
    ],
    answer: 1,
    explain: "Instrumental conditioning shapes behavior by its consequences (reinforcement), corresponding to RL's control problem — improving a policy to obtain more reward.",
  },
  {
    q: "Thorndike's 'Law of Effect' states that responses followed by satisfaction are...",
    options: [
      "weakened",
      "more likely to recur, while responses followed by discomfort are less likely to recur",
      "unaffected",
      "always random",
    ],
    answer: 1,
    explain: "The Law of Effect — satisfying outcomes strengthen preceding responses; discomforting outcomes weaken them — is a foundational principle behind reinforcement learning's trial-and-error control.",
  },
  {
    q: "The Rescorla–Wagner model explains conditioning via...",
    options: [
      "mere temporal contiguity of CS and US",
      "an error-correction rule: associative strength changes in proportion to the prediction error (surprise) of the US",
      "a full model of the brain",
      "random association",
    ],
    answer: 1,
    explain: "Rescorla–Wagner is error-driven: learning occurs to the extent the US is unpredicted (prediction error), not merely because CS and US co-occur. This explains phenomena contiguity cannot, like blocking.",
  },
  {
    q: "The 'blocking' effect is that a well-predicted US...",
    options: [
      "causes strong new learning",
      "prevents (blocks) a newly added CS from acquiring associative strength, because the prediction error is near zero",
      "increases exploration",
      "requires a model",
    ],
    answer: 1,
    explain: "If CS-A already predicts the US, adding CS-B produces little prediction error, so B gains little association — it is 'blocked.' This supports error-driven (not contiguity) learning, consistent with TD/Rescorla–Wagner.",
  },
  {
    q: "The TD model of classical conditioning improves on Rescorla–Wagner by adding...",
    options: [
      "a reward signal",
      "within-trial timing via a temporal-difference prediction error, capturing the timing of responses and higher-order conditioning",
      "a full environment model",
      "exploration",
    ],
    answer: 1,
    explain: "Rescorla–Wagner is trial-level and ignores timing. The TD model uses a moment-to-moment TD error, so it captures the timing of conditioned responses and phenomena like second-order (higher-order) conditioning.",
  },
  {
    q: "Second-order (higher-order) conditioning is when...",
    options: [
      "a US predicts a CS",
      "a previously conditioned CS can itself serve to condition a new stimulus, without the US present",
      "two USs combine",
      "no learning occurs",
    ],
    answer: 1,
    explain: "In higher-order conditioning, a CS that already predicts the US acts like a reinforcer for a new stimulus. The TD model naturally accounts for this because predicted value can act as a bootstrapped target — like a secondary reinforcer.",
  },
  {
    q: "A 'secondary (conditioned) reinforcer' in psychology corresponds in RL to...",
    options: [
      "the discount factor",
      "a stimulus/state that becomes rewarding because it predicts primary reward (like bootstrapped value)",
      "the behavior policy",
      "an importance ratio",
    ],
    answer: 1,
    explain: "A secondary reinforcer gains reinforcing power by predicting primary reward — analogous to how a high-value state, via TD bootstrapping, effectively acts as a reward target for earlier states.",
  },
  {
    q: "The distinction between habitual and goal-directed behavior parallels which RL distinction?",
    options: [
      "Episodic vs continuing",
      "Model-free (habitual) vs model-based (goal-directed) control",
      "On-policy vs off-policy",
      "Prediction vs reward",
    ],
    answer: 1,
    explain: "Habits resemble model-free learning: fast, cached action values insensitive to current goal value. Goal-directed behavior resembles model-based planning: it uses an action–outcome model and is sensitive to outcome revaluation.",
  },
  {
    q: "'Outcome devaluation' experiments (e.g., sating an animal on a food) distinguish habitual from goal-directed behavior because...",
    options: [
      "both respond identically",
      "goal-directed (model-based) behavior immediately reduces the action for the now-devalued outcome, while habitual (model-free) behavior persists until relearned",
      "neither changes",
      "only habits change",
    ],
    answer: 1,
    explain: "After devaluing an outcome, model-based (goal-directed) control adjusts at once (it knows the action leads to the now-unwanted outcome), whereas model-free habits keep responding based on cached values until experience updates them.",
  },
  {
    q: "In the RL–psychology correspondence, a 'state' most closely corresponds to...",
    options: [
      "a reward",
      "the animal's internal representation of its situation (stimuli/context)",
      "an action",
      "the discount",
    ],
    answer: 1,
    explain: "The RL state corresponds to the organism's representation of its current situation (perceived stimuli and context). Actions correspond to behaviors, and reward to primary reinforcement.",
  },
  {
    q: "The TD model treats a conditioned response as driven by...",
    options: [
      "the absolute value prediction",
      "changes in prediction (the TD error) over time within a trial",
      "the reward only",
      "random noise",
    ],
    answer: 1,
    explain: "In the TD model, responses and learning track the temporal-difference prediction error — how predictions change moment to moment — which is what lets it explain response timing and shifts to earlier predictors.",
  },
  {
    q: "Which phenomenon supports error-driven learning over simple contiguity?",
    options: [
      "Spontaneous recovery only",
      "Blocking (and related cue-competition effects), where a predicted US yields no learning about a redundant cue",
      "Reflexes",
      "Habituation only",
    ],
    answer: 1,
    explain: "Blocking and other cue-competition effects show that co-occurrence (contiguity) is insufficient; learning depends on prediction error. This aligns conditioning with the error-correction core of Rescorla–Wagner and TD.",
  },
  {
    q: "Instrumental conditioning's dependence on the action–outcome contingency (not just contiguity) parallels RL's use of...",
    options: [
      "the discount factor",
      "reward as a consequence of the agent's own actions (the agent's behavior influences outcomes)",
      "a fixed policy",
      "importance sampling",
    ],
    answer: 1,
    explain: "In instrumental conditioning the animal's actions cause outcomes, so learning depends on the action–outcome contingency — exactly RL's control setting, where the agent's policy affects the rewards it receives.",
  },
  {
    q: "The book argues that reinforcement learning provides psychology with...",
    options: [
      "only qualitative metaphors",
      "precise computational models (Rescorla–Wagner, TD) that quantitatively account for learning phenomena and make testable predictions",
      "a replacement for experiments",
      "a theory of vision",
    ],
    answer: 1,
    explain: "RL offers formal, quantitative models of animal learning (e.g., the TD model of conditioning) that reproduce and predict behavioral phenomena — a productive two-way bridge between RL and psychology.",
  },
  {
    q: "Which RL concept corresponds to a 'primary reinforcer' (e.g., food, water)?",
    options: [
      "The value function",
      "The reward signal (primary, intrinsic reward)",
      "The policy",
      "The eligibility trace",
    ],
    answer: 1,
    explain: "A primary reinforcer corresponds to the reward signal itself — intrinsically valuable outcomes. Secondary reinforcers correspond to learned (predicted) value that acquires reinforcing power via association.",
  },
  {
    q: "A key advantage of the TD model over Rescorla–Wagner is explaining...",
    options: [
      "only trial-level effects",
      "the precise TIMING of conditioned responses and the shift of responding to earlier predictive stimuli",
      "the reward magnitude only",
      "exploration",
    ],
    answer: 1,
    explain: "Because it operates over time within trials (not just trial-to-trial), the TD model explains response timing and how anticipatory responses/predictions move earlier onto the first reliable predictor — beyond Rescorla–Wagner's scope.",
  },
  {
    q: "In RL terms, the animal's 'policy' corresponds to...",
    options: [
      "its reward",
      "its behavioral tendencies — how it selects actions given its state",
      "the environment's dynamics",
      "the discount factor",
    ],
    answer: 1,
    explain: "The policy corresponds to the animal's way of behaving (action tendencies given the situation). Instrumental conditioning improves this policy through reinforcement, just as RL control improves a policy through reward.",
  },
  {
    q: "The concept of 'expectation' or 'prediction' in animal learning maps in RL onto...",
    options: [
      "the action",
      "the value function (expected future reward/US)",
      "the reward",
      "the model's transitions",
    ],
    answer: 1,
    explain: "Animals' learned expectations of upcoming events correspond to RL value functions — predictions of future reward. Classical conditioning is precisely the acquisition of such predictions.",
  },
  {
    q: "Why is the model-free/model-based distinction psychologically significant?",
    options: [
      "It is irrelevant to behavior",
      "It maps onto the well-documented habitual vs. goal-directed behavioral systems, suggesting the brain may use both kinds of RL",
      "It only concerns robots",
      "It removes reward",
    ],
    answer: 1,
    explain: "The model-free (habitual) vs. model-based (goal-directed) computational distinction aligns with two behavioral control systems observed in animals, supporting the idea that both forms of RL operate in the brain.",
  },
  {
    q: "The TD error's role as a teaching signal in these models foreshadows which later chapter?",
    options: [
      "Chapter 4 (DP)",
      "Chapter 15 (Neuroscience), where dopamine is proposed to signal a TD-like reward prediction error",
      "Chapter 2 (Bandits)",
      "Chapter 8 (Planning)",
    ],
    answer: 1,
    explain: "The TD prediction error central to these psychological models directly connects to Chapter 15's reward-prediction-error hypothesis of dopamine — a striking link between algorithm, behavior, and brain.",
  },
  {
    q: "Which statement about contiguity vs. contingency is correct?",
    options: [
      "Learning depends only on contiguity (co-occurrence)",
      "Learning depends on contingency/prediction error, not mere contiguity — as shown by blocking and related effects",
      "Contingency is irrelevant",
      "Both are the same",
    ],
    answer: 1,
    explain: "Modern conditioning theory (and RL models) holds that learning tracks predictive contingency and prediction error, not just co-occurrence. Blocking is the classic evidence that contiguity alone is insufficient.",
  },
  {
    q: "A 'habit' in the goal-directed/habitual framework is characterized by being...",
    options: [
      "sensitive to current outcome value",
      "fast, automatic, and INsensitive to current outcome value (cached, model-free)",
      "always optimal",
      "model-based",
    ],
    answer: 1,
    explain: "Habits are automatic and driven by cached (model-free) action values, so they persist even after the outcome is devalued — insensitive to the current goal value until re-learned through experience.",
  },
  {
    q: "The psychological phenomenon where responding shifts to the EARLIEST reliable predictor is captured by TD because...",
    options: [
      "TD ignores time",
      "the TD error propagates back to the earliest cue that predicts reward, mirroring how dopamine/response shifts to the first predictor",
      "TD uses a model",
      "TD is offline",
    ],
    answer: 1,
    explain: "TD backs up predictive value to the earliest reliable predictor, so both the model's prediction error and (per Ch. 15) dopamine responses migrate to the first cue that signals upcoming reward — matching behavioral data.",
  },
  {
    q: "The book's treatment of psychology is intended to show that RL...",
    options: [
      "is unrelated to animal learning",
      "shares deep computational principles with animal learning, informing and being informed by psychology",
      "replaces psychology",
      "only applies to games",
    ],
    answer: 1,
    explain: "Chapter 14 emphasizes the two-way relationship: RL provides computational theories of animal learning, and psychology provides phenomena and inspiration — a mutually reinforcing connection.",
  },
  {
    q: "Which RL element corresponds to the psychological notion of 'reinforcement'?",
    options: [
      "The state",
      "The reward (and, for learning, the reward prediction error that drives change)",
      "The policy",
      "The discount",
    ],
    answer: 1,
    explain: "Reinforcement corresponds to reward and, mechanistically, to the prediction error that strengthens or weakens behavior/associations — the driving signal in both Rescorla–Wagner/TD models and RL.",
  },
  {
    q: "The Rescorla–Wagner rule updates associative strength V by ΔV ∝ (λ − ΣV), where (λ − ΣV) is the...",
    options: [
      "reward",
      "prediction error (surprise): the difference between the US's value λ and the total prediction ΣV",
      "discount",
      "eligibility trace",
    ],
    answer: 1,
    explain: "In Rescorla–Wagner, λ represents the US's asymptotic value and ΣV the summed prediction from present cues; their difference is the prediction error that drives learning — the same error-correction idea as TD/RL.",
  },
  {
    q: "Which is TRUE about how RL informs the study of conditioning timing?",
    options: [
      "RL cannot model timing",
      "The TD model, via a complete-serial-compound or similar state representation, models within-trial timing that Rescorla–Wagner cannot",
      "Timing is irrelevant",
      "Only Monte Carlo models timing",
    ],
    answer: 1,
    explain: "By representing time within a trial (e.g., a series of internal states) and applying TD updates, the TD model reproduces the timing of anticipatory responses — an advance over trial-level Rescorla–Wagner.",
  },
  {
    q: "The correspondence table in Chapter 14 broadly maps: agent↔organism, environment↔world, action↔behavior, reward↔...",
    options: [
      "policy",
      "reinforcement (primary reward)",
      "value function",
      "discount",
    ],
    answer: 1,
    explain: "The chapter aligns RL and psychology terms: reward corresponds to (primary) reinforcement, value to learned prediction/expectation, and policy to behavioral tendencies — clarifying the computational–behavioral mapping.",
  },
  {
    q: "Why might an organism benefit from having BOTH model-free and model-based systems?",
    options: [
      "Redundancy only",
      "Model-free is fast/cheap once learned; model-based is flexible to changes (e.g., devaluation) — combining speed with adaptability",
      "Model-based is always better",
      "Model-free is useless",
    ],
    answer: 1,
    explain: "Model-free control gives quick, low-cost habitual responses, while model-based control adapts flexibly to new goals/changes. Having both lets an organism balance efficiency against flexibility — mirroring a key RL trade-off.",
  },
  {
    q: "Extinction (a conditioned response fading when the US stops) is explained by error-driven learning as...",
    options: [
      "increasing associative strength",
      "negative prediction errors (expected US absent) reducing the predictive association over trials",
      "random forgetting",
      "a model update",
    ],
    answer: 1,
    explain: "When the predicted US fails to occur, the prediction error is negative, driving down the associative strength — extinction. This is the error-correction rule operating in the downward direction.",
  },
  {
    q: "The concept of 'reward prediction' unifying classical conditioning and RL prediction implies that conditioned responses reflect...",
    options: [
      "random behavior",
      "learned value predictions, which RL value functions formalize",
      "the discount factor",
      "the policy only",
    ],
    answer: 1,
    explain: "Conditioned responses reflect the organism's learned predictions of upcoming significant events — exactly what RL value functions represent — making value estimation the shared computational core.",
  },
  {
    q: "Which best captures the chapter's stance on RL and animal learning theory?",
    options: [
      "They are unrelated fields",
      "RL formalizes and extends ideas long studied in animal learning, and the correspondence is mutually illuminating",
      "Animal learning has nothing to teach RL",
      "RL only models robots",
    ],
    answer: 1,
    explain: "Chapter 14 argues RL and animal-learning theory are deeply connected: RL gives precise models (TD, Rescorla–Wagner) of phenomena psychologists study, and those phenomena inspire and validate RL ideas.",
  },
  {
    q: "In the habitual/goal-directed framework, extensive repetition of a rewarded action tends to make behavior more...",
    options: [
      "goal-directed",
      "habitual (control shifts from model-based to model-free with overtraining)",
      "random",
      "exploratory",
    ],
    answer: 1,
    explain: "Overtraining shifts control from goal-directed (model-based) toward habitual (model-free): the behavior becomes automatic and less sensitive to outcome value, a well-documented transition mirrored by the two RL systems.",
  },
  {
    q: "The TD model can produce a prediction that a reward is 'earlier than expected,' generating a...",
    options: [
      "negative prediction error",
      "positive prediction error at the time of the earlier-than-expected cue/reward",
      "no error",
      "constant signal",
    ],
    answer: 1,
    explain: "An unexpectedly early reward or its predictor produces a positive TD error at that moment (the prediction jumps up), while omission at the expected time produces a negative error — patterns matched by dopamine data (Ch. 15).",
  },
  {
    q: "Which is a correct summary of Chapter 14?",
    options: [
      "RL and psychology are incompatible",
      "RL's prediction/control and model-free/model-based distinctions map onto classical/instrumental conditioning and habitual/goal-directed behavior, with error-driven models (Rescorla–Wagner, TD) explaining key phenomena",
      "Only classical conditioning matters",
      "RL cannot model conditioning",
    ],
    answer: 1,
    explain: "Chapter 14 draws the correspondence between RL constructs and animal-learning phenomena, highlighting error-driven learning (Rescorla–Wagner, TD) and the habitual/goal-directed ↔ model-free/model-based mapping.",
  },
  {
    q: "The prediction-error signal in these psychological models is significant partly because it is...",
    options: [
      "unmeasurable",
      "a candidate for a neural teaching signal — motivating the search for its biological correlate (dopamine, Ch. 15)",
      "only theoretical with no brain relevance",
      "the reward itself",
    ],
    answer: 1,
    explain: "Because error-driven models fit behavior so well, researchers sought a neural implementation of the prediction error — leading to the dopamine reward-prediction-error hypothesis, the subject of Chapter 15.",
  },
  {
    q: "Which statement about RL 'states' and animal representations is most accurate?",
    options: [
      "Animals have perfect Markov states",
      "The choice of state representation strongly affects the model's predictions, just as it does in RL (e.g., timing models require a temporal state representation)",
      "State representation is irrelevant",
      "Animals use the true environment model",
    ],
    answer: 1,
    explain: "As in RL, the assumed internal state representation shapes what the TD model predicts. Modeling response timing, for instance, requires a temporally-extended state representation — highlighting representation's importance in both fields.",
  },
  {
    q: "The chapter suggests that 'reward' in the brain should be understood as...",
    options: [
      "an external number handed to the animal",
      "an internally generated evaluative signal, consistent with RL placing reward at the agent–environment interface",
      "the value function",
      "the policy",
    ],
    answer: 1,
    explain: "Biological reward is produced by internal evaluative systems, not delivered as an external scalar. This fits the RL framing of reward as arising at the agent–environment boundary, reflecting the organism's own valuation.",
  },
  {
    q: "Overall, the psychology chapter strengthens the case that reinforcement learning is...",
    options: [
      "purely an engineering tool",
      "a computational theory relevant to natural intelligence, not just artificial agents",
      "unrelated to brains",
      "only about games",
    ],
    answer: 1,
    explain: "By showing RL models capture animal learning phenomena, Chapter 14 supports RL as a theory of learning in natural as well as artificial systems — a theme deepened by the neuroscience chapter.",
  }
);
