// ============================================================================
//  data-12-b.js — Chapter 12 (Eligibility Traces) expansion pool
// ============================================================================
QUESTIONS["12"].push(
  {
    q: "Eligibility traces unify and generalize which two families of methods?",
    options: [
      "DP and supervised learning",
      "Temporal-difference and Monte Carlo methods (via the parameter λ)",
      "Planning and search",
      "Bandits and MDPs",
    ],
    answer: 1,
    explain: "Eligibility traces (TD(λ)) span TD(0) (λ=0) to Monte Carlo (λ=1), unifying them with a single mechanism and parameter λ, and often outperforming either extreme.",
  },
  {
    q: "The λ-return G_t^λ weights the n-step return G_{t:t+n} by...",
    options: [
      "1/n",
      "(1−λ)λ^{n−1}",
      "γ^n",
      "a uniform weight",
    ],
    answer: 1,
    explain: "G_t^λ = (1−λ)Σ_{n≥1} λ^{n−1} G_{t:t+n} (plus a terminal term). The geometric weights (1−λ)λ^{n−1} sum to 1, blending all n-step returns. λ=0 → one-step; λ=1 → full return.",
  },
  {
    q: "The 'forward view' of TD(λ) defines the update using...",
    options: [
      "the eligibility trace",
      "the λ-return, which looks forward to future rewards/states (non-causal)",
      "the model",
      "the reward only",
    ],
    answer: 1,
    explain: "The forward view updates each state toward its λ-return, conceptually looking ahead to future outcomes. It is theoretically clean but not directly implementable online (needs the future).",
  },
  {
    q: "The 'backward view' of TD(λ) implements (approximately) the same updates using...",
    options: [
      "future returns",
      "an eligibility trace vector that remembers recently visited states, updated online each step by the TD error",
      "a distribution model",
      "Monte Carlo returns",
    ],
    answer: 1,
    explain: "The backward view keeps an eligibility trace z_t; each step's TD error δ_t updates all recently eligible states in proportion to their traces. This is causal, online, and incremental — the practical mechanism.",
  },
  {
    q: "The accumulating eligibility trace update is z_t = γλ z_{t−1} + ___.",
    options: [
      "0",
      "∇v̂(S_t,w) (the gradient/feature of the current state)",
      "the reward",
      "1 for all states",
    ],
    answer: 1,
    explain: "z_t = γλ z_{t−1} + ∇v̂(S_t,w): the trace decays by γλ and is incremented by the current state's gradient (feature vector). Weights update as w ← w + αδ_t z_t.",
  },
  {
    q: "In TD(λ), the eligibility trace decays each step by a factor of...",
    options: ["α", "γλ", "ε", "1"],
    answer: 1,
    explain: "Traces fade by γλ per step, so states visited longer ago are less 'eligible' for the current update. λ controls how slowly credit fades; γ is the usual discount.",
  },
  {
    q: "Setting λ = 0 in TD(λ) makes the algorithm equivalent to...",
    options: [
      "Monte Carlo",
      "one-step TD(0) (the trace collapses to only the current state)",
      "dynamic programming",
      "Sarsa",
    ],
    answer: 1,
    explain: "With λ=0, the trace decays instantly (γλ=0), so only the current state is updated by δ_t — exactly TD(0). Increasing λ spreads credit further back.",
  },
  {
    q: "Setting λ = 1 in TD(λ) makes it (approximately) equivalent to...",
    options: [
      "TD(0)",
      "Monte Carlo (credit propagates back with only γ decay, like a full return)",
      "value iteration",
      "Q-learning",
    ],
    answer: 1,
    explain: "With λ=1, traces decay only by γ, so a reward's credit reaches all preceding states as in a Monte Carlo return. Offline TD(1) equals every-visit MC; online it closely approximates it.",
  },
  {
    q: "A major computational advantage of the backward (trace) view over the forward (λ-return) view is that it...",
    options: [
      "requires the whole episode in memory",
      "updates online each step with memory/computation independent of episode length",
      "needs a model",
      "is exact for all λ",
    ],
    answer: 1,
    explain: "The eligibility trace lets TD(λ) update every step with per-step cost independent of how long the episode is — unlike the forward view, which conceptually needs future returns (the whole episode).",
  },
  {
    q: "The eligibility trace is described as a 'short-term memory' that...",
    options: [
      "stores rewards",
      "keeps a fading record of which states/features were recently active and thus eligible for learning updates",
      "stores the policy",
      "stores the model",
    ],
    answer: 1,
    explain: "The trace is a transient memory of recent state (feature) activations, decaying over time. It marks which components are 'eligible' to be adjusted when a TD error occurs — a temporal credit-assignment mechanism.",
  },
  {
    q: "The 'replacing' trace differs from the 'accumulating' trace by...",
    options: [
      "decaying faster",
      "resetting the trace for a revisited state/feature to 1 (or a fixed value) instead of adding to it",
      "using no decay",
      "ignoring the gradient",
    ],
    answer: 1,
    explain: "Replacing traces set a revisited component's trace to 1 rather than accumulating, which can improve performance (especially with frequent revisits) by preventing traces from growing too large. Dutch traces generalize these ideas.",
  },
  {
    q: "True Online TD(λ) uses a 'dutch trace' to...",
    options: [
      "approximate the forward view loosely",
      "reproduce the online λ-return (forward-view) updates EXACTLY at each step",
      "remove bootstrapping",
      "require a model",
    ],
    answer: 1,
    explain: "True Online TD(λ) combines a dutch trace with a corrected update so that its step-by-step behavior exactly matches the ideal online λ-return algorithm — often outperforming conventional TD(λ), especially at larger step sizes.",
  },
  {
    q: "Sarsa(λ) applies eligibility traces to...",
    options: [
      "state values for prediction",
      "action values for control, so a reward updates the whole recent trajectory of state–action pairs at once",
      "the reward function",
      "the model",
    ],
    answer: 1,
    explain: "Sarsa(λ) maintains traces over state–action features and combines them with the Sarsa TD error, assigning credit to all recently visited (s,a) pairs — dramatically speeding control, especially with delayed rewards.",
  },
  {
    q: "Why does Sarsa(λ) often learn much faster than one-step Sarsa on gridworld navigation?",
    options: [
      "It uses a model",
      "A single goal reward updates the entire recent path via the traces, instead of propagating one step per episode",
      "It removes exploration",
      "It ignores the discount",
    ],
    answer: 1,
    explain: "With traces, reaching the goal updates the values of all recently visited state–action pairs in one shot, so a good path is learned in far fewer episodes than one-step Sarsa, which propagates credit only one step at a time.",
  },
  {
    q: "The λ-return can be viewed as a specific way of averaging...",
    options: [
      "rewards",
      "n-step returns (a compound update with geometric weights)",
      "policies",
      "features",
    ],
    answer: 1,
    explain: "The λ-return is a compound update: a weighted average of all n-step returns with weights (1−λ)λ^{n−1}. Eligibility traces implement this averaging incrementally and online.",
  },
  {
    q: "For linear function approximation, the TD(λ) weight update is w ← w + αδ_t z_t, where z_t is...",
    options: [
      "the reward vector",
      "the eligibility-trace vector accumulating decayed feature vectors",
      "the policy",
      "the model",
    ],
    answer: 1,
    explain: "The trace z_t accumulates γλ-decayed feature vectors of recent states; the whole weight vector is nudged by αδ_t z_t each step, spreading the current TD error over recently active features.",
  },
  {
    q: "Off-policy eligibility traces require incorporating...",
    options: [
      "a larger step size",
      "importance-sampling ratios into the trace update (or using ratio-free variants), which can increase variance",
      "a distribution model",
      "the reward only",
    ],
    answer: 1,
    explain: "Off-policy TD(λ) multiplies traces by per-step importance ratios (e.g., in the trace decay), correcting for the behavior/target mismatch — but this can raise variance. Stable off-policy trace methods (GTD(λ), emphatic TD(λ)) address this.",
  },
  {
    q: "The offline λ-return algorithm and offline TD(λ) produce...",
    options: [
      "different updates",
      "the same total weight change at the end of an episode (they are equivalent offline)",
      "no updates",
      "Monte Carlo only",
    ],
    answer: 1,
    explain: "When updates are accumulated and applied only at episode end (offline), the backward-view TD(λ) and the forward-view λ-return algorithm yield identical total weight updates — establishing their equivalence.",
  },
  {
    q: "A benefit of eligibility traces over explicit n-step methods is that traces...",
    options: [
      "require choosing n",
      "avoid choosing a single n and avoid the n-step update delay, blending all horizons online with one parameter λ",
      "need a model",
      "only work for λ=1",
    ],
    answer: 1,
    explain: "Instead of picking one n and waiting n steps, traces geometrically blend all n-step returns and update every step immediately. One parameter λ controls the blend, and there is no fixed delay.",
  },
  {
    q: "Which is TRUE about intermediate λ values (0 < λ < 1)?",
    options: [
      "They are never useful",
      "They often yield the best performance, balancing bootstrapping (small λ) against long-return variance (large λ)",
      "They equal Monte Carlo",
      "They require a model",
    ],
    answer: 1,
    explain: "Just as intermediate n is often best for n-step methods, intermediate λ frequently gives the lowest error, trading off the bias of heavy bootstrapping against the variance of long returns.",
  },
  {
    q: "The eligibility trace mechanism assigns credit based on both recency and...",
    options: [
      "reward size",
      "frequency (how recently AND how often a state/feature was visited)",
      "the discount only",
      "the number of actions",
    ],
    answer: 1,
    explain: "Accumulating traces reflect both recency (decay) and frequency (repeated visits add up), so states visited recently and often are most eligible for updates — a heuristic for temporal credit assignment.",
  },
  {
    q: "True Online TD(λ) tends to outperform conventional (accumulating-trace) TD(λ) especially when...",
    options: [
      "the step size is tiny",
      "the step size is larger, where conventional TD(λ) only approximates the forward view but true online matches it exactly",
      "there is no reward",
      "λ=0",
    ],
    answer: 1,
    explain: "Conventional TD(λ) only approximates the online λ-return; the approximation degrades at larger step sizes. True Online TD(λ) matches the forward view exactly, so it is more robust and often better, particularly for larger α.",
  },
  {
    q: "Replacing traces are often preferred over accumulating traces because they...",
    options: [
      "grow without bound",
      "prevent a frequently-revisited feature's trace from becoming excessively large, improving stability/performance",
      "require a model",
      "remove the discount",
    ],
    answer: 1,
    explain: "By capping a revisited feature's trace (resetting to 1), replacing traces avoid the runaway growth accumulating traces can suffer with frequent revisits, often yielding better and more stable learning.",
  },
  {
    q: "Eligibility traces can be combined with function approximation, giving methods like...",
    options: [
      "tabular Q-learning only",
      "linear TD(λ) and Sarsa(λ) over features (e.g., tile coding), widely used in continuous control",
      "value iteration",
      "Monte Carlo tree search",
    ],
    answer: 1,
    explain: "TD(λ)/Sarsa(λ) work directly with feature vectors: the trace accumulates decayed features and the whole weight vector is updated by αδz. This combination (e.g., with tile coding) is effective and popular.",
  },
  {
    q: "The relationship 'TD(1) ≈ Monte Carlo' means that TD with λ=1...",
    options: [
      "ignores rewards",
      "propagates credit like a full return, so (offline) it equals every-visit Monte Carlo while still allowing online, incremental updates",
      "requires a model",
      "is one-step",
    ],
    answer: 1,
    explain: "λ=1 makes traces decay only by γ, spreading each reward's credit all the way back — equivalent to MC returns. Crucially, TD(1) can do this online/incrementally, unlike standard MC which waits for episode end.",
  },
  {
    q: "In Sarsa(λ), when a non-greedy (exploratory) action is taken, off-policy variants may...",
    options: [
      "increase the trace",
      "cut/zero the traces (for methods like Watkins's Q(λ)) because the target policy would not have taken that action",
      "add a reward",
      "increase the discount",
    ],
    answer: 1,
    explain: "In Watkins's Q(λ), traces are zeroed after a non-greedy action, since the greedy target policy's return no longer applies beyond that point. This preserves correctness at the cost of cutting traces often.",
  },
  {
    q: "Which correctly describes the memory cost of TD(λ) with a d-dimensional weight vector?",
    options: [
      "O(episode length)",
      "O(d) — one trace component per weight, independent of episode length",
      "O(number of states)",
      "O(1)",
    ],
    answer: 1,
    explain: "TD(λ) stores an eligibility trace of the same dimension as the weight vector (O(d)), independent of how long the episode runs — a key efficiency advantage of the backward view.",
  },
  {
    q: "The dutch trace is called that because...",
    options: [
      "it originated in dynamic programming",
      "it is a specific trace form (between accumulating and replacing) used to make True Online TD(λ) exactly match the forward view",
      "it removes bootstrapping",
      "it is only for tabular methods",
    ],
    answer: 1,
    explain: "The dutch trace is the particular trace variant (interpolating accumulating/replacing behavior with an extra correction term) that enables True Online TD(λ) to reproduce the online λ-return updates exactly.",
  },
  {
    q: "Which is TRUE about eligibility traces and delayed reward?",
    options: [
      "They make delayed reward harder",
      "They excel at delayed-reward problems by carrying credit back over many steps in a single update",
      "They require immediate reward",
      "They ignore rewards",
    ],
    answer: 1,
    explain: "Traces shine when rewards are delayed: a late reward's TD error updates all recently eligible states/actions at once, so credit reaches distant causes quickly — a major practical benefit.",
  },
  {
    q: "The parameter λ in TD(λ) is best described as controlling...",
    options: [
      "the discount",
      "the trace-decay rate, i.e., how far back in time credit is assigned (the degree of bootstrapping)",
      "the exploration rate",
      "the step size",
    ],
    answer: 1,
    explain: "λ (with γ) sets how quickly traces fade, i.e., how far credit propagates and how much the method relies on bootstrapping vs. longer returns. λ=0 is pure bootstrapping; λ=1 is MC-like.",
  },
  {
    q: "Compared to n-step methods, TD(λ) provides a ___ blend of horizons.",
    options: [
      "single fixed",
      "smooth (geometric) blend over all horizons via one parameter",
      "random",
      "model-based",
    ],
    answer: 1,
    explain: "n-step methods pick one horizon; TD(λ) geometrically averages all horizons at once. This smooth blend, controlled by a single λ, often gives robust performance without tuning a discrete n.",
  },
  {
    q: "Why is the equivalence of forward and backward views important?",
    options: [
      "It removes rewards",
      "It shows the intuitive λ-return (forward) is realized by a practical, causal, online mechanism (traces), justifying TD(λ)'s use",
      "It requires a model",
      "It only holds for λ=0",
    ],
    answer: 1,
    explain: "The forward view explains WHAT is computed (λ-return); the backward view shows HOW to compute it online with traces. Their (offline) equivalence connects the clean theory to a practical algorithm.",
  },
  {
    q: "In practice, which λ often works well as a default starting point?",
    options: [
      "λ = 0 always",
      "an intermediate value (e.g., around 0.8–0.95), then tuned",
      "λ = 1 always",
      "λ > 1",
    ],
    answer: 1,
    explain: "Intermediate λ (commonly ~0.8–0.95) is a reasonable default, capturing multi-step credit while limiting variance; the best value is problem-dependent and tuned empirically. (λ must be in [0,1].)",
  },
  {
    q: "Off-policy trace methods that are provably stable with approximation include...",
    options: [
      "naive TD(λ) only",
      "GTD(λ) and emphatic TD(λ) (extending Chapter 11's gradient-/emphatic-TD to traces)",
      "Monte Carlo only",
      "value iteration",
    ],
    answer: 1,
    explain: "Combining eligibility traces with the stable off-policy ideas of Chapter 11 yields GTD(λ) and emphatic TD(λ), which remain convergent under the deadly triad while enjoying the multi-step benefits of traces.",
  },
  {
    q: "The eligibility trace elegantly implements which principle of credit assignment?",
    options: [
      "Only the most recent state gets credit",
      "States/actions that were recently and frequently active share credit for a subsequent TD error, decaying with time",
      "All states get equal credit",
      "Credit is assigned by a model",
    ],
    answer: 1,
    explain: "Traces distribute a TD error's credit across recently active components, weighted by recency (and frequency for accumulating traces) — a simple, biologically-suggestive mechanism for temporal credit assignment.",
  },
  {
    q: "Which statement about TD(λ) and online learning is correct?",
    options: [
      "TD(λ) can only learn offline",
      "TD(λ) learns online every step, unlike Monte Carlo which must wait for the return, yet can capture MC-like multi-step credit via λ",
      "TD(λ) needs a model",
      "TD(λ) cannot bootstrap",
    ],
    answer: 1,
    explain: "TD(λ) updates online each step (like TD) while still assigning multi-step credit (up to MC-like at λ=1) through the trace — combining online learning with long-horizon credit assignment.",
  },
  {
    q: "Which is a correct reason True Online TD(λ) is theoretically appealing?",
    options: [
      "It ignores the forward view",
      "It exactly equals the online forward-view (λ-return) algorithm step by step, not just at episode end",
      "It removes traces",
      "It requires Monte Carlo returns",
    ],
    answer: 1,
    explain: "Unlike conventional TD(λ) (which matches the forward view only offline/approximately), True Online TD(λ) matches the online λ-return exactly at every step, giving cleaner theory and often better empirical performance.",
  },
  {
    q: "For control, the trace in Sarsa(λ) accumulates over which features?",
    options: [
      "state features only",
      "state–action features (the gradient of q̂(S,A,w))",
      "reward features",
      "model features",
    ],
    answer: 1,
    explain: "Sarsa(λ) traces accumulate the gradient of the action-value function ∇q̂(S,A,w) — i.e., state–action features — so credit is assigned to recently visited (s,a) pairs when a TD error occurs.",
  },
  {
    q: "The chapter's overall message is that eligibility traces provide...",
    options: [
      "a replacement for rewards",
      "a computationally efficient, online mechanism to obtain the benefits of multi-step (MC-to-TD) methods with a single parameter λ",
      "a distribution model",
      "a way to avoid value functions",
    ],
    answer: 1,
    explain: "Chapter 12 presents eligibility traces as the elegant, online way to blend TD and Monte Carlo (via λ), delivering fast multi-step credit assignment for prediction (TD(λ)) and control (Sarsa(λ)) with bounded per-step cost.",
  },
  {
    q: "Which correctly states the effect of γλ on the trace time constant?",
    options: [
      "Larger γλ → shorter memory",
      "Larger γλ → longer effective memory (credit persists further back in time)",
      "γλ has no effect",
      "γλ sets the reward",
    ],
    answer: 1,
    explain: "The trace decays by γλ per step, so a larger γλ means slower decay and a longer effective memory, propagating credit further into the past. Smaller γλ concentrates credit near the present.",
  },
  {
    q: "A practical caution with accumulating traces and function approximation is that...",
    options: [
      "they never diverge",
      "combined with large step sizes they can cause instability; replacing/dutch traces or True Online TD(λ) improve robustness",
      "they require a model",
      "they only work tabularly",
    ],
    answer: 1,
    explain: "Accumulating traces with large α can overshoot and destabilize learning. Replacing traces, dutch traces, and True Online TD(λ) offer more robust behavior, especially with function approximation and larger step sizes.",
  }
);
