// ============================================================================
//  data-13-b.js — Chapter 13 (Policy Gradient Methods) expansion pool
// ============================================================================
QUESTIONS["13"].push(
  {
    q: "Policy gradient methods learn a parameterized policy π(a|s,θ) and optimize θ by...",
    options: [
      "acting greedily w.r.t. a value function",
      "gradient ASCENT on a scalar performance measure J(θ)",
      "solving the Bellman optimality equation",
      "dynamic programming",
    ],
    answer: 1,
    explain: "Policy gradient methods parameterize the policy directly and ascend a performance measure J(θ) using estimates of its gradient ∇J(θ). Actions come from the policy, not from argmax over a value function.",
  },
  {
    q: "For discrete actions, a common policy parameterization uses action preferences h(s,a,θ) with a...",
    options: [
      "greedy rule",
      "soft-max: π(a|s,θ) = e^{h(s,a,θ)} / Σ_b e^{h(s,b,θ)}",
      "uniform rule",
      "value function",
    ],
    answer: 1,
    explain: "Soft-max over action preferences gives a differentiable stochastic policy. Preferences can be linear in features, h(s,a,θ)=θᵀx(s,a), or produced by a neural network.",
  },
  {
    q: "One advantage of policy parameterization over ε-greedy value methods is that the policy can...",
    options: [
      "never be stochastic",
      "approach a deterministic policy smoothly (probabilities change continuously), aiding convergence",
      "avoid all exploration",
      "ignore the reward",
    ],
    answer: 1,
    explain: "Soft-max policies can shift action probabilities gradually toward determinism, giving smoother learning than ε-greedy value methods where a tiny value change can flip the greedy action abruptly.",
  },
  {
    q: "Another advantage: policy methods can represent optimal STOCHASTIC policies, which matters when...",
    options: [
      "the environment is deterministic",
      "the best policy is genuinely random (e.g., partial observability, or games like rock-paper-scissors)",
      "there is one action",
      "rewards are dense",
    ],
    answer: 1,
    explain: "In partially observable or adversarial settings the optimal policy may be stochastic. Action-value ε-greedy methods target a (near-)deterministic greedy policy, whereas policy methods can learn arbitrary action probabilities.",
  },
  {
    q: "The policy gradient theorem's key property is that ∇J(θ) is expressed WITHOUT...",
    options: [
      "the reward",
      "the derivative of the state distribution with respect to θ (which depends on the unknown environment)",
      "the policy",
      "the value function",
    ],
    answer: 1,
    explain: "∇J(θ) ∝ Σ_s μ(s) Σ_a q_π(s,a) ∇π(a|s,θ) contains no term for ∇μ(θ). Avoiding the (unknown, θ-dependent) state-distribution gradient is what makes stochastic-gradient estimation of ∇J possible.",
  },
  {
    q: "The REINFORCE update is θ ← θ + α G_t ∇ln π(A_t|S_t,θ). The factor ∇ln π is called the...",
    options: [
      "reward",
      "eligibility vector (score function)",
      "discount",
      "baseline",
    ],
    answer: 1,
    explain: "∇ln π(A_t|S_t,θ) is the eligibility vector (a.k.a. score function). REINFORCE moves θ in this direction scaled by the return G_t, increasing the probability of actions that led to high return.",
  },
  {
    q: "REINFORCE uses which quantity as its (unbiased) estimate of q_π(S_t,A_t)?",
    options: [
      "A bootstrapped one-step target",
      "The sampled return G_t (Monte Carlo)",
      "The maximum action value",
      "The reward only",
    ],
    answer: 1,
    explain: "REINFORCE is a Monte Carlo policy-gradient method: it uses the complete sampled return G_t as an unbiased estimate of q_π(S_t,A_t). This makes it unbiased but high-variance, and it requires complete episodes.",
  },
  {
    q: "Subtracting a state-dependent baseline b(s) from the return in REINFORCE...",
    options: [
      "biases the gradient",
      "leaves the expected gradient unchanged (unbiased) while reducing variance",
      "changes the optimal policy",
      "requires a model",
    ],
    answer: 1,
    explain: "Because Σ_a ∇π(a|s,θ) = 0, subtracting any b(s) does not change the expected update — it stays unbiased — but a good baseline (e.g., v̂(s)) can greatly reduce variance and speed learning.",
  },
  {
    q: "A natural and effective choice of baseline is...",
    options: [
      "the reward",
      "an estimate of the state value, b(s) = v̂(s,w)",
      "zero always",
      "the discount factor",
    ],
    answer: 1,
    explain: "Using the estimated state value as the baseline makes the update proportional to (G_t − v̂(S_t)), an estimate of the advantage. This reduces variance substantially compared with raw returns.",
  },
  {
    q: "Actor–critic methods differ from REINFORCE-with-baseline in that the critic...",
    options: [
      "is only a baseline (no bootstrapping)",
      "BOOTSTRAPS — it provides a TD-based value used in the target, introducing bias but reducing variance and enabling online updates",
      "replaces the actor",
      "requires a model",
    ],
    answer: 1,
    explain: "In REINFORCE-with-baseline the value is used only as a baseline (no bootstrapping). In actor–critic the critic bootstraps: the actor is updated using the TD error δ = R + γv̂(S') − v̂(S), trading some bias for lower variance and online learning.",
  },
  {
    q: "In one-step actor–critic, the actor update uses the TD error δ as...",
    options: [
      "a reward",
      "a (biased) estimate of the advantage that scales the eligibility vector: θ ← θ + α δ ∇ln π(A|S,θ)",
      "the discount",
      "the baseline",
    ],
    answer: 1,
    explain: "The TD error δ = R + γv̂(S') − v̂(S) approximates the advantage of the action taken. The actor increases the probability of actions with positive δ, scaling ∇ln π by δ.",
  },
  {
    q: "The 'critic' in actor–critic is responsible for...",
    options: [
      "selecting actions",
      "evaluating the current policy by learning a value function (used to compute the TD error/advantage)",
      "generating the reward",
      "storing the model",
    ],
    answer: 1,
    explain: "The critic estimates a value function (e.g., v̂) to evaluate the actor's policy, producing the TD error that critiques each action. The actor uses this critique to adjust the policy.",
  },
  {
    q: "For CONTINUOUS action spaces, the policy is commonly parameterized as a...",
    options: [
      "soft-max over infinitely many actions",
      "Gaussian with state-dependent mean μ(s,θ) and standard deviation σ(s,θ)",
      "greedy rule",
      "uniform distribution",
    ],
    answer: 1,
    explain: "For continuous actions, a Gaussian policy outputs μ(s,θ) and σ(s,θ); actions are sampled from N(μ,σ²). Learning σ lets the agent control its own exploration, tightening the distribution as it becomes confident.",
  },
  {
    q: "Learning the standard deviation σ in a Gaussian policy allows the agent to...",
    options: [
      "ignore exploration",
      "adapt its own exploration level — large σ explores broadly, small σ exploits precisely",
      "remove the reward",
      "avoid the mean",
    ],
    answer: 1,
    explain: "By parameterizing and learning σ(s,θ), the agent controls the spread of its action distribution: it can explore widely when uncertain and narrow toward the best action as it learns — self-regulated exploration.",
  },
  {
    q: "Why does REINFORCE tend to have HIGH variance?",
    options: [
      "It bootstraps",
      "It uses full Monte Carlo returns (sums of many random rewards) to weight the gradient",
      "It uses a model",
      "It is deterministic",
    ],
    answer: 1,
    explain: "The full return G_t aggregates many random rewards along a trajectory, so it is noisy. Weighting the gradient by this noisy return gives high-variance updates — mitigated by baselines and, further, by actor–critic bootstrapping.",
  },
  {
    q: "The performance measure J(θ) for episodic problems is typically...",
    options: [
      "the immediate reward",
      "the value of the start state, v_{π_θ}(s_0)",
      "the average feature",
      "the discount",
    ],
    answer: 1,
    explain: "For episodic tasks, J(θ) is usually the expected return from the designated start state, v_{π_θ}(s_0). The policy gradient theorem provides ∇J(θ) in a form amenable to sampling.",
  },
  {
    q: "For continuing problems, the policy-gradient performance measure is usually...",
    options: [
      "the start-state value",
      "the average reward rate r(π_θ)",
      "the reward variance",
      "the discount",
    ],
    answer: 1,
    explain: "In continuing tasks, J(θ) = r(π_θ), the average reward per step. A corresponding policy gradient theorem (with differential values) applies, paralleling the episodic case.",
  },
  {
    q: "The 'advantage' A(s,a) = q_π(s,a) − v_π(s) measures...",
    options: [
      "the reward",
      "how much better action a is than the policy's average in state s",
      "the discount",
      "the number of visits",
    ],
    answer: 1,
    explain: "The advantage quantifies an action's value relative to the state's value under the policy. Positive advantage means better-than-average; policy gradients naturally increase the probability of positive-advantage actions.",
  },
  {
    q: "Which is TRUE about actor–critic's bias–variance trade-off versus REINFORCE?",
    options: [
      "Actor–critic has higher variance and no bias",
      "Actor–critic reduces variance (via bootstrapping) at the cost of introducing bias, and enables fully online/continual updates",
      "They are identical",
      "REINFORCE bootstraps more",
    ],
    answer: 1,
    explain: "Bootstrapping in the critic lowers variance and allows step-by-step online learning, but introduces bias (the critic is imperfect). REINFORCE is unbiased but high-variance and needs complete episodes.",
  },
  {
    q: "The score function ∇ln π(a|s,θ) for a soft-max policy with linear preferences equals...",
    options: [
      "x(s,a)",
      "x(s,a) − Σ_b π(b|s,θ) x(s,b) (feature minus its expected value under the policy)",
      "the reward",
      "zero",
    ],
    answer: 1,
    explain: "For linear soft-max, ∇ln π(a|s,θ) = x(s,a) − E_{b∼π}[x(s,b)]. The update thus pushes preferences toward features of taken actions that outperform the policy's average — a clean, interpretable form.",
  },
  {
    q: "Policy-gradient methods are especially advantageous when...",
    options: [
      "the action space is tiny and discrete",
      "the action space is large/continuous, or the optimal policy is stochastic, or a smooth policy parameterization is natural",
      "a model is available",
      "rewards are deterministic",
    ],
    answer: 1,
    explain: "They shine with continuous/high-dimensional actions (no argmax over infinite actions), when optimal policies are stochastic, or when a differentiable policy is a good fit — cases where value-based ε-greedy struggles.",
  },
  {
    q: "In actor–critic, eligibility traces can be applied to...",
    options: [
      "only the critic",
      "both the actor (policy parameters) and the critic (value parameters), for multi-step credit assignment",
      "neither",
      "the reward",
    ],
    answer: 1,
    explain: "Actor–critic can use separate eligibility traces for the actor and critic (actor–critic with traces), assigning multi-step credit to both the policy and value updates, accelerating learning as in TD(λ)/Sarsa(λ).",
  },
  {
    q: "Why is a baseline that does NOT depend on the action (only on the state) required for unbiasedness?",
    options: [
      "Action-dependent baselines are simpler",
      "Only a state-dependent baseline satisfies Σ_a ∇π(a|s,θ)·b(s) = b(s)·Σ_a∇π = 0, leaving the expected gradient unchanged",
      "The reward requires it",
      "It reduces the discount",
    ],
    answer: 1,
    explain: "Because Σ_a ∇π(a|s,θ)=0, a state-only baseline factors out with zero expected effect. An action-dependent term would not cancel and could bias the gradient (unless carefully constructed, as in some advanced methods).",
  },
  {
    q: "REINFORCE with baseline can be seen as a special actor–critic where the value function is used...",
    options: [
      "to bootstrap the target",
      "ONLY as a baseline (no bootstrapping), so it is technically not a full actor–critic",
      "to select actions",
      "as the reward",
    ],
    answer: 1,
    explain: "The book distinguishes them: REINFORCE-with-baseline uses the value only as a variance-reducing baseline (no bootstrapping), whereas actor–critic uses the value to bootstrap the target. Bootstrapping is the dividing line.",
  },
  {
    q: "A key theoretical guarantee of policy-gradient methods is convergence to...",
    options: [
      "the global optimum always",
      "at least a local optimum of J(θ) (under standard stochastic-approximation conditions), since they follow the gradient",
      "the tabular optimal policy",
      "the reward",
    ],
    answer: 1,
    explain: "As stochastic gradient ascent, policy-gradient methods converge to a local optimum of the (generally nonconvex) performance measure under suitable step-size conditions — a smoother convergence story than value-based methods with function approximation.",
  },
  {
    q: "Compared to value-based methods, a disadvantage of vanilla policy-gradient methods is that they...",
    options: [
      "cannot represent stochastic policies",
      "often have high variance and can converge slowly / to local optima",
      "require a model",
      "cannot use function approximation",
    ],
    answer: 1,
    explain: "Vanilla policy gradients (esp. REINFORCE) suffer high variance and can be sample-inefficient, converging slowly and only to local optima. Baselines, actor–critic, and modern variants address these issues.",
  },
  {
    q: "The Gaussian policy's mean μ(s,θ) and std σ(s,θ) are typically...",
    options: [
      "fixed constants",
      "parameterized functions of the state (e.g., linear in features or neural-network outputs)",
      "the reward and discount",
      "the value function",
    ],
    answer: 1,
    explain: "Both μ and σ are learned functions of the state, so the policy can output state-appropriate action means and exploration levels. Often σ is parameterized via its logarithm to keep it positive.",
  },
  {
    q: "Actor–critic methods are attractive for online, continuing tasks because they...",
    options: [
      "require complete episodes",
      "can update the policy and value at every step (bootstrapping), without waiting for episode returns",
      "need a model",
      "avoid value functions",
    ],
    answer: 1,
    explain: "Because the critic bootstraps, actor–critic updates both actor and critic each step, enabling fully online, incremental learning suited to continuing tasks — unlike REINFORCE, which needs full returns.",
  },
  {
    q: "The policy gradient theorem holds for both episodic and continuing settings with...",
    options: [
      "completely different forms",
      "analogous forms (start-state value for episodic; average reward with differential values for continuing)",
      "no value function",
      "only deterministic policies",
    ],
    answer: 1,
    explain: "The theorem has parallel versions: ∇v_{π}(s_0) for episodic and ∇r(π) (using differential action values) for continuing tasks, both avoiding the state-distribution gradient and enabling sample-based estimation.",
  },
  {
    q: "Which best describes how policy-gradient methods 'explore'?",
    options: [
      "Via ε-greedy over values",
      "Through the stochasticity of the policy itself (e.g., soft-max probabilities or Gaussian noise), which is learned",
      "They do not explore",
      "Via a model",
    ],
    answer: 1,
    explain: "Exploration is intrinsic to the stochastic policy: soft-max spreads probability over actions, and Gaussian policies inject noise via σ. As learning proceeds, the policy can sharpen, reducing exploration naturally.",
  },
  {
    q: "A well-chosen baseline reduces variance most when it...",
    options: [
      "is always zero",
      "closely tracks the expected return from each state (i.e., approximates v_π(s))",
      "equals the reward",
      "is action-dependent",
    ],
    answer: 1,
    explain: "The optimal (variance-minimizing) baseline is close to the state value, so (G_t − b(s)) has small magnitude on average, shrinking update variance. Hence v̂(s) is the standard baseline choice.",
  },
  {
    q: "In actor–critic, if the critic is inaccurate early in learning, the actor updates are...",
    options: [
      "perfectly unbiased",
      "biased (since δ uses imperfect value estimates), but this bias diminishes as the critic improves",
      "impossible",
      "identical to REINFORCE",
    ],
    answer: 1,
    explain: "Bootstrapping through an imperfect critic biases the actor's gradient estimate. As the critic's value estimates improve, the bias decreases — the standard bias–variance trade-off of bootstrapping.",
  },
  {
    q: "Which is a correct statement about REINFORCE's update direction?",
    options: [
      "It decreases the probability of high-return actions",
      "It increases the probability of actions that led to higher-than-baseline returns and decreases it for lower ones",
      "It ignores the return",
      "It selects actions greedily",
    ],
    answer: 1,
    explain: "REINFORCE adjusts θ so that actions followed by high (relative to baseline) returns become more likely, and those followed by low returns become less likely — reinforcing good behavior via the score function.",
  },
  {
    q: "Policy-gradient methods parameterize the policy so that small parameter changes cause small policy changes. This helps because...",
    options: [
      "it removes exploration",
      "it yields smoother, more stable learning dynamics than value-based methods where the greedy policy can change discontinuously",
      "it requires a model",
      "it eliminates the reward",
    ],
    answer: 1,
    explain: "Smooth dependence of the policy on θ gives gradual, stable improvement. In value-based methods, an infinitesimal value change can flip the greedy action, causing abrupt policy changes and potential instability.",
  },
  {
    q: "Which pairing correctly matches method to update target?",
    options: [
      "REINFORCE: TD error; actor–critic: full return",
      "REINFORCE: full return G_t; actor–critic: bootstrapped TD error δ",
      "Both use the full return",
      "Both use the TD error",
    ],
    answer: 1,
    explain: "REINFORCE weights the gradient by the Monte Carlo return G_t; actor–critic weights it by the bootstrapped TD error δ. This is the essential algorithmic difference and the source of their bias–variance contrast.",
  },
  {
    q: "The advantage-actor–critic view interprets the actor update as ascending...",
    options: [
      "the reward",
      "an estimate of E[advantage · ∇ln π], increasing probability of positive-advantage actions",
      "the discount",
      "the value error",
    ],
    answer: 1,
    explain: "Using the TD error (an advantage estimate) times the score function, actor–critic ascends E[A(s,a)∇ln π(a|s)], nudging the policy toward actions with positive advantage — the basis of A2C/A3C-style methods.",
  },
  {
    q: "Which is TRUE about combining policy gradients with function approximation?",
    options: [
      "It is impossible",
      "It is natural — both actor (policy) and critic (value) are typically parameterized (e.g., neural networks), enabling deep policy-gradient/actor–critic methods",
      "It requires a tabular policy",
      "It removes exploration",
    ],
    answer: 1,
    explain: "Policy-gradient methods are built for function approximation: the policy (and critic) are parameterized functions, often neural networks. This underlies modern deep actor–critic algorithms (A2C, PPO, etc.).",
  },
  {
    q: "The main reason policy-gradient methods avoid the deadly triad's worst instabilities is that they...",
    options: [
      "never use value functions",
      "directly optimize the policy via gradient ascent (the actor doesn't bootstrap on itself the way off-policy value bootstrapping does), though critics can still be delicate",
      "require a model",
      "use exploring starts",
    ],
    answer: 1,
    explain: "The actor follows a genuine gradient of performance, giving convergence to local optima. Instability concerns mainly involve the critic; the policy-gradient structure itself is comparatively well-behaved.",
  },
  {
    q: "REINFORCE requires which condition on the policy parameterization?",
    options: [
      "It must be deterministic",
      "It must be differentiable in θ and assign nonzero probability to actions (so ∇ln π is defined and exploration occurs)",
      "It must be tabular",
      "It must use a model",
    ],
    answer: 1,
    explain: "Policy-gradient methods need a differentiable, stochastic policy (π(a|s,θ) > 0 with well-defined ∇ln π). Soft-max and Gaussian policies satisfy this, providing both differentiability and exploration.",
  },
  {
    q: "The overall message of Chapter 13 is that policy-gradient methods...",
    options: [
      "are inferior to value methods in all cases",
      "directly learn parameterized (possibly stochastic, continuous) policies via gradient ascent, with REINFORCE, baselines, and actor–critic forming a spectrum of bias–variance trade-offs",
      "require a model",
      "cannot use value functions",
    ],
    answer: 1,
    explain: "Chapter 13 presents policy-gradient methods (REINFORCE → +baseline → actor–critic), the policy gradient theorem, continuous-action (Gaussian) policies, and their advantages — a major alternative/complement to value-based RL.",
  },
  {
    q: "A soft-max policy over action preferences can approach a deterministic optimal policy by...",
    options: [
      "keeping preferences equal",
      "driving the preferred action's preference much higher than the others (probabilities → near 1)",
      "increasing the reward",
      "reducing the discount",
    ],
    answer: 1,
    explain: "As the preference gap grows, the soft-max probability of the best action approaches 1. Unlike ε-greedy (stuck at ≥ε exploration), a soft-max policy can become arbitrarily close to deterministic if that is optimal.",
  }
);
