// ============================================================================
//  data-16-b.js — Chapter 16 (Applications and Case Studies) expansion pool
// ============================================================================
QUESTIONS["16"].push(
  {
    q: "TD-Gammon learned to play backgammon primarily through...",
    options: [
      "supervised learning from grandmaster games",
      "TD(λ) with a neural network value function trained via self-play",
      "exhaustive game-tree search",
      "hand-coded rules only",
    ],
    answer: 1,
    explain: "Tesauro's TD-Gammon combined TD(λ) with a multilayer neural network, learning a position value function almost entirely from self-play — a celebrated early success of RL plus nonlinear function approximation.",
  },
  {
    q: "A remarkable outcome of TD-Gammon was that it...",
    options: [
      "played worse than beginners",
      "reached expert/near-world-class play and even influenced human opening theory with novel strategies",
      "required no learning",
      "only memorized games",
    ],
    answer: 1,
    explain: "TD-Gammon reached top-level play and discovered move preferences that changed how human experts evaluated certain positions — demonstrating RL could produce genuinely novel, strong strategies.",
  },
  {
    q: "Backgammon's dice rolls make it a good match for TD learning because...",
    options: [
      "the game is deterministic",
      "the stochasticity yields smooth value functions and abundant varied self-play experience, aiding TD generalization",
      "there are no rewards",
      "the state space is tiny",
    ],
    answer: 1,
    explain: "The randomness of dice smooths the value landscape and generates diverse positions during self-play, which suited TD(λ) with neural-network generalization — part of why TD-Gammon worked so well.",
  },
  {
    q: "Arthur Samuel's checkers program (1950s–60s) was a pioneer because it used...",
    options: [
      "deep neural networks",
      "an early form of temporal-difference learning and self-play to tune an evaluation function, before such methods were formalized",
      "MCTS",
      "a complete solution of checkers",
    ],
    answer: 1,
    explain: "Samuel's checkers player used self-play and an early TD-like update to adjust its evaluation function's weights — anticipating key RL ideas decades before the modern theory existed.",
  },
  {
    q: "IBM Watson used reinforcement learning notably for...",
    options: [
      "understanding language",
      "deciding Daily-Double wagering (and related strategic betting) in Jeopardy!",
      "buzzing in",
      "reading the clues",
    ],
    answer: 1,
    explain: "Watson applied RL to strategic decisions such as Daily-Double wager sizing, optimizing expected game outcomes — a decision-theoretic use of RL within the larger system.",
  },
  {
    q: "DeepMind's DQN achieved human-level play on many Atari games by learning...",
    options: [
      "from hand-crafted features per game",
      "action values end-to-end from raw pixels using a convolutional network, with experience replay and a target network",
      "a full model of each game",
      "purely by policy gradients",
    ],
    answer: 1,
    explain: "DQN combined Q-learning with a deep convolutional network taking raw screen pixels, stabilized by experience replay and a periodically-updated target network — one architecture learning dozens of Atari games.",
  },
  {
    q: "In DQN, experience replay serves to...",
    options: [
      "increase the discount factor",
      "store transitions and sample them randomly, breaking correlations between consecutive updates and reusing data",
      "remove the reward",
      "make learning on-policy",
    ],
    answer: 1,
    explain: "Experience replay decorrelates the highly correlated stream of consecutive transitions and improves data efficiency by reusing each transition many times — key to stabilizing off-policy deep Q-learning.",
  },
  {
    q: "In DQN, the target network is used to...",
    options: [
      "select actions",
      "provide a slowly-changing bootstrap target, reducing the instability of chasing a constantly-moving target",
      "store the reward",
      "compute the policy gradient",
    ],
    answer: 1,
    explain: "The target network holds frozen weights (updated periodically) to compute the TD target, so the network isn't chasing its own rapidly changing estimates — mitigating divergence from the deadly triad in deep Q-learning.",
  },
  {
    q: "DQN's input preprocessing typically stacked several recent frames in order to...",
    options: [
      "increase resolution",
      "capture motion/velocity information, making the state closer to Markov",
      "reduce memory",
      "remove color",
    ],
    answer: 1,
    explain: "A single Atari frame lacks velocity/direction; stacking consecutive frames gives the network the temporal information needed to infer motion, making the state representation more nearly Markov.",
  },
  {
    q: "AlphaGo defeated top human Go players by combining...",
    options: [
      "only supervised learning",
      "deep policy and value networks with Monte Carlo Tree Search, trained via supervised learning then self-play RL",
      "brute-force full-width search",
      "tabular Q-learning",
    ],
    answer: 1,
    explain: "AlphaGo paired deep neural networks (policy and value) with MCTS. It was initialized from human games (supervised) and improved through self-play reinforcement learning — achieving superhuman Go.",
  },
  {
    q: "AlphaGo Zero differed from the original AlphaGo mainly in that it...",
    options: [
      "used more human data",
      "learned entirely from self-play with NO human game data, starting from random play",
      "abandoned neural networks",
      "did not use search",
    ],
    answer: 1,
    explain: "AlphaGo Zero learned from scratch by self-play alone, without human games, using a single network for policy and value and MCTS for improvement — surpassing the earlier, human-data-initialized AlphaGo.",
  },
  {
    q: "In AlphaGo/AlphaZero, MCTS is used at both training and play time to...",
    options: [
      "replace the neural network",
      "improve the network's raw policy (search produces stronger move distributions used as training targets and for play)",
      "remove exploration",
      "store the reward",
    ],
    answer: 1,
    explain: "MCTS acts as a policy-improvement operator: guided by the networks, it produces stronger move probabilities than the raw policy, which are used both to select moves and as targets to train the policy network.",
  },
  {
    q: "A recurring recipe across these landmark successes is RL combined with...",
    options: [
      "small tabular representations",
      "powerful function approximation (deep networks), abundant self-play/simulation, and often search",
      "no exploration",
      "a perfect given model",
    ],
    answer: 1,
    explain: "TD-Gammon, DQN, and AlphaGo share the pattern: RL scaled by strong (often deep) function approximation, massive self-generated experience, and — where helpful — planning/search. This recipe underlies modern RL breakthroughs.",
  },
  {
    q: "RL has been applied to computer systems problems such as...",
    options: [
      "none",
      "memory controller / resource scheduling optimization (e.g., DRAM access scheduling)",
      "only board games",
      "spell checking",
    ],
    answer: 1,
    explain: "The book describes RL applied to systems tasks like DRAM memory-controller scheduling, where an agent learns policies to improve throughput — showing RL's reach beyond games into engineering optimization.",
  },
  {
    q: "The autonomous-helicopter and thermal-soaring examples illustrate RL applied to...",
    options: [
      "text processing",
      "continuous control of physical/aerial systems",
      "board games",
      "database queries",
    ],
    answer: 1,
    explain: "RL (and related methods) have been applied to challenging continuous control of aerial systems, such as aerobatic helicopter flight and glider thermal soaring — demonstrating RL for real-world control.",
  },
  {
    q: "Personalized web-content/recommendation applications frame the problem as RL by treating...",
    options: [
      "each click independently with no state",
      "user interactions as sequential decisions where actions (what to show) affect future engagement (long-term reward)",
      "recommendations as supervised labels only",
      "the reward as fixed",
    ],
    answer: 1,
    explain: "Framing recommendation as sequential decision-making — where shown content influences future user behavior and long-term engagement — lets RL optimize cumulative reward rather than just immediate clicks.",
  },
  {
    q: "Why was learning from RAW PIXELS in Atari a significant milestone?",
    options: [
      "It required no computation",
      "It showed RL agents could learn effective control directly from high-dimensional sensory input, learning their own features end-to-end",
      "It used a full model",
      "It only worked on one game",
    ],
    answer: 1,
    explain: "DQN learning many games from raw pixels demonstrated end-to-end deep RL: the agent learned useful representations and control from high-dimensional input with the same architecture — a major step toward general agents.",
  },
  {
    q: "A common challenge these applications had to overcome was...",
    options: [
      "too little data",
      "instability of combining RL with deep function approximation (addressed via replay, target networks, self-play, and search)",
      "the absence of rewards",
      "having no actions",
    ],
    answer: 1,
    explain: "Scaling RL with deep networks risks instability (the deadly triad). The successful systems introduced stabilizers — experience replay, target networks, self-play, MCTS — to make deep RL work reliably.",
  },
  {
    q: "AlphaZero generalized AlphaGo Zero by...",
    options: [
      "adding human data",
      "applying the same self-play + MCTS + deep-network approach to multiple games (Go, chess, shogi) without game-specific knowledge",
      "removing search",
      "using tabular methods",
    ],
    answer: 1,
    explain: "AlphaZero showed the self-play, MCTS, and deep-network recipe was general: with only the rules, it mastered Go, chess, and shogi at superhuman level, without domain-specific tuning — a strong demonstration of generality.",
  },
  {
    q: "TD-Gammon's use of self-play was important because it...",
    options: [
      "required a database of games",
      "generated effectively unlimited training experience without needing human-labeled data",
      "prevented learning",
      "used a model of the opponent",
    ],
    answer: 1,
    explain: "Self-play let TD-Gammon generate vast amounts of its own training experience, sidestepping the need for labeled expert games — a theme central to later systems like AlphaGo Zero.",
  },
  {
    q: "Which best characterizes the value network in AlphaGo?",
    options: [
      "It selects the final move directly",
      "It estimates the probability of winning from a position (a value function), used to evaluate leaves in the search",
      "It stores the reward function",
      "It is a tabular lookup",
    ],
    answer: 1,
    explain: "The value network predicts the expected game outcome (win probability) from a board position, serving as a learned value function that evaluates positions during MCTS — reducing the need for full rollouts.",
  },
  {
    q: "The policy network in AlphaGo primarily...",
    options: [
      "evaluates final outcomes",
      "predicts a distribution over promising moves, guiding/narrowing the MCTS search",
      "stores transitions",
      "computes the discount",
    ],
    answer: 1,
    explain: "The policy network outputs move probabilities that focus the search on promising actions, making MCTS tractable in Go's enormous branching factor. Value and policy networks together power the search.",
  },
  {
    q: "A lesson from these case studies is that RL performance scales strongly with...",
    options: [
      "hand-engineering per problem",
      "computation and data (self-play/simulation) combined with general learning and search methods",
      "smaller networks",
      "avoiding exploration",
    ],
    answer: 1,
    explain: "The successes came from general methods (learning + search) that scale with computation and self-generated data, rather than heavy problem-specific engineering — a theme the frontiers chapter also emphasizes.",
  },
  {
    q: "Which is TRUE about DQN's use of Q-learning?",
    options: [
      "It made Q-learning on-policy",
      "It kept Q-learning off-policy (learning greedy values while behaving ε-greedily), enabling experience replay of past transitions",
      "It removed bootstrapping",
      "It required a model",
    ],
    answer: 1,
    explain: "DQN is off-policy Q-learning, which is what makes experience replay valid — old transitions from earlier policies can still be used to learn the greedy value function. Off-policy learning enabled the replay buffer.",
  },
  {
    q: "The applications chapter demonstrates that RL is useful for...",
    options: [
      "only toy problems",
      "a wide range of real and challenging problems (games, control, systems, recommendation), especially when combined with function approximation and search",
      "only classical conditioning",
      "supervised classification",
    ],
    answer: 1,
    explain: "Chapter 16 surveys diverse, hard applications, showing RL's practical power when scaled with deep function approximation, self-play/simulation, and planning — from board games to control and systems.",
  },
  {
    q: "Why is Go especially hard, motivating AlphaGo's approach?",
    options: [
      "It has few positions",
      "Its enormous branching factor and state space make brute-force search and simple heuristics infeasible, requiring learned policy/value networks plus guided search",
      "It is deterministic with random dice",
      "It has no reward",
    ],
    answer: 1,
    explain: "Go's astronomical number of positions defeats brute-force search and handcrafted evaluation. AlphaGo combined learned networks (policy/value) with MCTS to search intelligently — the key to conquering Go.",
  },
  {
    q: "The self-play policy-improvement loop in AlphaZero can be viewed as an instance of...",
    options: [
      "supervised learning",
      "generalized policy iteration: search (MCTS) improves the policy, and the improved policy trains the networks, repeatedly",
      "importance sampling",
      "bandit learning",
    ],
    answer: 1,
    explain: "AlphaZero is essentially GPI at scale: MCTS acts as policy improvement over the network's policy, and the resulting stronger play trains the networks (evaluation) — iterated via self-play toward stronger play.",
  },
  {
    q: "Which practical technique did DQN NOT rely on?",
    options: [
      "Experience replay",
      "A target network",
      "A perfect model of the game dynamics",
      "A convolutional network on pixels",
    ],
    answer: 2,
    explain: "DQN is model-free — it did not use a perfect model of the game. Its innovations were experience replay, a target network, and a CNN over raw pixels, all serving model-free off-policy Q-learning.",
  },
  {
    q: "A general takeaway about function approximation from these cases is that...",
    options: [
      "it is unnecessary",
      "deep neural networks let RL scale to high-dimensional inputs and huge state spaces by learning representations",
      "only linear methods work",
      "it prevents learning",
    ],
    answer: 1,
    explain: "The case studies show deep function approximation is what enabled RL to handle raw pixels and giant state spaces (Atari, Go), by learning useful internal representations — central to modern deep RL.",
  },
  {
    q: "The applications collectively suggest that a promising path to general agents is...",
    options: [
      "more hand-coded rules",
      "combining learning (from experience) and search (planning), scaled with computation",
      "avoiding neural networks",
      "removing rewards",
    ],
    answer: 1,
    explain: "The successes rest on general learning-plus-search methods that improve with more computation and data — pointing toward scalable general agents, a direction the frontiers chapter develops further.",
  },
  {
    q: "In TD-Gammon, the neural network's output represented...",
    options: [
      "the next dice roll",
      "an estimate of the value (expected outcome / win probability) of a board position",
      "the reward function",
      "the opponent's policy",
    ],
    answer: 1,
    explain: "The network estimated the value of positions (probability of winning), trained by TD(λ) from self-play. Move selection used a shallow search over this learned position evaluator.",
  },
  {
    q: "Which is TRUE about the generality of the AlphaZero approach?",
    options: [
      "It only works for Go",
      "The same algorithm mastered Go, chess, and shogi given only the rules, showing broad applicability of self-play + search + deep networks",
      "It requires human expert data",
      "It abandons value functions",
    ],
    answer: 1,
    explain: "AlphaZero used one general algorithm across Go, chess, and shogi with only the game rules — no human data or game-specific features — highlighting the generality of the learning-plus-search recipe.",
  },
  {
    q: "Why is Atari a good RL benchmark suite?",
    options: [
      "All games are identical",
      "It offers many diverse games with a common interface (pixels in, score as reward), testing general learning without per-game engineering",
      "The games have no rewards",
      "It requires a model",
    ],
    answer: 1,
    explain: "The Atari suite provides varied tasks through a uniform interface (screen pixels, joystick actions, game score), making it ideal for testing whether one general agent can learn many tasks — which DQN did.",
  },
  {
    q: "The case studies illustrate that off-policy learning (as in DQN) is valuable because it enables...",
    options: [
      "on-policy-only updates",
      "reuse of stored past experience (replay) and learning about the greedy policy while exploring",
      "removing the value function",
      "avoiding neural networks",
    ],
    answer: 1,
    explain: "Off-policy Q-learning lets DQN learn the greedy value function from a replay buffer of past (behavior-policy) transitions — data efficiency and stability that on-policy methods can't directly match.",
  },
  {
    q: "A key engineering insight from DQN is that stabilizing deep RL often requires...",
    options: [
      "larger learning rates only",
      "decorrelating updates and slowing target movement (replay + target network)",
      "removing exploration",
      "a perfect model",
    ],
    answer: 1,
    explain: "DQN's stability came from breaking update correlations (experience replay) and slowing the bootstrap target (target network) — practical antidotes to the deadly-triad instability of deep off-policy bootstrapping.",
  },
  {
    q: "Which best summarizes Chapter 16?",
    options: [
      "RL only works in theory",
      "Landmark applications (TD-Gammon, Samuel's checkers, Watson, DQN/Atari, AlphaGo/Zero, systems and control) show RL solving hard real problems when scaled with function approximation, self-play, and search",
      "RL is limited to bandits",
      "Applications avoid value functions",
    ],
    answer: 1,
    explain: "Chapter 16 surveys RL's most striking successes, extracting the common recipe: general RL algorithms scaled by (often deep) function approximation, abundant self-play/simulation, and planning/search.",
  },
  {
    q: "The novel backgammon strategies discovered by TD-Gammon demonstrate that RL can...",
    options: [
      "only imitate humans",
      "discover strategies beyond existing human knowledge, not merely replicate expert play",
      "never reach expert level",
      "avoid learning",
    ],
    answer: 1,
    explain: "TD-Gammon's self-play produced move preferences that surprised and influenced human experts — evidence that RL can invent genuinely new, superior strategies rather than just copying human play.",
  },
  {
    q: "Which is a correct statement about MCTS in AlphaGo?",
    options: [
      "It searches the full game tree exhaustively",
      "It selectively simulates promising lines guided by the policy/value networks, focusing computation where it matters",
      "It ignores the neural networks",
      "It requires no simulation",
    ],
    answer: 1,
    explain: "MCTS in AlphaGo uses the networks to guide selective simulations toward promising moves and evaluate positions, making search tractable in Go's vast tree — a synergy of learning and planning.",
  },
  {
    q: "The applications suggest RL is most transformative when the problem is...",
    options: [
      "a static classification task",
      "a sequential decision problem with delayed reward, where long-term consequences matter",
      "a one-step prediction",
      "purely supervised",
    ],
    answer: 1,
    explain: "RL's strength is sequential decision-making under delayed reward — games, control, recommendation over time. That's where optimizing cumulative reward (not immediate feedback) yields the biggest gains.",
  },
  {
    q: "What common role does self-play serve in TD-Gammon and AlphaZero?",
    options: [
      "It provides labeled data from humans",
      "It generates a curriculum of ever-stronger opponents and unlimited experience, enabling continual improvement",
      "It removes the need for value functions",
      "It fixes the policy",
    ],
    answer: 1,
    explain: "Self-play creates an automatically-scaling curriculum: as the agent improves, so does its opponent (itself), producing endless, increasingly challenging experience that drives continual improvement.",
  },
  {
    q: "A cautionary point implicit in the applications is that scaling RL requires attention to...",
    options: [
      "nothing special",
      "stability, exploration, and computational cost — deep RL can be sample-hungry and unstable without careful design",
      "removing rewards",
      "avoiding simulation",
    ],
    answer: 1,
    explain: "Despite the successes, deep RL can be unstable and data-hungry; the systems succeeded by carefully addressing stability (replay/target nets), exploration, and by leveraging large amounts of (often simulated) experience.",
  },
  {
    q: "Overall, the applications chapter argues that RL, combined with modern function approximation and search, is...",
    options: [
      "a narrow curiosity",
      "a broadly powerful approach capable of superhuman performance on some of the hardest decision problems",
      "only useful for psychology",
      "unable to scale",
    ],
    answer: 1,
    explain: "Chapter 16 concludes that RL — scaled with deep function approximation, self-play/simulation, and search — is a broadly powerful methodology, achieving superhuman results on very hard sequential decision problems.",
  }
);
