// ============================================================================
//  data-02-b.js — Chapter 02 (Multi-armed Bandits) expansion pool
// ============================================================================
QUESTIONS["02"].push(
  {
    q: "In the k-armed bandit problem, why is there no need to learn a state-transition model?",
    options: [
      "Because rewards are deterministic",
      "Because the problem is nonassociative/single-situation — the same k actions are faced repeatedly with no state changes",
      "Because there are no rewards",
      "Because the actions are labeled",
    ],
    answer: 1,
    explain: "The basic bandit is nonassociative: there is a single state, so actions do not change the situation. This isolates the exploration–exploitation problem without the complications of sequential state transitions.",
  },
  {
    q: "If you knew q*(a) for all actions, solving the bandit problem would be...",
    options: [
      "Still very hard",
      "Trivial — always select the action with the highest q*(a)",
      "Impossible",
      "Dependent on the step size",
    ],
    answer: 1,
    explain: "With the true action values known, you would simply always pick the highest-valued action. The challenge is that q*(a) is unknown and must be estimated from noisy rewards, forcing exploration.",
  },
  {
    q: "A 'greedy' action is defined as...",
    options: [
      "A randomly chosen action",
      "An action whose current estimated value is the greatest",
      "The least-tried action",
      "The action with the highest uncertainty",
    ],
    answer: 1,
    explain: "The greedy action is argmax_a Q_t(a), the one with the largest current value estimate. Choosing it is exploiting; choosing a non-greedy action is exploring.",
  },
  {
    q: "As the number of times an action is selected → ∞, the sample-average estimate Q_t(a) converges to q*(a) by...",
    options: [
      "The central limit theorem",
      "The law of large numbers",
      "Bayes' rule",
      "Gradient descent",
    ],
    answer: 1,
    explain: "By the law of large numbers, the average of the rewards observed for an action converges to its expected value q*(a) as the sample size grows without bound.",
  },
  {
    q: "The incremental sample-average update Q_{n+1} = Q_n + (1/n)[R_n − Q_n] is derived to avoid...",
    options: [
      "Using the reward",
      "Storing and summing all past rewards (memory/computation growing with n)",
      "Exploration",
      "The step-size parameter",
    ],
    answer: 1,
    explain: "The incremental form updates the running average with O(1) memory and computation, instead of storing every reward and recomputing the mean each step.",
  },
  {
    q: "In the update NewEstimate ← OldEstimate + StepSize[Target − OldEstimate], the bracketed quantity [Target − OldEstimate] is a(n)...",
    options: ["Reward", "Error in the estimate", "Discount factor", "Probability"],
    answer: 1,
    explain: "The bracket is the error between the target and the current estimate; the update reduces this error by a step-size fraction. This error-correction form recurs throughout the book.",
  },
  {
    q: "For the sample-average method, the effective step size on the n-th update is...",
    options: ["A constant α", "1/n", "n", "0"],
    answer: 1,
    explain: "Sample averaging uses a decreasing step size of 1/n, giving all rewards equal weight. This satisfies the stochastic-approximation conditions for convergence in the stationary case.",
  },
  {
    q: "With a CONSTANT step size α, the estimate is a weighted average in which the weight given to a reward from k steps ago is...",
    options: [
      "Equal to all others",
      "α(1−α)^k — decaying exponentially into the past (recency weighting)",
      "1/k",
      "Zero",
    ],
    answer: 1,
    explain: "A constant α yields an exponential recency-weighted average: older rewards get weight α(1−α)^k, which decays geometrically. This tracks nonstationary values but does not converge to a fixed estimate.",
  },
  {
    q: "The Robbins–Monro conditions for convergence of a step-size sequence require Σαₙ = ∞ and...",
    options: [
      "Σαₙ² = ∞",
      "Σαₙ² < ∞",
      "αₙ constant",
      "αₙ increasing",
    ],
    answer: 1,
    explain: "Σαₙ = ∞ ensures the steps are large enough to overcome initial conditions/noise; Σαₙ² < ∞ ensures they shrink enough to converge. 1/n satisfies both; a constant α satisfies the first but not the second (so it keeps adapting).",
  },
  {
    q: "In the 10-armed testbed, which method generally achieves the highest long-run average reward among these?",
    options: [
      "Pure greedy (ε=0)",
      "ε-greedy with a small ε (e.g., 0.01 or 0.1)",
      "Always exploring at random",
      "A method that never updates estimates",
    ],
    answer: 1,
    explain: "On the 10-armed testbed, ε-greedy methods outperform pure greedy because they continue to explore and find better actions. Small ε eventually does best (more exploitation once good actions are found); ε=0.1 improves faster early on.",
  },
  {
    q: "Compared to ε=0.1, using ε=0.01 in the testbed tends to...",
    options: [
      "Learn faster early but plateau lower",
      "Learn more slowly early but reach a higher final performance",
      "Never find the best action",
      "Behave identically",
    ],
    answer: 1,
    explain: "ε=0.01 explores less, so it improves more slowly at first but ultimately selects the optimal action a larger fraction of the time (higher asymptotic reward) than ε=0.1.",
  },
  {
    q: "Why do optimistic initial values encourage exploration only TEMPORARILY?",
    options: [
      "Because the step size grows",
      "Because once actions have been tried enough, estimates settle near true values and the optimism (drive to explore) fades",
      "Because ε decays",
      "Because the rewards stop",
    ],
    answer: 1,
    explain: "Optimism drives early exploration, but as estimates are corrected downward toward true values the exploratory pressure disappears. Hence it is a transient technique, poorly suited to nonstationary problems that need ongoing exploration.",
  },
  {
    q: "Optimistic initial values are best suited to which kind of problem?",
    options: ["Nonstationary problems", "Stationary problems", "Problems with no reward", "Associative problems only"],
    answer: 1,
    explain: "Optimistic initialization works well for stationary problems where a burst of early exploration suffices. In nonstationary settings it fails, because it does not promote the continual exploration that a changing environment requires.",
  },
  {
    q: "In the UCB formula A_t = argmax_a [Q_t(a) + c·sqrt(ln t / N_t(a))], what happens to an action that has never been selected (N_t(a)=0)?",
    options: [
      "It is ignored",
      "It is treated as a maximizing action (given effectively infinite priority) so it gets selected",
      "It causes a division error that stops learning",
      "Its value is set to zero",
    ],
    answer: 1,
    explain: "Actions with N_t(a)=0 are considered maximizing actions, ensuring every action is tried at least once before the uncertainty bonus starts shrinking with more selections.",
  },
  {
    q: "In UCB, the constant c controls...",
    options: [
      "The learning rate",
      "The degree of exploration (larger c → more weight on uncertainty)",
      "The discount factor",
      "The number of arms",
    ],
    answer: 1,
    explain: "c scales the confidence/uncertainty bonus. Larger c increases exploration by favoring less-tried actions more strongly; smaller c makes the method more exploitative.",
  },
  {
    q: "The uncertainty term sqrt(ln t / N_t(a)) behaves how as an action a is selected more often (N_t(a) grows)?",
    options: [
      "It grows",
      "It shrinks, reducing that action's exploration bonus",
      "It stays constant",
      "It becomes negative",
    ],
    answer: 1,
    explain: "As N_t(a) increases, the bonus shrinks (we are more certain about a), so UCB shifts attention to other, less-certain actions. The ln t in the numerator slowly raises all bonuses over time.",
  },
  {
    q: "A practical difficulty of UCB (versus ε-greedy) noted in the book is that it is harder to extend to...",
    options: [
      "Small problems",
      "Nonstationary problems and problems with large state spaces / function approximation",
      "Deterministic problems",
      "Problems with two arms",
    ],
    answer: 1,
    explain: "UCB is elegant for stationary bandits but is more difficult to extend to nonstationary settings and to the full RL problem with function approximation and large state spaces, where ε-greedy generalizes more easily.",
  },
  {
    q: "Gradient bandit algorithms use a soft-max (Gibbs/Boltzmann) distribution defined over...",
    options: [
      "Action-value estimates Q(a)",
      "Numerical action preferences H(a)",
      "Rewards directly",
      "Visit counts N(a)",
    ],
    answer: 1,
    explain: "Gradient bandits learn preferences H_t(a) (which have no reward-value interpretation) and choose actions with probability proportional to e^{H(a)} via soft-max. Only relative preferences matter.",
  },
  {
    q: "In the gradient bandit update, the reward baseline (typically the average reward R̄_t) serves to...",
    options: [
      "Increase variance",
      "Reduce the variance of the update without biasing it, comparing the current reward against a reference",
      "Replace the reward",
      "Set the step size",
    ],
    answer: 1,
    explain: "Subtracting a baseline (the running average reward) compares R_t to what is typical. It does not change the expected update (unbiased) but reduces variance, greatly improving learning speed and robustness.",
  },
  {
    q: "The gradient bandit algorithm is a form of...",
    options: [
      "Dynamic programming",
      "Stochastic gradient ascent on expected reward",
      "Supervised learning",
      "Exhaustive search",
    ],
    answer: 1,
    explain: "Its preference updates are a stochastic approximation to gradient ascent on E[R_t]: preferences move in the direction that increases expected reward, which is why it is called a gradient method.",
  },
  {
    q: "Associative search (a.k.a. contextual bandits) differs from the basic bandit because...",
    options: [
      "There is only one situation",
      "Different situations (states) are presented, and the agent must learn a policy mapping situations to actions, but actions still don't affect the next situation",
      "Actions affect the next state fully",
      "There is no reward",
    ],
    answer: 1,
    explain: "Contextual/associative bandits add different situations signaled to the agent, so it learns a policy (situation → action). It is intermediate between the pure bandit and the full RL problem, since actions still do not influence which situation comes next.",
  },
  {
    q: "What separates the full reinforcement learning problem from a contextual bandit?",
    options: [
      "The presence of rewards",
      "In full RL, actions influence the next state (and thus future situations and rewards), not just the immediate reward",
      "The presence of multiple actions",
      "The use of a policy",
    ],
    answer: 1,
    explain: "In the full RL problem actions affect the next situation as well as the reward, introducing delayed consequences. Contextual bandits keep situations independent of the agent's actions.",
  },
  {
    q: "The 'reward distribution' for each arm in the standard 10-armed testbed is...",
    options: [
      "Deterministic",
      "Gaussian with mean q*(a) and variance 1",
      "Uniform on [0,1]",
      "Always zero",
    ],
    answer: 1,
    explain: "In the testbed, selecting action a yields a reward drawn from a normal distribution with mean q*(a) and unit variance; the q*(a) themselves are drawn from a standard normal at the start of each run.",
  },
  {
    q: "Why does the greedy method (ε=0) get stuck at about 'optimal action ~1/3 of the time' in the testbed?",
    options: [
      "Because there are three arms",
      "Because it commits to whichever action looked best from limited early samples and never explores to correct mistakes",
      "Because rewards are negative",
      "Because the step size is too large",
    ],
    answer: 1,
    explain: "The greedy method locks onto an early-favored action; with noisy initial estimates this is frequently suboptimal, and lacking exploration it never discovers the truly best arm on many runs.",
  },
  {
    q: "For a NONSTATIONARY bandit, which action-selection/estimation combination is most appropriate?",
    options: [
      "Sample averages with greedy selection",
      "A constant step size (to track) plus continual exploration (e.g., ε-greedy)",
      "Optimistic initial values with ε=0",
      "UCB with c=0",
    ],
    answer: 1,
    explain: "Nonstationary problems need a constant step size (to keep tracking the drifting values) and ongoing exploration (ε>0), since one-shot exploration tricks and 1/n averaging cannot follow changing values.",
  },
  {
    q: "The probability that ε-greedy selects the greedy action on a given step is...",
    options: [
      "ε",
      "1 − ε + ε/|A| (greedy directly, plus its share of the random pick)",
      "1",
      "0",
    ],
    answer: 1,
    explain: "With probability 1−ε it picks greedily, and with probability ε it picks uniformly at random (which includes the greedy action with probability 1/|A|). So total = 1 − ε + ε/|A|.",
  },
  {
    q: "Which statement about the gradient-bandit preferences H(a) is correct?",
    options: [
      "Their absolute values estimate reward",
      "Only differences between preferences matter; adding a constant to all H(a) leaves the policy unchanged",
      "They must be nonnegative",
      "They equal the action values",
    ],
    answer: 1,
    explain: "Soft-max depends only on relative preferences: shifting all H(a) by a constant does not change the action probabilities. Preferences are not estimates of reward.",
  },
  {
    q: "An advantage of ε-greedy over pure greedy specifically as reward noise (variance) increases is that ε-greedy...",
    options: [
      "Becomes worse",
      "Benefits more, because noisier rewards make early estimates less reliable, so exploration pays off more",
      "Behaves identically",
      "Stops exploring",
    ],
    answer: 1,
    explain: "With higher reward variance, more sampling is needed to identify the best action, so exploration (ε-greedy) helps more relative to greedy. With zero noise, greedy could do fine after one sample per action.",
  },
  {
    q: "Which is a correct characterization of 'regret' in bandit problems (as commonly used)?",
    options: [
      "The total reward collected",
      "The cumulative difference between the reward of the optimal action and the rewards actually obtained",
      "The number of arms",
      "The step-size sequence",
    ],
    answer: 1,
    explain: "Regret measures how much reward was lost by not always playing the optimal arm — the summed gap between optimal and actual reward. Good bandit algorithms keep regret growing slowly (e.g., logarithmically).",
  },
  {
    q: "Why can initial action-value estimates be considered a form of prior knowledge or bias?",
    options: [
      "They are always zero",
      "They influence early behavior; sample-average methods eventually wash them out, but constant-α methods retain a permanent (decaying) bias from them",
      "They equal the true values",
      "They are irrelevant",
    ],
    answer: 1,
    explain: "Initial estimates bias early estimates. Sample averaging removes this bias once every action is chosen at least once; with a constant step size the bias is permanent though it decreases over time.",
  },
  {
    q: "In UCB, the ln t term (natural log of the time step) ensures that...",
    options: [
      "Exploration stops entirely",
      "All actions are revisited eventually, since the bonus of any fixed action slowly grows with t if it is not selected",
      "The step size decreases",
      "Rewards increase",
    ],
    answer: 1,
    explain: "The ln t numerator slowly increases the exploration bonus over time for actions not being selected, guaranteeing they are eventually re-examined — though increases become smaller as t grows.",
  },
  {
    q: "Which best explains why the gradient bandit method can work even though preferences are not value estimates?",
    options: [
      "It secretly estimates values",
      "It directly performs (stochastic) gradient ascent on expected reward, so preferences drift toward better actions regardless of a value interpretation",
      "It uses a model",
      "It ignores rewards",
    ],
    answer: 1,
    explain: "The method needs no value interpretation: it adjusts preferences in the direction of increasing expected reward. Actions yielding above-baseline reward have their preference (and probability) increased.",
  },
  {
    q: "Which parameter setting makes ε-greedy behave identically to pure greedy?",
    options: ["ε = 1", "ε = 0", "ε = 0.5", "ε = 0.1"],
    answer: 1,
    explain: "ε = 0 means never explore at random — always take the greedy action — which is exactly pure greedy behavior.",
  },
  {
    q: "A 'nonstationary' bandit problem is one in which...",
    options: [
      "The number of arms changes each step",
      "The true action values q*(a) change over time",
      "There is no reward variance",
      "The policy is fixed",
    ],
    answer: 1,
    explain: "Nonstationarity means the underlying reward distributions (true values q*(a)) drift over time, so the agent must keep re-estimating and re-exploring — the more common situation in real RL.",
  },
  {
    q: "The action-value estimate Q_t(a) is best interpreted as...",
    options: [
      "The exact q*(a)",
      "An estimate of q*(a) formed from observed rewards",
      "The reward on the last step",
      "The number of selections of a",
    ],
    answer: 1,
    explain: "Q_t(a) is the agent's estimate of the true value q*(a). Different methods (sample average, constant-α) compute this estimate differently, and action selection is based on these estimates.",
  },
  {
    q: "Why is the multi-armed bandit a useful pedagogical starting point for the book?",
    options: [
      "It has no exploration",
      "It isolates the exploration–exploitation trade-off in the simplest (single-state) setting before adding sequential/state complexity",
      "It requires a full model",
      "It is unsolvable",
    ],
    answer: 1,
    explain: "By stripping away state transitions, the bandit lets the book study exploration vs. exploitation and value estimation cleanly, building intuition and tools reused throughout the full RL problem.",
  },
  {
    q: "If two actions have equal estimated value under ε-greedy, ties for the greedy action are typically...",
    options: [
      "Always broken toward the first action",
      "Broken randomly among the tied maximizing actions",
      "Broken toward the least-tried",
      "Not allowed",
    ],
    answer: 1,
    explain: "When several actions share the maximum estimate, the greedy choice is usually made by breaking ties randomly among them, avoiding a systematic bias toward any particular tied action.",
  },
  {
    q: "Which statement comparing UCB and gradient-bandit methods is accurate?",
    options: [
      "Both estimate action values with sample averages",
      "UCB selects using value estimates plus an uncertainty bonus, while gradient bandits learn preferences and use soft-max — different mechanisms for exploration",
      "They are identical",
      "Neither explores",
    ],
    answer: 1,
    explain: "UCB is a value-based method with a deterministic uncertainty-driven exploration bonus; gradient bandits are preference-based with stochastic soft-max action selection. Both address exploration but via distinct principles.",
  },
  {
    q: "A parameter study (as in the book's summary figure) plots average reward against a method's parameter to reveal...",
    options: [
      "Only the best single setting",
      "How each algorithm's performance varies with its parameter and how the best settings of different algorithms compare",
      "The number of arms",
      "The reward variance only",
    ],
    answer: 1,
    explain: "Parameter studies show each method's performance across a range of its key parameter (ε, α, c, Q₀), letting you compare algorithms at their best settings and judge robustness to parameter choice.",
  },
  {
    q: "Overall, Chapter 2 concludes that balancing exploration and exploitation...",
    options: [
      "Is trivial and fully solved",
      "Remains a genuinely difficult, unresolved problem, with several practical heuristics (ε-greedy, UCB, optimistic init, gradient) each having strengths",
      "Requires a model of the environment",
      "Is unnecessary in practice",
    ],
    answer: 1,
    explain: "The chapter presents several practical exploration methods but emphasizes that optimally balancing exploration and exploitation is still an open challenge; the heuristics are effective but not a complete solution.",
  }
);
