// ============================================================================
//  data-11-b.js — Chapter 11 (Off-policy Methods with Approximation) pool
// ============================================================================
QUESTIONS["11"].push(
  {
    q: "The three elements of the 'deadly triad' are function approximation, bootstrapping, and...",
    options: [
      "discounting",
      "off-policy training",
      "exploration",
      "sampling",
    ],
    answer: 1,
    explain: "Instability/divergence risk arises when function approximation, bootstrapping, and off-policy training are combined. Any two together are generally safe; all three can cause parameters to diverge.",
  },
  {
    q: "If you REMOVE bootstrapping (use Monte Carlo returns) while keeping off-policy training and approximation, learning...",
    options: [
      "still diverges",
      "is generally stable (no deadly triad without bootstrapping), though possibly high variance",
      "cannot be done",
      "requires a model",
    ],
    answer: 1,
    explain: "The triad needs all three. Dropping bootstrapping (using full returns) removes the instability, at the cost of Monte Carlo's higher variance and episodic-only applicability. Similarly, staying on-policy also avoids divergence.",
  },
  {
    q: "Baird's counterexample demonstrates that...",
    options: [
      "on-policy TD diverges",
      "off-policy linear semi-gradient TD(0) can make the weights diverge to infinity, even though a good solution exists",
      "Monte Carlo diverges",
      "tabular TD diverges",
    ],
    answer: 1,
    explain: "Baird's 7-state counterexample shows off-policy semi-gradient TD with linear features diverging (weights → ∞) despite the existence of a perfect representation — the canonical demonstration of the deadly triad.",
  },
  {
    q: "In Baird's counterexample, the divergence occurs because...",
    options: [
      "the reward is too large",
      "off-policy updates (weighted by a distribution differing from on-policy) combined with bootstrapping and shared features push weights apart without correction",
      "the step size is negative",
      "there is no discount",
    ],
    answer: 1,
    explain: "The mismatch between the update distribution (behavior) and the on-policy distribution, together with bootstrapping through shared linear features, creates an expected update whose dynamics are unstable — weights grow without bound.",
  },
  {
    q: "The Mean Squared Bellman Error (BE) is generally NOT a good learning objective because it...",
    options: [
      "is always zero",
      "is not learnable from data — different MDPs producing the same data distribution can have different BE",
      "ignores the reward",
      "requires bootstrapping",
    ],
    answer: 1,
    explain: "The book proves the Bellman error is not learnable: two MDPs indistinguishable from observed data can have different BE, so no algorithm using only data can minimize it. This motivates the projected Bellman error instead.",
  },
  {
    q: "The Mean Squared Projected Bellman Error (PBE) differs from the BE by...",
    options: [
      "ignoring the Bellman operator",
      "projecting the Bellman-updated value back into the representable (approximation) subspace before measuring error",
      "removing the reward",
      "using Monte Carlo returns",
    ],
    answer: 1,
    explain: "PBE applies the projection operator so it measures error within the space of representable value functions. Its minimizer is the TD fixed point, and unlike BE it is learnable from data.",
  },
  {
    q: "The TD fixed point (found by semi-gradient TD) is the value function where the PBE equals...",
    options: [
      "1",
      "0 (the projected Bellman update leaves v̂ unchanged)",
      "the reward",
      "infinity",
    ],
    answer: 1,
    explain: "At the TD fixed point, projecting the Bellman update of v̂ gives back v̂, so the projected Bellman error is zero. This is exactly where on-policy semi-gradient TD converges.",
  },
  {
    q: "Gradient-TD methods (GTD2, TDC) are stable off-policy because they...",
    options: [
      "avoid bootstrapping",
      "perform true stochastic gradient descent on the PBE, guaranteeing convergence even under the deadly triad",
      "use a model",
      "are on-policy",
    ],
    answer: 1,
    explain: "Gradient-TD methods genuinely descend the projected Bellman error via SGD, so they converge with linear function approximation off-policy. The cost is a second weight vector and roughly double computation.",
  },
  {
    q: "Gradient-TD methods maintain a second set of weights, v, that estimates...",
    options: [
      "the reward",
      "a quantity (related to the expected TD error times features) needed to form the true PBE gradient",
      "the policy",
      "the discount",
    ],
    answer: 1,
    explain: "The auxiliary weights approximate E[δx] (a product needed to compute the PBE gradient without a double-sampling problem). This extra estimate is what makes gradient-TD a true, stable gradient method.",
  },
  {
    q: "The 'double sampling' problem in naively minimizing the Bellman error refers to needing...",
    options: [
      "two rewards",
      "two independent samples of the next state to form an unbiased product of expectations, which a single transition can't provide",
      "two policies",
      "two discount factors",
    ],
    answer: 1,
    explain: "The BE gradient contains a product of two expectations over the next state; an unbiased estimate would need two independent next-state samples from the same state. Gradient-TD's auxiliary weights sidestep this.",
  },
  {
    q: "Emphatic-TD methods achieve off-policy stability by...",
    options: [
      "removing the target policy",
      "reweighting updates with a state-dependent 'emphasis' that restores a distribution under which semi-gradient bootstrapping is stable",
      "using Monte Carlo returns",
      "ignoring importance ratios",
    ],
    answer: 1,
    explain: "Emphatic-TD scales each update by an emphasis M_t (built from interest and past emphasis, incorporating importance ratios), effectively changing the state weighting so that off-policy linear semi-gradient TD becomes convergent.",
  },
  {
    q: "Emphatic-TD and gradient-TD are two DIFFERENT remedies for the deadly triad. Emphatic-TD...",
    options: [
      "uses a second weight vector like gradient-TD",
      "keeps the semi-gradient TD update form but reweights it via emphasis, rather than switching to a true gradient objective",
      "requires a model",
      "is on-policy only",
    ],
    answer: 1,
    explain: "Gradient-TD changes the objective (true SGD on PBE, extra weights); emphatic-TD keeps the semi-gradient update but multiplies it by an emphasis factor. Both restore convergence under the deadly triad by different means.",
  },
  {
    q: "The per-step importance sampling ratio ρ_t = π(A_t|S_t)/b(A_t|S_t) appears in off-policy value-approximation updates to...",
    options: [
      "increase the reward",
      "correct the update for the fact that actions were drawn from b rather than the target policy π",
      "set the step size",
      "compute the projection",
    ],
    answer: 1,
    explain: "Multiplying the semi-gradient TD update by ρ_t reweights it to account for the behavior/target policy mismatch. Off-policy TD(0) with function approximation uses this ratio (and, unfortunately, can still diverge — hence gradient/emphatic-TD).",
  },
  {
    q: "Which combination is SAFE (does NOT trigger the deadly triad)?",
    options: [
      "Off-policy + bootstrapping + linear approximation",
      "On-policy + bootstrapping + linear approximation",
      "Off-policy + bootstrapping + nonlinear approximation",
      "All combinations diverge",
    ],
    answer: 1,
    explain: "On-policy linear semi-gradient TD (bootstrapping + approximation, but ON-policy) is stable. Divergence requires all three triad elements together; keeping training on-policy removes the risk.",
  },
  {
    q: "The Bellman error at a state measures...",
    options: [
      "the reward received",
      "how far v̂ is from satisfying the Bellman equation there (the expected one-step backup minus v̂)",
      "the policy gradient",
      "the number of visits",
    ],
    answer: 1,
    explain: "The Bellman error δ̄(s) = (Bellman update of v̂ at s) − v̂(s) quantifies the residual of the Bellman equation under the current approximation. Its squared, μ-weighted sum is the BE objective.",
  },
  {
    q: "Which objective is minimized to zero exactly by the true value function v_π (in the tabular/representable case)?",
    options: [
      "Only the TDE",
      "The Bellman Error (BE) — v_π makes the Bellman residual zero everywhere",
      "None",
      "The reward",
    ],
    answer: 1,
    explain: "v_π satisfies the Bellman equation exactly, so its Bellman error is zero. The problem is that BE is not learnable from data with function approximation, unlike the PBE.",
  },
  {
    q: "The Mean Squared TD Error (TDE) is minimized by a value function that...",
    options: [
      "equals v_π",
      "is NOT generally v_π — naively minimizing the expected squared TD error gives a biased/undesirable solution",
      "maximizes reward",
      "is the TD fixed point",
    ],
    answer: 1,
    explain: "Minimizing E[δ²] (the TDE) does not yield v_π in general; it can produce a value function that 'splits the difference' undesirably. This is why the PBE (whose minimizer is the TD fixed point) is preferred as an objective.",
  },
  {
    q: "Off-policy learning with approximation is valuable enough to solve (despite the triad) because it enables...",
    options: [
      "smaller state spaces",
      "learning about many target policies (or the greedy/optimal policy) from a single stream of exploratory or logged experience",
      "removing the reward",
      "avoiding value functions",
    ],
    answer: 1,
    explain: "Off-policy learning lets one behavior stream train many predictions/policies (e.g., learning q* while exploring, or a Horde of predictions). Its power motivates finding stable algorithms like gradient-TD and emphatic-TD.",
  },
  {
    q: "In Baird's counterexample, which method(s) converge correctly?",
    options: [
      "Semi-gradient off-policy TD(0)",
      "Gradient-TD (e.g., TDC) and emphatic-TD, which are designed to be stable",
      "None",
      "Only Monte Carlo with a model",
    ],
    answer: 1,
    explain: "The naive semi-gradient off-policy TD diverges on Baird's example, whereas gradient-TD (TDC/GTD2) and emphatic-TD converge, demonstrating that these methods cure the instability.",
  },
  {
    q: "Why is nonlinear function approximation (e.g., deep networks) particularly prone to instability off-policy?",
    options: [
      "It has no parameters",
      "It compounds the deadly triad with nonconvexity and moving targets, so guarantees are even weaker (mitigated in practice by tricks like target networks and replay)",
      "It is tabular",
      "It cannot bootstrap",
    ],
    answer: 1,
    explain: "Deep off-policy bootstrapping stacks the triad on top of nonconvex optimization. Practical stability comes from heuristics — experience replay, target networks (as in DQN) — rather than the clean guarantees of linear gradient-TD.",
  },
  {
    q: "The projection operator Π (in PBE) projects with respect to which norm?",
    options: [
      "The uniform norm",
      "The μ-weighted (on-policy or specified distribution) norm",
      "The max norm",
      "The reward norm",
    ],
    answer: 1,
    explain: "Π projects onto the representable subspace using the state-weighted (μ) norm. The weighting matters: off-policy, the effective distribution differs from the on-policy one, which is central to the stability analysis.",
  },
  {
    q: "A concise statement of the chapter's central problem is:",
    options: [
      "How to explore efficiently",
      "How to do stable and efficient off-policy learning with function approximation and bootstrapping (i.e., tame the deadly triad)",
      "How to compute the reward",
      "How to build a model",
    ],
    answer: 1,
    explain: "Chapter 11 is about the challenge of off-policy learning with approximation and bootstrapping — the deadly triad — and the methods (gradient-TD, emphatic-TD) that make it convergent.",
  },
  {
    q: "Which is TRUE about the learnability of objectives from data?",
    options: [
      "BE is learnable; PBE is not",
      "PBE (and VE) are learnable from data, whereas the Bellman error (BE) is not in general",
      "Neither is learnable",
      "All objectives are equally learnable",
    ],
    answer: 1,
    explain: "The chapter shows BE is not learnable (data-indistinguishable MDPs differ in BE), while the projected Bellman error is learnable — a key reason the TD fixed point (PBE minimizer) is the practical target.",
  },
  {
    q: "Compared to semi-gradient TD, gradient-TD methods trade some ___ for guaranteed ___.",
    options: [
      "stability; speed",
      "simplicity/speed; convergence (stability) under the deadly triad",
      "reward; exploration",
      "features; states",
    ],
    answer: 1,
    explain: "Gradient-TD adds a second weight vector and computation (less simple/slightly slower per step) in exchange for provable convergence off-policy — a worthwhile trade when the deadly triad would otherwise cause divergence.",
  },
  {
    q: "In the value-function geometry view, v_π, the TD fixed point, and the representable subspace are related such that...",
    options: [
      "they always coincide",
      "the representable functions form a subspace; v_π usually lies outside it, and different objectives (VE, PBE, BE) pick different points in the subspace",
      "there is no subspace",
      "the reward defines the subspace",
    ],
    answer: 1,
    explain: "Geometrically, representable value functions form a subspace; the true v_π typically isn't in it. VE picks the closest point (projection of v_π), while PBE picks the TD fixed point — generally a different point.",
  },
  {
    q: "Which statement about emphasis M_t in emphatic-TD is correct?",
    options: [
      "It is constant",
      "It accumulates over time (from interest and prior emphasis, scaled by importance ratios), varying how strongly each state's update counts",
      "It equals the reward",
      "It removes bootstrapping",
    ],
    answer: 1,
    explain: "Emphasis M_t is a running quantity combining the state's interest with discounted, ratio-weighted past emphasis. It reweights updates so the resulting expected update is stable off-policy.",
  },
  {
    q: "The practical significance of Chapter 11 for deep RL is that...",
    options: [
      "it proves deep RL always converges",
      "it explains WHY off-policy deep RL can be unstable and motivates stabilizers; the linear theory (gradient/emphatic-TD) gives principled guarantees",
      "deep RL never bootstraps",
      "it forbids off-policy learning",
    ],
    answer: 1,
    explain: "Understanding the deadly triad clarifies deep RL instabilities and motivates practical fixes (target networks, replay). The chapter's linear gradient-/emphatic-TD provide the principled convergent counterparts.",
  },
  {
    q: "Semi-gradient off-policy TD(0) update includes ρ_t because the state distribution encountered under b...",
    options: [
      "equals the on-policy distribution",
      "differs from the target policy's, so ρ_t reweights toward the target policy's expectations (yet stability still isn't guaranteed)",
      "is uniform",
      "is irrelevant",
    ],
    answer: 1,
    explain: "ρ_t corrects the action distribution mismatch. However, even with ρ_t, semi-gradient off-policy TD can diverge (Baird), because reweighting actions doesn't fix the unstable expected-update dynamics — motivating gradient/emphatic-TD.",
  },
  {
    q: "Which is the safest recommendation when facing the deadly triad in a linear setting?",
    options: [
      "Use naive semi-gradient off-policy TD",
      "Use a convergent method: gradient-TD (TDC/GTD2) or emphatic-TD",
      "Increase the step size",
      "Remove exploration",
    ],
    answer: 1,
    explain: "For linear off-policy learning with bootstrapping, gradient-TD or emphatic-TD provide convergence guarantees, making them the principled choices where naive semi-gradient TD would risk divergence.",
  },
  {
    q: "The overall message of Chapter 11 is that off-policy learning with approximation...",
    options: [
      "is trivial",
      "is genuinely hard (the deadly triad) but solvable with methods that either do true gradient descent on the PBE or reweight updates via emphasis",
      "should never be attempted",
      "requires a full model",
    ],
    answer: 1,
    explain: "The chapter diagnoses the deadly triad and presents solutions — gradient-TD and emphatic-TD — that restore convergence for off-policy, bootstrapping, function-approximation learning.",
  },
  {
    q: "Which quantity does semi-gradient TD implicitly minimize, connecting Chapters 9–11?",
    options: [
      "The reward",
      "The projected Bellman error (its fixed point), not the value error directly",
      "The policy gradient",
      "The model error",
    ],
    answer: 1,
    explain: "Semi-gradient TD converges to the TD fixed point, the minimizer of the projected Bellman error. Recognizing this (Ch. 11) clarifies what Chapters 9–10's methods actually optimize and why off-policy versions need care.",
  },
  {
    q: "Why is on-policy learning inherently safer than off-policy for bootstrapping methods?",
    options: [
      "It uses more data",
      "The update distribution matches the distribution the value function is evaluated under, keeping the expected update contraction-like and stable",
      "It avoids rewards",
      "It uses a model",
    ],
    answer: 1,
    explain: "On-policy, updates follow the same distribution used to define value accuracy, which keeps the expected TD update well-behaved (contraction-like). Off-policy breaks this alignment, opening the door to divergence.",
  },
  {
    q: "A downside of gradient-TD methods in practice is that they...",
    options: [
      "cannot converge",
      "can learn more slowly than semi-gradient TD (extra weights/updates), even though they are guaranteed stable",
      "require a model",
      "ignore the reward",
    ],
    answer: 1,
    explain: "Guaranteed stability comes at a cost: gradient-TD often converges more slowly than (when it works) semi-gradient TD, and needs a second learning rate/weights — a trade-off between safety and speed.",
  },
  {
    q: "Which correctly characterizes the relationship between VE and PBE minimizers?",
    options: [
      "They are always identical",
      "They are generally DIFFERENT points in the representable subspace (best-approximation vs. TD fixed point)",
      "Neither can be computed",
      "PBE minimizer equals v_π",
    ],
    answer: 1,
    explain: "The VE minimizer is the projection of v_π (best mean-squared approximation); the PBE minimizer is the TD fixed point. These usually differ, and semi-gradient TD reaches the latter.",
  },
  {
    q: "Interest (in interest/emphasis) lets the designer specify...",
    options: [
      "the reward",
      "how much accuracy is desired at each state, shaping which states the algorithm emphasizes",
      "the discount",
      "the exploration rate",
    ],
    answer: 1,
    explain: "Interest encodes the user's care about each state's value accuracy. Emphatic methods propagate interest into emphasis, focusing learning (and enabling off-policy stability) accordingly.",
  },
  {
    q: "Which is TRUE about Monte Carlo methods and the deadly triad?",
    options: [
      "MC triggers the triad",
      "MC does not bootstrap, so off-policy MC with approximation avoids the triad's instability (though with high variance)",
      "MC requires a model",
      "MC is always unstable",
    ],
    answer: 1,
    explain: "Because Monte Carlo uses full returns (no bootstrapping), it removes one triad element, avoiding the divergence — at the cost of variance and needing complete episodes. This is a general escape route from the triad.",
  },
  {
    q: "The chapter's value-function geometry helps by...",
    options: [
      "removing features",
      "giving a visual/linear-algebraic picture of objectives (VE, BE, PBE) as distances/projections, clarifying what each method targets",
      "computing rewards",
      "selecting actions",
    ],
    answer: 1,
    explain: "By casting value functions as vectors and objectives as (projected) distances, the geometry view makes the relationships among VE, BE, PBE, and the TD fixed point intuitive and precise.",
  },
  {
    q: "A single sentence summary of the deadly triad's resolution is:",
    options: [
      "Always stay tabular",
      "Use true-gradient (gradient-TD) or emphasis-reweighted (emphatic-TD) methods, or avoid one triad component (go on-policy or drop bootstrapping)",
      "Increase the discount to 1",
      "Remove the reward",
    ],
    answer: 1,
    explain: "You can either fix the algorithm (gradient-TD/emphatic-TD to make off-policy bootstrapping-approximation converge) or sidestep the triad by removing a component (on-policy training, or Monte Carlo instead of bootstrapping).",
  },
  {
    q: "Why does the book invest a whole chapter in off-policy approximation?",
    options: [
      "It is a niche curiosity",
      "Off-policy learning with approximation and bootstrapping is both extremely useful and uniquely prone to divergence, so understanding and fixing it is central to scalable RL",
      "It replaces on-policy learning",
      "It removes the need for exploration",
    ],
    answer: 1,
    explain: "Off-policy + approximation + bootstrapping is powerful (learn optimal/many policies from arbitrary data) yet dangerous (the deadly triad). Making it stable is essential for scalable, general RL — hence a dedicated chapter.",
  }
);
