// ============================================================================
//  data-17-b.js — Chapter 17 (Frontiers) expansion pool
// ============================================================================
QUESTIONS["17"].push(
  {
    q: "General Value Functions (GVFs) extend ordinary value functions by allowing predictions of...",
    options: [
      "only the standard reward",
      "arbitrary signals (cumulants/pseudo-rewards) under arbitrary target policies and termination functions",
      "only terminal states",
      "the discount factor",
    ],
    answer: 1,
    explain: "GVFs generalize value functions to predict any 'cumulant' signal (not just reward), each under its own policy and termination. A large collection of GVFs can encode rich predictive knowledge of the world.",
  },
  {
    q: "A GVF is specified by which components?",
    options: [
      "Only a reward",
      "A target policy, a cumulant (signal to accumulate), and a termination/continuation function",
      "A model and a discount only",
      "A single state",
    ],
    answer: 1,
    explain: "Each GVF answers a predictive question defined by (1) the policy to follow, (2) the cumulant to accumulate, and (3) the termination function. This lets one framework express many different predictions.",
  },
  {
    q: "Temporal abstraction via 'options' means treating extended courses of action as...",
    options: [
      "single primitive actions only",
      "higher-level actions with their own internal policy, initiation set, and termination condition",
      "rewards",
      "value functions",
    ],
    answer: 1,
    explain: "An option is a temporally-extended, closed-loop behavior: an internal policy, an initiation set (where it can start), and a termination condition. Options enable planning and learning at multiple time scales (hierarchical RL).",
  },
  {
    q: "The three components that define an option are...",
    options: [
      "reward, state, action",
      "an initiation set, an internal policy, and a termination condition",
      "policy, value, model",
      "cumulant, discount, feature",
    ],
    answer: 1,
    explain: "An option ⟨I, π, β⟩ has an initiation set I (states where it can begin), a policy π (how it behaves), and a termination function β (probability of stopping per state) — the standard options framework.",
  },
  {
    q: "Hierarchical RL with options is valuable because it can...",
    options: [
      "only slow learning",
      "enable reasoning/planning over longer time scales and transfer reusable skills across tasks",
      "remove the reward",
      "eliminate exploration",
    ],
    answer: 1,
    explain: "Options let agents plan with temporally-extended actions (fewer decisions over long horizons) and reuse learned skills across tasks, improving exploration and transfer — key motivations for hierarchical RL.",
  },
  {
    q: "The chapter emphasizes that designing the REWARD signal is difficult because...",
    options: [
      "rewards must be sparse",
      "agents optimize exactly what is rewarded, so a mis-specified or naively shaped reward can produce unintended, 'gamed' behavior",
      "rewards must be negative",
      "reward design is automatic",
    ],
    answer: 1,
    explain: "Because RL agents relentlessly maximize the given reward, poorly designed rewards can be exploited, yielding behavior that scores well but misses the true intent — a central practical and safety challenge.",
  },
  {
    q: "'Reward shaping' refers to...",
    options: [
      "removing the reward",
      "adding extra reward terms to guide learning, which must be done carefully (e.g., potential-based) to avoid changing the optimal policy",
      "increasing the discount",
      "using a model",
    ],
    answer: 1,
    explain: "Shaping adds auxiliary rewards to speed learning. Potential-based shaping provably preserves the optimal policy; arbitrary shaping can distort it. Careful design is needed so shaping helps without introducing unintended optima.",
  },
  {
    q: "The Horde architecture learns many predictions in parallel by using...",
    options: [
      "a single on-policy value function",
      "many independent GVF learners ('demons'), each learning off-policy from one shared stream of experience",
      "a perfect world model",
      "supervised labels for every prediction",
    ],
    answer: 1,
    explain: "Horde runs many independent RL 'demons' in parallel, each learning a GVF off-policy from the same behavior stream. Off-policy learning is what allows one experience stream to train predictions about many different policies at once.",
  },
  {
    q: "Off-policy learning is essential to architectures like Horde because it allows...",
    options: [
      "learning only about the behavior policy",
      "learning about MANY different target policies simultaneously from a single behavior stream",
      "removing the reward",
      "avoiding function approximation",
    ],
    answer: 1,
    explain: "Since each GVF has its own target policy, off-policy learning lets all of them be learned in parallel from the same stream of experience generated by one behavior policy — the enabling capability for large-scale predictive knowledge.",
  },
  {
    q: "The frontiers chapter argues that a promising direction is agents that...",
    options: [
      "rely on hand-engineered features",
      "learn their own representations/features and predictive knowledge autonomously from experience, scaling with computation",
      "avoid function approximation",
      "use only tabular methods",
    ],
    answer: 1,
    explain: "The chapter looks toward agents that construct their own features and world knowledge through experience, leaning on learning and search that scale with computation rather than on human-engineered features.",
  },
  {
    q: "Learning good REPRESENTATIONS is highlighted as important because...",
    options: [
      "representations don't matter",
      "the features/representation determine what can be learned and how well an agent generalizes; autonomous representation learning is a key open problem",
      "tables are always sufficient",
      "representations set the reward",
    ],
    answer: 1,
    explain: "Representation quality caps performance and generalization. The chapter frames learning useful representations autonomously (rather than hand-designing them) as one of RL's central open challenges.",
  },
  {
    q: "Predictive knowledge represented as many GVFs is appealing as a model of world knowledge because it is...",
    options: [
      "purely symbolic",
      "grounded, learnable from experience, and verifiable (predictions can be checked against outcomes)",
      "impossible to learn",
      "independent of data",
    ],
    answer: 1,
    explain: "GVF-based predictive knowledge is grounded in sensorimotor experience and self-verifying — the agent can check its predictions against what actually happens — offering a learnable, testable notion of world knowledge.",
  },
  {
    q: "A frontier concerning exploration is developing methods that...",
    options: [
      "never explore",
      "explore efficiently in large state spaces (e.g., intrinsic motivation, curiosity, or count-based bonuses)",
      "remove the reward",
      "use exploring starts only",
    ],
    answer: 1,
    explain: "Scaling exploration to large/high-dimensional problems is an active frontier: intrinsic motivation, curiosity, and count/uncertainty-based bonuses aim to drive systematic exploration where naive ε-greedy fails.",
  },
  {
    q: "The chapter notes that combining model-based and model-free methods is a frontier because...",
    options: [
      "they are incompatible",
      "integrating learned models (for planning/data efficiency) with model-free robustness could yield agents that are both efficient and flexible",
      "models are never useful",
      "model-free methods are obsolete",
    ],
    answer: 1,
    explain: "Model-based methods offer data efficiency and planning; model-free methods offer robustness to model errors. Effectively combining them (as in Dyna and modern successors) is an important open direction for capable agents.",
  },
  {
    q: "A safety/alignment concern raised is that powerful RL agents may...",
    options: [
      "always behave as intended",
      "optimize the literal reward in unintended, possibly harmful ways, so specifying the right objective is crucial",
      "ignore the reward",
      "never generalize",
    ],
    answer: 1,
    explain: "Because agents maximize exactly the specified reward, misspecification can lead to unintended or unsafe behavior. Getting the objective right (and safe) becomes increasingly important as agents grow more capable.",
  },
  {
    q: "The idea that agents should learn and plan with methods that scale with computation reflects the view that...",
    options: [
      "human knowledge engineering is the future",
      "general methods leveraging learning and search, which improve with more computation and data, tend to win in the long run",
      "small fixed models are best",
      "computation is irrelevant",
    ],
    answer: 1,
    explain: "The chapter favors general, scalable methods (learning + search) that ride increases in computation and data, over heavy problem-specific engineering — echoing a recurring lesson from RL's biggest successes.",
  },
  {
    q: "Options can be used within planning by treating them as...",
    options: [
      "rewards",
      "temporally-extended actions in a semi-Markov decision process, enabling multi-time-scale planning",
      "value functions",
      "features",
    ],
    answer: 1,
    explain: "With options, the decision process becomes semi-Markov (actions take variable time). Planning over options lets an agent reason in larger steps, dramatically shortening the effective horizon for long-range tasks.",
  },
  {
    q: "A GVF whose cumulant is 1 until termination and 0 after effectively predicts...",
    options: [
      "the total reward",
      "the expected time-to-termination (e.g., steps until an event) under its policy",
      "the discount factor",
      "the policy",
    ],
    answer: 1,
    explain: "With a constant cumulant of 1 accumulated until termination, the GVF's value is the expected number of steps to termination — a temporal prediction (e.g., 'how long until I reach the wall?'), showcasing GVFs' flexibility.",
  },
  {
    q: "The subproblem of learning WHERE and WHEN to use options (option discovery) is a frontier because...",
    options: [
      "options are given by the environment",
      "automatically discovering useful, reusable options from experience remains challenging and is key to effective hierarchical RL",
      "options are unnecessary",
      "it is fully solved",
    ],
    answer: 1,
    explain: "Hand-crafting options is limiting; automatically discovering useful temporal abstractions (option discovery) is an open, important problem for scalable hierarchical RL — the agent must find its own subgoals/skills.",
  },
  {
    q: "The chapter views prediction (via GVFs) and control as related in that...",
    options: [
      "they are unrelated",
      "a rich set of learned predictions can support better control and world understanding, and both use the same RL machinery",
      "prediction is useless for control",
      "control requires no predictions",
    ],
    answer: 1,
    explain: "Extensive predictive knowledge (GVFs) can inform decision-making and model the world, and both prediction and control share RL's value-learning machinery — an integrated view the chapter promotes.",
  },
  {
    q: "Intrinsic motivation in RL refers to...",
    options: [
      "the external task reward",
      "internally generated reward signals (e.g., curiosity, novelty) that drive exploration and skill acquisition without external reward",
      "the discount factor",
      "the behavior policy",
    ],
    answer: 1,
    explain: "Intrinsic motivation supplies internal rewards (novelty, prediction-error/curiosity, empowerment) that encourage exploration and learning of skills, especially useful when external reward is sparse — an active frontier.",
  },
  {
    q: "Why is off-policy learning central to the frontiers vision of predictive knowledge?",
    options: [
      "It limits learning to one policy",
      "It lets a single behavior stream train predictions/skills about many policies in parallel, building broad knowledge efficiently",
      "It removes the reward",
      "It forbids function approximation",
    ],
    answer: 1,
    explain: "Broad predictive knowledge means learning about many policies at once; off-policy learning makes this possible from one stream of experience (as in Horde), which is why stable off-policy methods (Ch. 11) matter so much.",
  },
  {
    q: "The frontiers chapter's stance on hand-engineering vs. learning is that...",
    options: [
      "hand-engineering should dominate",
      "long-term progress favors learning features/knowledge from experience over relying on human-designed representations",
      "learning is a dead end",
      "neither matters",
    ],
    answer: 1,
    explain: "The chapter leans toward autonomous learning of representations and knowledge, viewing over-reliance on hand-engineered features as a limitation to be overcome by scalable learning and search.",
  },
  {
    q: "A key open challenge in scaling RL is sample efficiency, i.e., learning...",
    options: [
      "with unlimited data only",
      "good policies from limited real experience (motivating model-based methods, transfer, and better exploration)",
      "without any reward",
      "only in simulation",
    ],
    answer: 1,
    explain: "Deep RL can require enormous experience. Improving sample efficiency — via models, transfer, hierarchy, and smarter exploration — is a major frontier, especially for real-world (non-simulated) applications.",
  },
  {
    q: "The options framework turns the underlying decision process into a...",
    options: [
      "bandit problem",
      "semi-Markov decision process (SMDP), where actions (options) have variable durations",
      "supervised learning problem",
      "static optimization",
    ],
    answer: 1,
    explain: "Because options last variable numbers of steps, planning/learning over them is naturally formulated as an SMDP. SMDP methods (with adjusted discounting for option durations) extend RL to temporally-extended actions.",
  },
  {
    q: "Which is a correct statement about GVFs and the value function you already know?",
    options: [
      "The ordinary value function is unrelated to GVFs",
      "The ordinary reward-based value function is a special case of a GVF (cumulant = reward, policy = the agent's, standard termination)",
      "GVFs cannot represent reward",
      "GVFs require a model",
    ],
    answer: 1,
    explain: "The standard value function is just one GVF — the one whose cumulant is the reward, under the target policy, with the usual discount/termination. GVFs generalize this to arbitrary signals, policies, and terminations.",
  },
  {
    q: "The chapter suggests that much of an agent's knowledge could be represented as...",
    options: [
      "a single scalar",
      "a large collection of predictions (GVFs) about the consequences of behaving in various ways",
      "a fixed lookup table",
      "the reward function only",
    ],
    answer: 1,
    explain: "The 'predictive knowledge' hypothesis is that world knowledge can be encoded as many GVFs — predictions of what would happen under different behaviors — grounded in and verifiable through experience.",
  },
  {
    q: "A reason reward design connects to AI safety is that...",
    options: [
      "rewards are always safe",
      "an agent will exploit any loophole in the reward to maximize it, so reward specification errors can cause unsafe or unintended behavior",
      "safety is unrelated to objectives",
      "agents ignore rewards",
    ],
    answer: 1,
    explain: "Reward misspecification is an alignment risk: powerful optimizers find and exploit loopholes ('reward hacking'). Ensuring the reward faithfully captures the intended goal is therefore a safety-critical design problem.",
  },
  {
    q: "Which best describes the relationship between learning and search emphasized as a frontier?",
    options: [
      "They are competitors; only one should be used",
      "They are complementary and both scale with computation; combining learned value/policy functions with search (as in AlphaZero) is powerful",
      "Search should be avoided",
      "Learning is unnecessary",
    ],
    answer: 1,
    explain: "The chapter (echoing Ch. 16) stresses that learning and search are complementary, scalable ingredients. Combining them — learned functions guiding search, search improving the learned functions — is a promising path to general agents.",
  },
  {
    q: "Continual (lifelong) learning is a frontier concerned with agents that...",
    options: [
      "learn one task then stop",
      "keep learning over a long lifetime, accumulating and transferring knowledge/skills across many tasks",
      "never adapt",
      "require i.i.d. data",
    ],
    answer: 1,
    explain: "Continual learning aims for agents that learn indefinitely, building on prior knowledge and transferring skills — as opposed to the common single-task, reset-heavy training regime. It raises challenges like avoiding catastrophic forgetting.",
  },
  {
    q: "The chapter frames abstraction (state and temporal) as important because it...",
    options: [
      "slows agents down",
      "lets agents represent situations and behaviors at useful levels of granularity, making learning and planning tractable in complex worlds",
      "removes the reward",
      "is only for small problems",
    ],
    answer: 1,
    explain: "State abstraction (grouping similar situations) and temporal abstraction (options) let agents cope with complexity by operating at appropriate levels — a key enabler for scalable, general intelligence.",
  },
  {
    q: "Which is TRUE about the maturity of the frontiers topics?",
    options: [
      "They are fully solved",
      "They are open research directions (GVFs, options/hierarchy, representation learning, reward design, exploration, safety) rather than settled solutions",
      "They are irrelevant to RL",
      "They only concern tabular RL",
    ],
    answer: 1,
    explain: "Chapter 17 presents active, unsolved directions — predictive knowledge, temporal abstraction, representation learning, reward/objective design, exploration, and safety — as the frontier of RL research.",
  },
  {
    q: "The vision of an agent building predictive knowledge suggests a form of world model that is...",
    options: [
      "a single distribution model",
      "a large collection of grounded, learned predictions (GVFs) rather than one monolithic model",
      "hand-coded",
      "unnecessary",
    ],
    answer: 1,
    explain: "Instead of one big distribution model, the GVF view represents world knowledge as many verifiable predictions about the effects of behaving in various ways — a distributed, experience-grounded notion of a world model.",
  },
  {
    q: "Why does the chapter connect representation learning to the success of deep RL?",
    options: [
      "Deep RL avoids representations",
      "Deep networks learn representations from raw input, and improving how agents learn/organize representations is key to further progress",
      "Representations are fixed",
      "Deep RL uses tables",
    ],
    answer: 1,
    explain: "Deep RL's power comes largely from learned representations. Advancing autonomous representation learning — including auxiliary predictive tasks (GVFs) that shape features — is seen as central to future gains.",
  },
  {
    q: "Auxiliary tasks (e.g., predicting many GVFs alongside the main task) can help an agent by...",
    options: [
      "distracting it from reward",
      "shaping richer representations that improve learning of the main control task",
      "removing the reward",
      "requiring a model",
    ],
    answer: 1,
    explain: "Learning auxiliary predictions (like GVFs) in parallel encourages the network to build informative features, which can accelerate and stabilize learning of the primary policy/value — a practical frontier technique.",
  },
  {
    q: "The chapter's discussion of designing reward signals cautions against...",
    options: [
      "sparse rewards only",
      "rewarding proxies/subgoals in ways the agent can exploit without achieving the true objective",
      "using any reward",
      "long horizons",
    ],
    answer: 1,
    explain: "Rewarding proxies (rather than the true goal) invites reward hacking: the agent maximizes the proxy while neglecting the real objective. The caution is to reward what you actually want, not a manipulable stand-in.",
  },
  {
    q: "Which best captures the role of off-policy stability results (Ch. 11) for the frontiers vision?",
    options: [
      "They are irrelevant",
      "Stable off-policy learning underpins learning many GVFs/skills in parallel (e.g., Horde), so it is foundational to scalable predictive knowledge",
      "They forbid GVFs",
      "They require tabular methods",
    ],
    answer: 1,
    explain: "The frontier of massively parallel off-policy prediction (Horde/GVFs) depends on stable off-policy learning with function approximation — exactly what gradient-/emphatic-TD (Ch. 11) provide — making that theory foundational.",
  },
  {
    q: "The overall message of Chapter 17 is that RL's future lies in...",
    options: [
      "abandoning value functions",
      "scalable agents that learn representations and rich predictive knowledge, use temporal abstraction, combine learning with search, and are guided by well-designed, safe objectives",
      "hand-coding everything",
      "solving only tabular problems",
    ],
    answer: 1,
    explain: "Chapter 17 envisions RL advancing through autonomous representation and predictive-knowledge learning (GVFs), temporal abstraction (options), integrated learning-and-search, and careful reward/objective design — the open frontiers of the field.",
  },
  {
    q: "A unifying theme between Chapters 16 and 17 is that progress comes from...",
    options: [
      "narrow, hand-tuned solutions",
      "general methods (learning + search) that scale with computation and data",
      "avoiding neural networks",
      "removing rewards",
    ],
    answer: 1,
    explain: "Both chapters emphasize general, scalable learning-and-search methods over bespoke engineering — the applications demonstrate it, and the frontiers chapter argues it is the path forward.",
  },
  {
    q: "Temporal abstraction helps exploration because options can...",
    options: [
      "only take single steps",
      "carry the agent to distant regions in one decision, enabling more effective, structured exploration",
      "remove the reward",
      "prevent learning",
    ],
    answer: 1,
    explain: "Extended options move the agent across many primitive steps per decision, so exploring at the level of options can reach faraway states and structure exploration far better than primitive-action random walks.",
  },
  {
    q: "The predictive-knowledge/GVF view relates to classical AI 'knowledge' by offering knowledge that is...",
    options: [
      "purely symbolic and ungrounded",
      "grounded in sensorimotor experience and empirically verifiable, unlike ungrounded symbolic assertions",
      "unlearnable",
      "independent of the agent",
    ],
    answer: 1,
    explain: "GVF-based knowledge is grounded (defined in terms of the agent's own experience) and verifiable (predictions can be checked), addressing the grounding problem that ungrounded symbolic knowledge representations face.",
  },
  {
    q: "Which is a correct statement about the book's concluding outlook?",
    options: [
      "RL is a finished field",
      "RL is a powerful, broadly applicable framework with many exciting open problems, poised to play a central role in understanding and building intelligence",
      "RL applies only to games",
      "RL should be abandoned",
    ],
    answer: 1,
    explain: "The book concludes optimistically: RL is a general, successful framework with rich open frontiers (abstraction, representation, prediction, safety), central to both understanding natural intelligence and building artificial agents.",
  },
  {
    q: "Designing rewards, learning representations, and temporal abstraction are unified by the goal of...",
    options: [
      "reducing computation",
      "enabling agents to learn and act effectively and autonomously in complex, long-horizon environments",
      "avoiding value functions",
      "removing exploration",
    ],
    answer: 1,
    explain: "These frontiers all serve the overarching aim: agents that autonomously learn useful objectives, representations, and behavioral abstractions to cope with complex, long-horizon, real-world environments.",
  },
  {
    q: "The frontiers chapter suggests that the biggest gains will come from methods that...",
    options: [
      "depend on ever more human knowledge engineering",
      "improve automatically with more computation and experience (general learning and search)",
      "avoid learning",
      "use only fixed features",
    ],
    answer: 1,
    explain: "Consistent with RL's landmark successes, the chapter argues the largest long-term gains come from general methods whose performance scales with computation and experience — learning and search — rather than manual engineering.",
  }
);
