// ============================================================================
//  data-10-b.js — Chapter 10 (On-policy Control with Approximation) pool
// ============================================================================
QUESTIONS["10"].push(
  {
    q: "Episodic semi-gradient Sarsa approximates which quantity?",
    options: [
      "The state-value function v̂(s,w)",
      "The action-value function q̂(s,a,w), so actions can be compared for control",
      "The model",
      "The reward function",
    ],
    answer: 1,
    explain: "For control we need to compare actions, so we approximate q̂(s,a,w). Semi-gradient Sarsa updates w toward R+γq̂(S',A',w) and selects actions ε-greedily w.r.t. q̂.",
  },
  {
    q: "The semi-gradient Sarsa update is w ← w + α[R + γq̂(S',A',w) − q̂(S,A,w)] · ___.",
    options: [
      "1",
      "∇q̂(S,A,w) (the feature vector for (S,A) in the linear case)",
      "the reward",
      "the discount",
    ],
    answer: 1,
    explain: "The update multiplies the TD error by the gradient ∇q̂(S,A,w). For linear q̂, this gradient is the feature vector x(S,A), giving w ← w + αδ x(S,A).",
  },
  {
    q: "In control with approximation, action selection is typically...",
    options: [
      "greedy only",
      "ε-greedy (or another soft policy) with respect to the current q̂ estimates",
      "uniform random",
      "based on the model",
    ],
    answer: 1,
    explain: "To ensure exploration under GPI, actions are chosen ε-greedily (or via another soft policy) w.r.t. q̂(s,·,w). This mirrors tabular Sarsa/Q-learning control but with a parameterized value function.",
  },
  {
    q: "The Mountain Car task is challenging because...",
    options: [
      "the reward is huge",
      "the car's engine is too weak to climb directly, so the agent must first move away from the goal to build momentum",
      "it has no actions",
      "the state is discrete",
    ],
    answer: 1,
    explain: "Mountain Car has a continuous 2D state (position, velocity) and an underpowered engine; the optimal policy oscillates to gain energy. It's a classic testbed for tile-coded semi-gradient Sarsa.",
  },
  {
    q: "The Mountain Car state is continuous, so a natural representation is...",
    options: [
      "a lookup table over exact positions",
      "tile coding over (position, velocity), giving sparse binary features for semi-gradient Sarsa",
      "the reward",
      "a distribution model",
    ],
    answer: 1,
    explain: "Tile coding discretizes the continuous (position, velocity) space with overlapping tilings, producing sparse features. Semi-gradient Sarsa over these features learns the control policy efficiently.",
  },
  {
    q: "The typical reward in Mountain Car is −1 per time step until the goal, which encourages the agent to...",
    options: [
      "take as long as possible",
      "reach the goal in as few steps as possible (maximizing the sum of −1s means minimizing steps)",
      "stay still",
      "ignore the goal",
    ],
    answer: 1,
    explain: "With −1 per step and 0 at the goal, the return is maximized by reaching the goal quickly. This is the standard shortest-time formulation for episodic control tasks.",
  },
  {
    q: "n-step semi-gradient Sarsa improves on one-step semi-gradient Sarsa by...",
    options: [
      "removing function approximation",
      "using an n-step return target, which can speed learning (intermediate n often best)",
      "requiring a model",
      "eliminating exploration",
    ],
    answer: 1,
    explain: "n-step semi-gradient Sarsa bootstraps after n steps using q̂, combining multi-step credit assignment with approximation. As in the tabular case, an intermediate n frequently performs best.",
  },
  {
    q: "For CONTINUING control tasks, the book argues discounting is problematic with function approximation and replaces it with...",
    options: [
      "a larger discount",
      "the average-reward setting (maximize long-run average reward per step)",
      "Monte Carlo returns",
      "exploring starts",
    ],
    answer: 1,
    explain: "In continuing tasks with function approximation, the average-reward formulation is preferred: the agent maximizes r(π), the long-run average reward per time step, with values defined relative to it.",
  },
  {
    q: "In the average-reward setting, r(π) denotes...",
    options: [
      "the immediate reward",
      "the long-run average reward per step under policy π",
      "the discounted return",
      "the reward variance",
    ],
    answer: 1,
    explain: "r(π) is the steady-state average reward per time step obtained by following π. Policies are ranked by r(π); differential values measure transient deviations from this average.",
  },
  {
    q: "The 'differential return' in the average-reward setting is defined by...",
    options: [
      "discounting rewards by γ",
      "subtracting the average reward from each reward: G_t = Σ (R_{t+k+1} − r(π))",
      "using only the first reward",
      "squaring the rewards",
    ],
    answer: 1,
    explain: "Differential returns sum reward deviations from the average, G_t = Σ_{k}(R_{t+k+1} − r(π)). Differential value functions and differential Bellman equations (without γ) follow from this definition.",
  },
  {
    q: "The differential semi-gradient Sarsa TD error is δ = R − R̄ + q̂(S',A',w) − q̂(S,A,w), where R̄ is...",
    options: [
      "the discount factor",
      "a running estimate of the average reward r(π)",
      "the immediate reward",
      "a feature",
    ],
    answer: 1,
    explain: "R̄ estimates the average reward and is itself updated toward observed rewards. Note there is NO discount factor γ in the differential TD error — a hallmark of the average-reward formulation.",
  },
  {
    q: "In differential semi-gradient Sarsa, the average-reward estimate R̄ is typically updated by...",
    options: [
      "keeping it fixed",
      "R̄ ← R̄ + β·δ (moving it toward observed reward using the TD error and a step size β)",
      "the discount",
      "the policy gradient",
    ],
    answer: 1,
    explain: "R̄ is adjusted using the TD error with its own step size β: R̄ ← R̄ + βδ. This tracks the long-run average reward as learning proceeds, anchoring the differential values.",
  },
  {
    q: "The access-control queuing example (a continuing task) is naturally handled by...",
    options: [
      "episodic Monte Carlo",
      "differential (average-reward) semi-gradient control, since it has no natural episodes",
      "value iteration with a model",
      "exploring starts",
    ],
    answer: 1,
    explain: "The server access-control queue runs indefinitely (no episodes), so the average-reward formulation with differential semi-gradient Sarsa is appropriate — maximizing long-run reward per step.",
  },
  {
    q: "Why can the discounted objective lose its usual meaning under function approximation in continuing tasks?",
    options: [
      "The return becomes negative",
      "With approximation, the ordering of policies by discounted value need not be preserved, and the average of discounted returns is proportional to r(π)",
      "Discounting is uncomputable",
      "There is no reward",
    ],
    answer: 1,
    explain: "The book shows that with function approximation the guarantee that better discounted value = better policy can fail, and the discounted objective essentially reduces to the average-reward objective — motivating the switch.",
  },
  {
    q: "Semi-gradient Sarsa for control is an instance of...",
    options: [
      "supervised learning",
      "Generalized Policy Iteration with approximate action-value evaluation and (ε-)greedy improvement",
      "dynamic programming with a model",
      "Monte Carlo tree search",
    ],
    answer: 1,
    explain: "It is GPI: evaluate q̂ via semi-gradient TD updates and improve by acting ε-greedily w.r.t. q̂. The value function is now parameterized, but the evaluation–improvement structure is the same.",
  },
  {
    q: "Convergence guarantees for on-policy control with function approximation are...",
    options: [
      "as strong as the tabular case",
      "weaker — control with approximation (even on-policy) generally lacks the clean convergence guarantees of tabular methods, though it often works well in practice",
      "nonexistent for linear methods",
      "identical to DP",
    ],
    answer: 1,
    explain: "Bringing approximation into control (with the moving target of an improving policy) weakens theoretical guarantees relative to tabular RL. In practice, on-policy semi-gradient Sarsa with good features (like tile coding) works reliably.",
  },
  {
    q: "The features for action-value approximation q̂(s,a,w) are often constructed by...",
    options: [
      "ignoring the action",
      "tiling the state space separately for each action (or including the action in the feature construction)",
      "using only the reward",
      "a distribution model",
    ],
    answer: 1,
    explain: "A common approach gives each action its own set of state features (e.g., separate tilings per action), so q̂(s,a,w) has action-specific weights. This lets the same state produce different values for different actions.",
  },
  {
    q: "In Mountain Car, why does semi-gradient Sarsa initially explore widely before finding the goal?",
    options: [
      "Because the reward is positive everywhere",
      "Because rewards are −1 everywhere until the goal, so the agent must wander (guided by ε-greedy and generalization) until it stumbles onto the goal, then values propagate",
      "Because it uses a model",
      "Because the state is discrete",
    ],
    answer: 1,
    explain: "With uniform −1 rewards and no gradient toward the goal initially, the agent explores until it first reaches the goal; from then on, tile-coding generalization and TD backups rapidly shape a good policy.",
  },
  {
    q: "The differential form of the Bellman equations (average-reward) differs from the discounted form by...",
    options: [
      "including γ²",
      "omitting the discount factor and subtracting the average reward r(π)",
      "using the max only",
      "ignoring successor states",
    ],
    answer: 1,
    explain: "Differential Bellman equations have no γ; instead each reward is compared to r(π). Values represent relative (differential) desirability of states rather than absolute discounted returns.",
  },
  {
    q: "Which is TRUE about the average-reward setting's value functions?",
    options: [
      "They are unique in absolute terms",
      "Differential values are defined only up to an additive constant (a shared offset doesn't change the differences)",
      "They require discounting",
      "They equal the rewards",
    ],
    answer: 1,
    explain: "Differential value functions are determined only up to an additive constant, because only differences among state values matter for decision-making in the average-reward formulation.",
  },
  {
    q: "For episodic control with approximation, the target in one-step semi-gradient Sarsa at a terminal transition uses...",
    options: [
      "q̂ of the terminal state",
      "just the terminal reward R (the terminal state's value is 0)",
      "the average reward",
      "the full return",
    ],
    answer: 1,
    explain: "At a transition into a terminal state, there is no bootstrap term (terminal value = 0), so the target is simply R. This correctly handles the ends of episodes in semi-gradient Sarsa.",
  },
  {
    q: "Which is a correct reason to prefer the average-reward setting over a discount close to 1 for continuing control?",
    options: [
      "It is easier to compute rewards",
      "It directly optimizes long-run performance without an arbitrary discount, and avoids the policy-ordering issues discounting has under approximation",
      "It removes the value function",
      "It requires a model",
    ],
    answer: 1,
    explain: "Average reward optimizes the natural long-run criterion without choosing an arbitrary γ, and sidesteps the theoretical problems the book identifies with discounting under function approximation in continuing tasks.",
  },
  {
    q: "The exploration strategy most commonly paired with semi-gradient Sarsa in the chapter is...",
    options: [
      "optimistic initialization only",
      "ε-greedy action selection",
      "UCB",
      "no exploration",
    ],
    answer: 1,
    explain: "The chapter's control examples use ε-greedy exploration with semi-gradient Sarsa. Exploration remains necessary under approximation to visit and correctly value all relevant actions.",
  },
  {
    q: "In the average-reward differential setting, a state's differential value being positive means...",
    options: [
      "the reward is positive there",
      "starting there yields more than the average reward in the transient (it is a relatively good state)",
      "the discount is high",
      "the policy is optimal",
    ],
    answer: 1,
    explain: "A positive differential value indicates the state is better than average — following the policy from it accrues more than r(π) per step during the transient. Negative means worse than average.",
  },
  {
    q: "The main new algorithmic idea of Chapter 10 (beyond Ch. 9) is...",
    options: [
      "value function approximation for prediction",
      "extending approximation to CONTROL (semi-gradient Sarsa) and introducing the average-reward setting for continuing control",
      "Monte Carlo prediction",
      "importance sampling",
    ],
    answer: 1,
    explain: "Chapter 10 moves from prediction (Ch. 9) to on-policy control with approximation via semi-gradient Sarsa, and develops the average-reward formulation (differential values) for continuing tasks.",
  },
  {
    q: "Which is TRUE about combining n-step returns with function approximation in control?",
    options: [
      "It is impossible",
      "n-step semi-gradient Sarsa is straightforward and, like the tabular case, often benefits from an intermediate n",
      "It requires a model",
      "It removes bootstrapping",
    ],
    answer: 1,
    explain: "n-step semi-gradient Sarsa simply uses an n-step return with q̂ as the bootstrap. It typically improves over one-step Sarsa for an intermediate n, just as in the tabular setting.",
  },
  {
    q: "A subtlety in average-reward control is that R̄ (the average-reward estimate) and the differential values are learned...",
    options: [
      "independently and offline",
      "simultaneously online, with R̄ tracking the average as the policy (and thus r(π)) changes",
      "from a model",
      "using discounting",
    ],
    answer: 1,
    explain: "R̄ and the differential value weights are updated together online. As the policy improves, r(π) changes, and R̄ must keep tracking it — coupling the two learning processes.",
  },
  {
    q: "Why does the −1-per-step reward make the value function in Mountain Car roughly proportional to (negative) time-to-goal?",
    options: [
      "Because rewards are random",
      "Because the return equals minus the number of steps to the goal, so v̂ estimates the negative expected steps remaining",
      "Because γ=0",
      "Because the state is discrete",
    ],
    answer: 1,
    explain: "With −1 per step, the (undiscounted or near-undiscounted) return from a state is minus the steps until the goal, so the learned value function approximates the negative cost-to-go (time-to-goal) surface.",
  },
  {
    q: "Which statement correctly contrasts episodic vs. continuing control in this chapter?",
    options: [
      "Both must use discounting",
      "Episodic control uses discounted (or undiscounted) returns with terminal states; continuing control uses the average-reward/differential formulation",
      "Continuing control cannot be done",
      "Episodic control has no reward",
    ],
    answer: 1,
    explain: "Episodic tasks have terminal states and use (possibly discounted) returns; continuing tasks lack episodes and are handled with the average-reward setting and differential semi-gradient methods.",
  },
  {
    q: "The 'differential' in differential value functions refers to values being measured...",
    options: [
      "as derivatives",
      "relative to the average reward (differences from the long-run average), not as absolute discounted sums",
      "with respect to the policy parameters",
      "per feature",
    ],
    answer: 1,
    explain: "Differential values quantify how much better or worse than the average-reward baseline a state (or state–action) is. They replace absolute discounted values in the average-reward setting.",
  },
  {
    q: "Which is a correct statement about action-value features in tile-coded control?",
    options: [
      "One tiling serves all actions with shared weights",
      "Typically each action gets its own weights over the (tiled) state features, so different actions can have different values in the same state",
      "Actions are ignored",
      "Features must be dense",
    ],
    answer: 1,
    explain: "To distinguish actions, the common design gives each action its own weight vector over the state's tile features, so q̂(s,a,w) varies by action — enabling ε-greedy action selection.",
  },
  {
    q: "The performance of semi-gradient Sarsa on Mountain Car is sensitive to...",
    options: [
      "only the reward",
      "the number/width of tilings and the step size (feature resolution and learning rate)",
      "the discount only",
      "the random seed alone",
    ],
    answer: 1,
    explain: "Learning quality depends on the tile-coding resolution (number and width of tilings) and the step size. Good settings yield fast, reliable learning; poor ones slow or destabilize it.",
  },
  {
    q: "Which is TRUE about exploration in continuing average-reward control?",
    options: [
      "No exploration is needed",
      "Exploration (e.g., ε-greedy) is still required to keep visiting and correctly valuing all state–action pairs",
      "Only optimistic initialization works",
      "Exploration is harmful",
    ],
    answer: 1,
    explain: "As in all control, the agent must keep exploring to estimate action values accurately and avoid locking onto suboptimal behavior — ε-greedy remains a standard choice in the average-reward setting.",
  },
  {
    q: "A key practical takeaway from Mountain Car is that...",
    options: [
      "tabular methods suffice",
      "with a good feature representation (tile coding), simple semi-gradient Sarsa solves a nontrivial continuous control task",
      "a model is required",
      "policy gradients are necessary",
    ],
    answer: 1,
    explain: "Mountain Car shows that value-based control with a suitable representation (tile coding) and semi-gradient Sarsa handles continuous-state control well, without needing a model or policy-gradient methods.",
  },
  {
    q: "In differential semi-gradient Sarsa, omitting the R̄ correction (i.e., not subtracting the average reward) would...",
    options: [
      "have no effect",
      "break the average-reward formulation, since differential values are defined relative to r(π)",
      "improve convergence",
      "add discounting",
    ],
    answer: 1,
    explain: "The − R̄ term is essential: differential values are deviations from the average reward. Without it, the TD error wouldn't correspond to the differential Bellman equation and learning would be ill-posed for continuing tasks.",
  },
  {
    q: "Which best summarizes the relationship between Chapters 9 and 10?",
    options: [
      "They are unrelated",
      "Chapter 9 does prediction with approximation; Chapter 10 extends it to control (and adds average reward)",
      "Chapter 10 is only about tabular methods",
      "Both are about policy gradients",
    ],
    answer: 1,
    explain: "Chapter 9 establishes approximate prediction (evaluating a fixed policy); Chapter 10 builds on it for approximate control (improving the policy via semi-gradient Sarsa) and introduces the average-reward setting.",
  },
  {
    q: "For an episodic task with approximation, semi-gradient Sarsa's weight update per step costs (linear case)...",
    options: [
      "O(number of states)",
      "O(number of active features), which is small for sparse representations like tile coding",
      "O(number of episodes)",
      "O(1) regardless of features",
    ],
    answer: 1,
    explain: "The linear update touches only the active features, so cost per step is proportional to the number of active features — a small constant for tile coding — making it efficient even in large state spaces.",
  },
  {
    q: "The average reward r(π) can be interpreted as...",
    options: [
      "the immediate reward",
      "the reward rate: total reward accumulated divided by time, in the long run under π",
      "the discount factor",
      "the value of the start state",
    ],
    answer: 1,
    explain: "r(π) is the long-run reward per unit time (reward rate) under policy π. Maximizing it is the objective in the average-reward setting for continuing tasks.",
  },
  {
    q: "Which is a correct characterization of on-policy control with approximation's stability?",
    options: [
      "It always diverges",
      "It is generally stable in practice for linear semi-gradient Sarsa (on-policy), though with weaker guarantees than tabular control",
      "It requires off-policy training",
      "It needs a distribution model",
    ],
    answer: 1,
    explain: "On-policy linear semi-gradient control is typically stable and effective in practice; the serious instability risk (deadly triad) arises with off-policy training plus bootstrapping and approximation, addressed in Chapter 11.",
  },
  {
    q: "In the average-reward setting, a policy that achieves higher r(π) is...",
    options: [
      "worse",
      "better (r(π) is the primary criterion for ranking policies)",
      "equivalent",
      "undefined",
    ],
    answer: 1,
    explain: "Policies are ranked by their average reward rate r(π): higher is better. Differential value functions then describe transient advantages among states under a given policy.",
  },
  {
    q: "Why does the chapter present control (Sarsa) rather than Q-learning for the primary approximation results?",
    options: [
      "Q-learning is tabular only",
      "On-policy semi-gradient Sarsa has better stability properties with approximation than off-policy Q-learning (which risks the deadly triad)",
      "Q-learning ignores rewards",
      "Sarsa needs a model",
    ],
    answer: 1,
    explain: "On-policy semi-gradient Sarsa is stable with linear approximation, whereas off-policy Q-learning with approximation can diverge (the deadly triad, Ch. 11). Hence the on-policy control focus in Chapter 10.",
  },
  {
    q: "The overall contribution of Chapter 10 is to show that...",
    options: [
      "control with approximation is impossible",
      "value-based control scales to large/continuous problems via semi-gradient Sarsa, and continuing tasks are best framed with average reward",
      "only Monte Carlo works",
      "discounting is always best",
    ],
    answer: 1,
    explain: "Chapter 10 demonstrates scalable on-policy control with function approximation (semi-gradient Sarsa on Mountain Car) and develops the average-reward/differential framework for continuing control tasks.",
  }
);
