// ============================================================================
//  data-04-b.js — Chapter 04 (Dynamic Programming) expansion pool
// ============================================================================
QUESTIONS["04"].push(
  {
    q: "In iterative policy evaluation, the update v_{k+1}(s) ← Σ_a π(a|s) Σ_{s',r} p(s',r|s,a)[r + γ v_k(s')] is called a(n)...",
    options: ["Sample update", "Expected (full) update", "Monte Carlo update", "Gradient update"],
    answer: 1,
    explain: "DP uses expected updates: it averages over ALL successor states/rewards using the model, unlike sample updates (MC/TD) that use one sampled successor. This is the hallmark of dynamic programming.",
  },
  {
    q: "Iterative policy evaluation is guaranteed to converge to v_π as k→∞ provided...",
    options: [
      "γ = 1 always",
      "γ < 1 or eventual termination is guaranteed under π",
      "The policy is optimal",
      "The reward is zero",
    ],
    answer: 1,
    explain: "The sequence {v_k} converges to v_π when γ<1 (or when the policy guarantees termination), because the Bellman operator for a fixed policy is a contraction under those conditions.",
  },
  {
    q: "An 'in-place' version of iterative policy evaluation...",
    options: [
      "Requires two arrays of values",
      "Uses a single array, updating states using the newest available values, and typically converges faster",
      "Cannot converge",
      "Ignores the model",
    ],
    answer: 1,
    explain: "In-place DP updates values in a single array, so later states in a sweep use already-updated values. It usually converges faster than the two-array version and is the form asynchronous DP builds on.",
  },
  {
    q: "A 'sweep' in dynamic programming refers to...",
    options: [
      "One episode of experience",
      "One systematic pass of updates through the entire state space",
      "A gradient step",
      "A random state update",
    ],
    answer: 1,
    explain: "A sweep is a full pass over all states, applying the update to each. Policy evaluation and value iteration proceed by repeated sweeps until values stop changing appreciably.",
  },
  {
    q: "The policy improvement theorem states that if q_π(s, π'(s)) ≥ v_π(s) for all s, then...",
    options: [
      "π' is worse than π",
      "π' is at least as good as π (v_π'(s) ≥ v_π(s) for all s)",
      "π' equals π",
      "π' is optimal",
    ],
    answer: 1,
    explain: "If choosing π'(s) is at least as good as following π from every state (in the one-step sense), then π' ≥ π everywhere. This justifies greedy improvement.",
  },
  {
    q: "Greedy policy improvement forms π'(s) = argmax_a ...",
    options: [
      "π(a|s)",
      "Σ_{s',r} p(s',r|s,a)[r + γ v_π(s')] = q_π(s,a)",
      "r(s,a)",
      "v_π(s)",
    ],
    answer: 1,
    explain: "The greedy policy picks, in each state, the action maximizing the one-step lookahead value q_π(s,a) = Σ p(s',r|s,a)[r+γv_π(s')]. By the improvement theorem this new policy is ≥ π.",
  },
  {
    q: "If greedy improvement produces a policy that is no better than π (i.e., v_π' = v_π), then...",
    options: [
      "π must be evaluated again",
      "π (and π') satisfy the Bellman optimality equation and are optimal",
      "The algorithm has failed",
      "γ must be decreased",
    ],
    answer: 1,
    explain: "When improvement yields no change, v_π satisfies the Bellman OPTIMALITY equation, so π is optimal. This is the stopping guarantee of policy iteration.",
  },
  {
    q: "Policy iteration produces a sequence π_0 → v_{π_0} → π_1 → v_{π_1} → … that...",
    options: [
      "May cycle forever without improving",
      "Monotonically improves and converges to an optimal policy in a finite number of iterations (finite MDP)",
      "Requires infinite iterations always",
      "Ignores value functions",
    ],
    answer: 1,
    explain: "Each policy is strictly better than the last (or optimal), and a finite MDP has finitely many policies, so policy iteration reaches an optimal policy in finitely many steps.",
  },
  {
    q: "A practical drawback of policy iteration is that...",
    options: [
      "It never converges",
      "Each iteration requires a full policy evaluation, which itself may need many sweeps",
      "It cannot use a model",
      "It ignores the policy",
    ],
    answer: 1,
    explain: "Policy iteration's expense comes from fully evaluating each policy (many sweeps) before improving. Value iteration addresses this by truncating evaluation to a single sweep.",
  },
  {
    q: "Value iteration's update is v_{k+1}(s) ← max_a Σ_{s',r} p(s',r|s,a)[r + γ v_k(s')], which combines...",
    options: [
      "Two full policy evaluations",
      "One sweep of policy evaluation with policy improvement (the max)",
      "Monte Carlo sampling",
      "Only policy improvement",
    ],
    answer: 1,
    explain: "Value iteration folds improvement into evaluation by taking the max over actions each sweep. It is policy iteration with evaluation truncated to one sweep — turning the Bellman OPTIMALITY equation into an update rule.",
  },
  {
    q: "Value iteration is guaranteed to converge to v* because the Bellman optimality operator is...",
    options: [
      "A random map",
      "A contraction mapping (under γ<1), so repeated application converges to its unique fixed point v*",
      "Linear only",
      "Non-convergent",
    ],
    answer: 1,
    explain: "The Bellman optimality operator is a γ-contraction in the max norm, so iterating it converges to the unique fixed point v* regardless of the initial values (for γ<1).",
  },
  {
    q: "In practice, value iteration is stopped when...",
    options: [
      "The policy is random",
      "The maximum change in values across a sweep falls below a small threshold θ",
      "Exactly one sweep completes",
      "γ reaches 1",
    ],
    answer: 1,
    explain: "Value iteration terminates when the largest value change in a sweep (max_s |v_{k+1}(s)−v_k(s)|) is below θ, indicating near-convergence. A greedy policy is then extracted.",
  },
  {
    q: "Asynchronous DP algorithms differ from standard DP in that they...",
    options: [
      "Must sweep all states in order each iteration",
      "Update states in an arbitrary order, possibly some more than others, and can converge if all states are updated infinitely often",
      "Cannot reach v*",
      "Require two value arrays",
    ],
    answer: 1,
    explain: "Asynchronous DP relaxes the systematic full-sweep requirement, updating states in any order (even focusing on important ones), and still converges as long as no state is permanently ignored.",
  },
  {
    q: "A benefit of asynchronous DP is that it can...",
    options: [
      "Eliminate the need for a model",
      "Interleave computation with real-time interaction, focusing updates on states the agent actually visits",
      "Guarantee one-sweep convergence",
      "Avoid the Bellman equation",
    ],
    answer: 1,
    explain: "By not requiring complete sweeps, asynchronous DP can concentrate updates on relevant states and be interleaved with the agent's real-time experience, improving efficiency for large problems.",
  },
  {
    q: "Generalized Policy Iteration (GPI) is the idea that evaluation and improvement processes...",
    options: [
      "Must fully complete before the other begins",
      "Interact and can be interleaved at any granularity; their interaction converges toward optimality",
      "Are unrelated",
      "Are used only in bandits",
    ],
    answer: 1,
    explain: "GPI abstracts policy iteration: as long as both an evaluation process (toward v_π) and an improvement process (toward greedy) keep operating, together they drive toward the optimal value function and policy — regardless of how finely they are interleaved.",
  },
  {
    q: "In GPI, the two processes can be seen as competing and cooperating because...",
    options: [
      "They always agree",
      "Making the policy greedy usually makes the value function wrong for the new policy, and re-evaluating changes the greedy policy — yet together they converge to a joint fixed point (v*, π*)",
      "One always dominates",
      "They never converge",
    ],
    answer: 1,
    explain: "Each step of improvement typically invalidates the current evaluation, and re-evaluation changes what is greedy; this push-pull nonetheless converges to the single point where the policy is greedy w.r.t. its own value function — optimality.",
  },
  {
    q: "'Bootstrapping' in DP means value estimates are updated using...",
    options: [
      "Full sampled returns to episode end",
      "Estimates of successor state values (not waiting for actual returns)",
      "A supervised label",
      "The reward only",
    ],
    answer: 1,
    explain: "DP bootstraps: it updates v(s) from the current estimates of successor values v(s'), rather than from complete returns. This is shared with TD methods and distinguishes both from Monte Carlo.",
  },
  {
    q: "Why is DP said to suffer from the 'curse of dimensionality'?",
    options: [
      "It cannot represent policies",
      "The number of states grows exponentially with the number of state variables, making full sweeps intractable for large problems",
      "It uses too little memory",
      "It requires random sampling",
    ],
    answer: 1,
    explain: "DP's cost scales with the size of the state set, which grows exponentially in the number of state variables. This limits exact DP to moderate problems and motivates sampling and approximation.",
  },
  {
    q: "Despite the curse of dimensionality, DP is considered efficient because it finds an optimal policy in time...",
    options: [
      "Exponential in the number of states and actions",
      "Polynomial in the number of states and actions (far better than exhaustive policy search)",
      "Constant time",
      "Independent of the problem size",
    ],
    answer: 1,
    explain: "DP runs in time polynomial in |S| and |A|, dramatically better than the exponentially large number of deterministic policies (|A|^|S|) that direct search would consider.",
  },
  {
    q: "In Jack's Car Rental (a classic policy-iteration example), the actions are...",
    options: [
      "Prices to charge",
      "Numbers of cars to move overnight between the two locations",
      "Whether to buy cars",
      "Which customer to serve",
    ],
    answer: 1,
    explain: "In Jack's Car Rental, the agent decides how many cars to move between two locations each night (bounded, with a per-car cost) to maximize expected rental profit — solved with policy iteration.",
  },
  {
    q: "In the Gambler's Problem (value-iteration example), the state is the gambler's capital and the actions are...",
    options: [
      "Whether to quit",
      "Stakes to bet (how much of the capital to wager on the next coin flip)",
      "The coin's bias",
      "The number of flips",
    ],
    answer: 1,
    explain: "The gambler bets a stake on each flip, aiming to reach a goal capital. Value iteration finds the optimal (often surprising, non-monotonic) betting policy as a function of current capital.",
  },
  {
    q: "The optimal value function found by DP for a fixed problem is unique, but the optimal policy...",
    options: [
      "Is always unique",
      "May not be unique (ties can yield multiple optimal policies)",
      "Does not exist",
      "Depends on the initial values",
    ],
    answer: 1,
    explain: "v* (and q*) are unique, but several policies can be optimal when actions tie in value. Any policy greedy with respect to v* is optimal.",
  },
  {
    q: "Which best describes the relationship between value iteration and policy iteration?",
    options: [
      "They are unrelated algorithms",
      "Value iteration is a special case of GPI where policy evaluation is truncated to a single sweep",
      "Policy iteration never converges but value iteration does",
      "They require different MDPs",
    ],
    answer: 1,
    explain: "Both are instances of GPI. Value iteration truncates evaluation to one sweep (with a max), while policy iteration runs evaluation to (near) completion before improving. Intermediate truncations are also possible.",
  },
  {
    q: "DP methods require which of the following that model-free methods do not?",
    options: [
      "A reward signal",
      "A complete and accurate model of the environment's dynamics p(s',r|s,a)",
      "A value function",
      "A policy",
    ],
    answer: 1,
    explain: "DP needs the full model p to compute expected updates. Monte Carlo and TD methods instead learn from sampled experience, requiring no model — a key practical advantage.",
  },
  {
    q: "'Truncated policy iteration' refers to...",
    options: [
      "Skipping improvement",
      "Running only a few evaluation sweeps (not to convergence) before each improvement",
      "Using no model",
      "Evaluating a random policy",
    ],
    answer: 1,
    explain: "Truncated policy iteration performs a limited number of evaluation sweeps between improvements. Value iteration is the extreme case of one sweep; full policy iteration is the other extreme.",
  },
  {
    q: "For a fixed policy, the Bellman operator T_π defined by (T_π v)(s) = Σ_a π(a|s)Σ p(s',r|s,a)[r+γv(s')] has v_π as its...",
    options: [
      "Maximum",
      "Unique fixed point",
      "Gradient",
      "Derivative",
    ],
    answer: 1,
    explain: "v_π is the unique fixed point of the policy's Bellman operator T_π (a contraction for γ<1). Iterative policy evaluation repeatedly applies T_π to converge to it.",
  },
  {
    q: "Why does acting greedily with respect to v_π give a policy at least as good as π?",
    options: [
      "By random chance",
      "Because in each state it chooses an action whose one-step value q_π(s,a) is ≥ v_π(s), and the policy improvement theorem then applies",
      "Because it ignores the model",
      "Because it uses Monte Carlo returns",
    ],
    answer: 1,
    explain: "The greedy action has q_π(s,a) ≥ v_π(s) in every state (it can always at least match following π), so by the policy improvement theorem the greedy policy is ≥ π.",
  },
  {
    q: "The main computational operation shared by policy evaluation and value iteration is...",
    options: [
      "Sampling episodes",
      "Applying a Bellman-style expected update over successor states",
      "Gradient descent",
      "Shuffling actions",
    ],
    answer: 1,
    explain: "Both repeatedly apply expected (full-width) Bellman updates using the model. Policy evaluation averages over the policy's actions; value iteration maxes over actions.",
  },
  {
    q: "Which statement about DP and the Bellman equations is correct?",
    options: [
      "DP ignores the Bellman equations",
      "DP algorithms are obtained by turning Bellman equations into iterative update rules",
      "DP only uses the reward function",
      "DP requires no successor states",
    ],
    answer: 1,
    explain: "DP methods are essentially the Bellman equations (for v_π or v*) recast as assignment/update rules and iterated to a fixed point. This is the unifying view of the chapter.",
  },
  {
    q: "The advantage of DP over exhaustive search of all deterministic policies is greatest when...",
    options: [
      "There is one state",
      "The numbers of states and actions are large (exhaustive search is exponential, DP is polynomial)",
      "γ = 0",
      "There is no reward",
    ],
    answer: 1,
    explain: "There are |A|^|S| deterministic policies; enumerating them is hopeless for large problems. DP's polynomial-time guarantee is a huge improvement, making it the classical baseline for planning.",
  },
  {
    q: "In value iteration, extracting the final policy after values converge requires...",
    options: [
      "Nothing; the values are the policy",
      "One more greedy step: π(s) = argmax_a Σ p(s',r|s,a)[r+γv(s')]",
      "A full policy evaluation",
      "Sampling episodes",
    ],
    answer: 1,
    explain: "Value iteration outputs a value function; the deterministic optimal policy is obtained by a final greedy (argmax) pass over actions using the converged values and the model.",
  },
  {
    q: "Which is an example of prioritizing updates in DP (a precursor to prioritized sweeping)?",
    options: [
      "Updating states uniformly",
      "Updating states whose values are likely to change the most first",
      "Never updating any state twice",
      "Updating only terminal states",
    ],
    answer: 1,
    explain: "Asynchronous DP can prioritize states expected to change substantially, propagating information efficiently. This idea is developed into prioritized sweeping in Chapter 8.",
  },
  {
    q: "If the model p is only approximate, DP will converge to...",
    options: [
      "The true v*",
      "The optimal value function of the APPROXIMATE model, which may differ from the true optimum",
      "A random function",
      "Zero",
    ],
    answer: 1,
    explain: "DP is only as good as its model. With an inaccurate model, it solves the wrong MDP, converging to that model's optimum. Model errors thus directly bias the result — a key limitation.",
  },
  {
    q: "Why is DP called a 'bootstrapping' method while Monte Carlo is not?",
    options: [
      "DP uses random returns",
      "DP updates estimates from other estimates (successor values); MC updates from complete actual returns",
      "MC uses a model",
      "They are the same",
    ],
    answer: 1,
    explain: "Bootstrapping = updating estimates from estimates. DP (and TD) bootstrap via successor value estimates; Monte Carlo uses full sampled returns and does not bootstrap.",
  },
  {
    q: "The convergence rate of value iteration depends strongly on...",
    options: [
      "The random seed",
      "The discount factor γ (values closer to 1 converge more slowly)",
      "The number of episodes",
      "The exploration rate",
    ],
    answer: 1,
    explain: "The contraction factor is γ, so error shrinks by a factor of γ per sweep. As γ→1, convergence slows dramatically because long horizons take many sweeps to propagate.",
  },
  {
    q: "A key conceptual message of Chapter 4 is that all DP methods can be understood as instances of...",
    options: [
      "Supervised learning",
      "Generalized Policy Iteration (interacting evaluation and improvement)",
      "Monte Carlo sampling",
      "Gradient descent",
    ],
    answer: 1,
    explain: "Policy iteration, value iteration, and asynchronous DP are all realizations of GPI: evaluation and improvement processes interacting to reach the optimal policy and value function.",
  },
  {
    q: "DP's use of full-width (expected) updates means each update's computational cost per state is proportional to...",
    options: [
      "1 (constant)",
      "The number of possible successor states/actions considered",
      "The number of episodes",
      "The discount factor",
    ],
    answer: 1,
    explain: "An expected update sums over all actions and all possible next states/rewards, so its cost scales with the branching (number of successors and actions) — more expensive per state than a sample update, but exact.",
  },
  {
    q: "Which method would you use to compute v_π for a KNOWN policy in a KNOWN small MDP exactly?",
    options: [
      "Monte Carlo control",
      "Iterative policy evaluation (or solving the linear Bellman system directly)",
      "Q-learning",
      "REINFORCE",
    ],
    answer: 1,
    explain: "With a known model and policy, iterative policy evaluation (or directly solving the linear Bellman equations) computes v_π. Model-free methods like MC/Q-learning are for when the model is unavailable.",
  },
  {
    q: "In-place asynchronous value iteration can converge faster than the two-array version because...",
    options: [
      "It uses less accurate values",
      "It immediately uses newly updated values within the same sweep, propagating information more quickly",
      "It skips the max operation",
      "It ignores γ",
    ],
    answer: 1,
    explain: "By overwriting values in place, later updates in a sweep benefit from earlier updates, so information propagates within a sweep — often speeding convergence relative to using a full previous-sweep copy.",
  },
  {
    q: "The overall role of Chapter 4 (DP) in the book is to...",
    options: [
      "Provide a practical algorithm for huge problems",
      "Establish the theoretical foundation and exact algorithms that later model-free/approximate methods imitate without a model",
      "Replace all later chapters",
      "Introduce neural networks",
    ],
    answer: 1,
    explain: "DP gives the exact, model-based benchmark. Monte Carlo, TD, and function-approximation methods can be seen as ways to achieve DP-like results using sampled experience and less computation.",
  },
  {
    q: "Which is TRUE about the memory requirement of tabular DP?",
    options: [
      "Constant regardless of problem size",
      "It stores a value for every state (and possibly every state–action pair), so memory scales with the state set",
      "It stores only the reward function",
      "It needs no storage",
    ],
    answer: 1,
    explain: "Tabular DP keeps a table of values indexed by state (or state–action), so its memory grows with |S| (or |S|·|A|) — another reason large problems require function approximation.",
  }
);
