// ============================================================================
//  data-09-b.js — Chapter 09 (On-policy Prediction with Approximation) pool
// ============================================================================
QUESTIONS["09"].push(
  {
    q: "In value-function approximation, the value estimate v̂(s,w) is a function of...",
    options: [
      "a table entry per state",
      "a weight vector w with far fewer components than the number of states",
      "the reward only",
      "the discount factor",
    ],
    answer: 1,
    explain: "Approximation represents the value function with a parameter vector w (|w| ≪ |S|). Changing w to fit one state affects many others — this generalization is what makes large/continuous problems tractable.",
  },
  {
    q: "Generalization in function approximation means that...",
    options: [
      "each state is updated independently",
      "updating the estimate for one state changes the estimates for other (similar) states",
      "the model is learned",
      "exploration increases",
    ],
    answer: 1,
    explain: "Because states share parameters/features, an update from one state generalizes to others. This is powerful (learn from few states) but also why tabular guarantees don't automatically carry over.",
  },
  {
    q: "The prediction objective VE(w) = Σ_s μ(s)[v_π(s) − v̂(s,w)]² weights state errors by...",
    options: [
      "uniform weights",
      "the on-policy distribution μ(s) — how much time the policy spends in each state",
      "the reward magnitude",
      "the number of actions",
    ],
    answer: 1,
    explain: "The Mean Squared Value Error weights each state's squared error by μ(s), the fraction of time spent there under π. Accuracy is prioritized where the agent actually is.",
  },
  {
    q: "Stochastic gradient descent updates w by moving it...",
    options: [
      "in the direction of the gradient of the error",
      "a small step in the direction that reduces the (sampled) error, i.e., opposite the gradient",
      "randomly",
      "toward zero",
    ],
    answer: 1,
    explain: "SGD adjusts w by −½α∇[error²] = α[target − v̂(s,w)]∇v̂(s,w), nudging the estimate toward the target on each example. It converges (for appropriate α) to a local optimum of the error.",
  },
  {
    q: "A 'semi-gradient' TD method is called that because it...",
    options: [
      "uses half the features",
      "includes the gradient of v̂ but ignores the effect of w on the bootstrapped target",
      "uses a decreasing step size",
      "is exact",
    ],
    answer: 1,
    explain: "Semi-gradient TD updates toward a target like R+γv̂(S',w) but does NOT differentiate that target w.r.t. w. It ignores part of the gradient, so it isn't a true gradient method — but it learns fast and works online.",
  },
  {
    q: "Gradient Monte Carlo (using the return G_t as target) is a TRUE gradient method because...",
    options: [
      "the target G_t does not depend on w",
      "it uses a model",
      "it bootstraps",
      "it has no target",
    ],
    answer: 0,
    explain: "The Monte Carlo target G_t is an unbiased sample of v_π(s) independent of w, so the update is a genuine SGD step on VE and converges to a local optimum. Bootstrapped targets (TD) depend on w, breaking this.",
  },
  {
    q: "Linear function approximation represents v̂(s,w) as...",
    options: [
      "a lookup table",
      "wᵀx(s), the inner product of weights with a feature vector x(s)",
      "a deep network",
      "max over features",
    ],
    answer: 1,
    explain: "Linear methods use v̂(s,w) = Σ_i w_i x_i(s) = wᵀx(s). The gradient ∇v̂ = x(s) is simply the feature vector, making updates cheap and enabling strong convergence theory.",
  },
  {
    q: "For linear semi-gradient TD(0) (on-policy), the weights converge to the TD fixed point w_TD, whose error satisfies...",
    options: [
      "VE(w_TD) = 0",
      "VE(w_TD) ≤ [1/(1−γ)] · min_w VE(w)",
      "VE(w_TD) = ∞",
      "no bound",
    ],
    answer: 1,
    explain: "The asymptotic error of linear semi-gradient TD is bounded by 1/(1−γ) times the best possible (minimum) VE. Bootstrapping can inflate error versus the best approximation, but on-policy it stays bounded and stable.",
  },
  {
    q: "State aggregation is a special case of linear approximation in which...",
    options: [
      "each state has its own weight",
      "states are grouped and all states in a group share one estimated value (one-hot group features)",
      "features are polynomials",
      "there are no features",
    ],
    answer: 1,
    explain: "State aggregation partitions states into groups; the feature vector is one-hot over groups, so each group has a single value. It's the simplest generalizing linear approximation (e.g., the 1000-state random walk).",
  },
  {
    q: "Polynomial features can represent interactions between state dimensions but...",
    options: [
      "always generalize well",
      "can generalize poorly and scale badly (feature count grows fast with dimension and order)",
      "require a model",
      "are nonlinear methods",
    ],
    answer: 1,
    explain: "Polynomial bases capture interactions but their number explodes with the number of dimensions and the polynomial order, and they can extrapolate poorly — so they're often outperformed by Fourier or coarse-coding features.",
  },
  {
    q: "The Fourier basis represents value functions using...",
    options: [
      "random features",
      "cosine functions of (weighted sums of) the state variables",
      "one-hot indicators",
      "polynomials only",
    ],
    answer: 1,
    explain: "The Fourier basis uses cosine features cos(π cⁱ·s) with integer coefficient vectors cⁱ. It is simple to use, often performs very well on continuous problems, and needs no manual feature placement.",
  },
  {
    q: "Coarse coding represents a state by...",
    options: [
      "a single feature",
      "which of many overlapping receptive fields (features) it falls within — a binary vector of active features",
      "the reward",
      "a polynomial",
    ],
    answer: 1,
    explain: "Coarse coding uses overlapping features (e.g., circles) that are 1 if the state is inside them. The pattern of active features encodes the state; overlap controls generalization breadth.",
  },
  {
    q: "In coarse coding, using BROADER features (larger receptive fields) leads to...",
    options: [
      "finer resolution, slower generalization",
      "broader generalization (faster early learning) but a coarser limit on final resolution",
      "no generalization",
      "exact tabular behavior",
    ],
    answer: 1,
    explain: "Feature width controls the breadth of generalization: broad features generalize widely (fast early learning) but blur fine detail; the number of features determines the ultimate achievable resolution.",
  },
  {
    q: "Tile coding is a form of coarse coding that...",
    options: [
      "uses a single grid",
      "overlays multiple offset tilings so each state activates exactly one tile per tiling, giving a sparse binary feature vector",
      "requires a neural network",
      "cannot handle continuous states",
    ],
    answer: 1,
    explain: "Tile coding partitions the space with several offset tilings. A state activates one tile per tiling; the union of active tiles is the feature vector. It is efficient, has a known number of active features, and gives tunable generalization.",
  },
  {
    q: "A computational advantage of tile coding is that the number of ACTIVE features per state is...",
    options: [
      "equal to the total number of tiles",
      "exactly the number of tilings (constant and small), making updates fast",
      "zero",
      "unbounded",
    ],
    answer: 1,
    explain: "Because a state lands in one tile per tiling, exactly (number of tilings) features are active — a small constant. This sparsity makes computing v̂ and its updates very fast.",
  },
  {
    q: "Radial basis functions (RBFs) generalize coarse coding by...",
    options: [
      "using binary features",
      "producing features in [0,1] that vary continuously with distance from a center (e.g., Gaussians)",
      "requiring a model",
      "using polynomials",
    ],
    answer: 1,
    explain: "RBF features respond in a graded (continuous) way based on distance to prototype centers, unlike the 0/1 features of tile coding. They give smooth approximations but add computational cost and tuning.",
  },
  {
    q: "The step-size rule α = 1/(τ · E[xᵀx]) for linear methods is designed so that learning...",
    options: [
      "diverges",
      "roughly averages over about τ experiences (a rule of thumb for setting α)",
      "ignores features",
      "stops immediately",
    ],
    answer: 1,
    explain: "Setting α = 1/(τ E[xᵀx]) makes an update behave like averaging over ~τ recent examples with similar features, a practical heuristic. For tile coding with m active features, α = 1/(τm) is common.",
  },
  {
    q: "Why is the Monte Carlo (gradient) target attractive for convergence guarantees but often slower in practice?",
    options: [
      "It bootstraps",
      "It is an unbiased SGD target (nice guarantees) but has high variance and needs complete returns, slowing learning",
      "It requires a model",
      "It ignores features",
    ],
    answer: 1,
    explain: "Gradient MC is unbiased and a true SGD method (good theory), but full returns are high-variance and only available at episode end, so semi-gradient TD often learns faster despite weaker guarantees.",
  },
  {
    q: "Least-Squares TD (LSTD) computes the TD fixed point by...",
    options: [
      "stochastic gradient descent",
      "directly forming and solving the linear system for w_TD from accumulated statistics (data-efficient but O(d²) per step)",
      "Monte Carlo sampling",
      "ignoring features",
    ],
    answer: 1,
    explain: "LSTD accumulates matrices/vectors and solves for the TD fixed point directly, using data very efficiently. Its cost is O(d²) per step (d = number of features), versus O(d) for incremental semi-gradient TD.",
  },
  {
    q: "Artificial neural networks provide function approximation that is...",
    options: [
      "always linear",
      "nonlinear, learning their own features via multiple layers, at the cost of nonconvex optimization and weaker guarantees",
      "tabular",
      "model-based",
    ],
    answer: 1,
    explain: "ANNs are nonlinear approximators that learn hierarchical features. They are powerful (e.g., deep RL) but training is nonconvex, so the strong linear-case guarantees no longer hold.",
  },
  {
    q: "Memory-based (nonparametric) methods like kernel regression differ from parametric methods by...",
    options: [
      "storing a fixed weight vector",
      "storing training examples and computing estimates locally from nearby examples at query time",
      "using a model",
      "having no data",
    ],
    answer: 1,
    explain: "Memory-based methods keep the examples themselves and answer queries using nearby stored experiences (e.g., weighted by a kernel). They are lazy learners: no fixed parameter vector, computation deferred to query time.",
  },
  {
    q: "The 'interest' and 'emphasis' variables (introduced for emphatic methods) allow the agent to...",
    options: [
      "ignore all states",
      "weight how much it cares about accurately valuing particular states, redistributing update emphasis",
      "remove the reward",
      "change the discount",
    ],
    answer: 1,
    explain: "Interest specifies how much we care about each state's value; emphasis (accumulated from interest) scales updates accordingly. This generalizes the uniform on-policy weighting and underlies emphatic-TD stability (Ch. 11).",
  },
  {
    q: "Why don't tabular convergence guarantees automatically transfer to function approximation?",
    options: [
      "Tables are nonlinear",
      "Because updates generalize across states, a bootstrapped update can interfere with other states' estimates, potentially causing instability (esp. off-policy)",
      "Rewards change",
      "Features are exact",
    ],
    answer: 1,
    explain: "With shared parameters, improving one state's estimate can worsen others'. Combined with bootstrapping and off-policy training this can diverge (the deadly triad). On-policy linear semi-gradient TD, however, remains stable.",
  },
  {
    q: "The gradient of a LINEAR value function v̂(s,w)=wᵀx(s) with respect to w is...",
    options: ["0", "x(s), the feature vector", "w", "the reward"],
    answer: 1,
    explain: "For linear approximation, ∇_w v̂(s,w) = x(s). This makes the semi-gradient TD update w ← w + αδ x(s) especially simple and is why linear methods are analytically tractable.",
  },
  {
    q: "On-policy distribution μ under semi-gradient TD is important because...",
    options: [
      "it is uniform",
      "TD's stability guarantee holds under the on-policy state distribution; using a different distribution (off-policy) can break it",
      "it equals the reward",
      "it removes bootstrapping",
    ],
    answer: 1,
    explain: "Linear semi-gradient TD is guaranteed stable when updates follow the on-policy distribution μ. Training off-policy (a different distribution) with bootstrapping is where divergence can occur (the deadly triad).",
  },
  {
    q: "Coarse/tile coding features are examples of features that are...",
    options: [
      "dense and continuous",
      "sparse and binary (few active at a time), enabling fast, local generalization",
      "polynomial",
      "learned by a network",
    ],
    answer: 1,
    explain: "Tile/coarse coding produce sparse binary feature vectors (only a few 1s). Sparsity gives fast computation and localized generalization, which often works well for low-dimensional continuous control problems.",
  },
  {
    q: "The number of features primarily controls the ___, while feature width controls the ___.",
    options: [
      "generalization; resolution",
      "final resolution/capacity; breadth of generalization",
      "reward; discount",
      "policy; value",
    ],
    answer: 1,
    explain: "More features → finer ultimate resolution (capacity); wider features → broader generalization (faster early learning, coarser detail). Together they trade off learning speed against asymptotic accuracy.",
  },
  {
    q: "Semi-gradient TD(0) with a good linear representation typically...",
    options: [
      "diverges on-policy",
      "learns faster than gradient MC and converges (on-policy) to a bounded-error TD fixed point",
      "requires a model",
      "cannot generalize",
    ],
    answer: 1,
    explain: "On-policy semi-gradient TD(0) usually learns faster than gradient MC (lower variance, online) and converges to the TD fixed point with error bounded relative to the best approximation.",
  },
  {
    q: "A drawback of state aggregation is that within a group...",
    options: [
      "values vary smoothly",
      "all states are forced to share one value, so it cannot distinguish states in the same group",
      "the model is required",
      "features are dense",
    ],
    answer: 1,
    explain: "Because a whole group shares one value, aggregation cannot represent value differences within a group — a coarse approximation. Finer groupings improve resolution at the cost of less generalization.",
  },
  {
    q: "For the 1000-state random walk, state aggregation into 10 groups produces a value estimate that is...",
    options: [
      "exact",
      "a staircase (piecewise-constant) approximation of the smooth true value function",
      "random",
      "identical to tabular",
    ],
    answer: 1,
    explain: "With 10 groups of 100 states, the learned value is constant within each group, yielding a staircase approximation to the true (nearly linear) value function — illustrating aggregation's coarse but useful generalization.",
  },
  {
    q: "The objective actually optimized by semi-gradient TD is NOT exactly VE; instead it relates to...",
    options: [
      "the reward",
      "the (projected) Bellman error / TD fixed point, which differs from the minimum-VE solution",
      "the policy gradient",
      "the model likelihood",
    ],
    answer: 1,
    explain: "Semi-gradient TD converges to the TD fixed point (minimizing a projected Bellman error surrogate), not the minimum-VE point. This distinction is developed formally in Chapter 11.",
  },
  {
    q: "Which is an advantage of tile coding's hashing variant?",
    options: [
      "It removes generalization",
      "Hashing maps a huge (possibly high-dimensional) tiling space into a manageable, fixed-size feature vector, controlling memory",
      "It requires a model",
      "It makes features dense",
    ],
    answer: 1,
    explain: "Hashing consistently maps the astronomically many possible tiles into a bounded table of features, controlling memory in high dimensions (with occasional collisions), while retaining tile coding's speed and sparsity.",
  },
  {
    q: "Why is the choice of features often described as the most important design decision in linear RL?",
    options: [
      "Features set the discount",
      "The representation (features) determines what value functions can be represented and how learning generalizes — quality of features caps achievable performance",
      "Features are the reward",
      "Features choose the policy",
    ],
    answer: 1,
    explain: "In linear methods, the features define the hypothesis space and generalization behavior. Good features can make a problem easy; poor ones limit accuracy regardless of learning algorithm — hence feature construction's importance.",
  },
  {
    q: "Nonlinear ANNs are attractive for RL because they...",
    options: [
      "require hand-designed features",
      "learn useful features automatically from raw inputs (e.g., pixels), enabling end-to-end deep RL",
      "guarantee convergence",
      "avoid bootstrapping",
    ],
    answer: 1,
    explain: "Deep networks learn representations directly from high-dimensional inputs, removing the need for hand-crafted features — the basis of deep RL systems like DQN, at the cost of nonconvex, less-guaranteed training.",
  },
  {
    q: "The prediction problem with approximation is fundamentally harder than tabular prediction because...",
    options: [
      "there are fewer states",
      "with limited parameters you generally cannot make every state's value exactly correct — you must trade off errors across states",
      "there is no reward",
      "bootstrapping is impossible",
    ],
    answer: 1,
    explain: "Finite parameters can't represent every state exactly, so learning must distribute (and trade off) approximation error across states — which is why the weighted VE objective and the on-policy distribution matter.",
  },
  {
    q: "Which statement about gradient MC vs. semi-gradient TD convergence is correct?",
    options: [
      "Both are true gradient methods",
      "Gradient MC is a true SGD method converging to a VE local optimum; semi-gradient TD converges to the (different) TD fixed point",
      "Neither converges",
      "They converge to the same point always",
    ],
    answer: 1,
    explain: "Gradient MC genuinely descends VE (converging to a local optimum of VE). Semi-gradient TD is not a true gradient method and converges instead to the TD fixed point, generally a different solution.",
  },
  {
    q: "In continuous-state control, tile coding is popular because it...",
    options: [
      "requires a model",
      "is fast, sparse, and gives controllable generalization, working well with semi-gradient Sarsa (e.g., Mountain Car)",
      "cannot represent value functions",
      "needs deep networks",
    ],
    answer: 1,
    explain: "Tile coding's speed, sparsity, and tunable generalization make it a go-to representation for classic continuous control (like Mountain Car with semi-gradient Sarsa), before neural networks are necessary.",
  },
  {
    q: "The role of the projection operator (introduced conceptually here, formalized in Ch. 11) is to...",
    options: [
      "remove features",
      "map an arbitrary value function onto the nearest representable one in the approximation space (under the μ-weighted norm)",
      "increase the reward",
      "select actions",
    ],
    answer: 1,
    explain: "The projection maps a target value function (e.g., the Bellman update of v̂) back into the space of representable functions. Semi-gradient TD's fixed point is where the projected Bellman update equals v̂.",
  },
  {
    q: "Which is TRUE about on-policy linear prediction stability?",
    options: [
      "It can diverge",
      "On-policy linear semi-gradient TD(0) is stable and converges to a bounded-error solution (no deadly triad, since it's on-policy)",
      "It requires exploring starts",
      "It needs a model",
    ],
    answer: 1,
    explain: "On-policy linear semi-gradient TD(0) is provably stable and convergent to the TD fixed point. Instability (the deadly triad) requires off-policy training combined with bootstrapping and approximation (Ch. 11).",
  },
  {
    q: "The overall message of Chapter 9 is that on-policy prediction with approximation...",
    options: [
      "is impossible",
      "extends tabular prediction using parameterized value functions and SGD/semi-gradient updates, with feature construction (tile coding, Fourier, etc.) being crucial",
      "requires a distribution model",
      "abandons value functions",
    ],
    answer: 1,
    explain: "Chapter 9 generalizes prediction to parameterized value functions, introduces the VE objective and (semi-)gradient methods, analyzes the linear case and TD fixed point, and emphasizes feature construction techniques.",
  }
);
