// ============================================================================
//  data-03-b.js — Chapter 03 (Finite MDPs) expansion pool
// ============================================================================
QUESTIONS["03"].push(
  {
    q: "The four-argument dynamics function p(s',r | s,a) gives...",
    options: [
      "The policy's action probabilities",
      "The probability of transitioning to state s' with reward r, given state s and action a",
      "The value of state s",
      "The discounted return",
    ],
    answer: 1,
    explain: "p(s',r|s,a) = Pr{S_t=s', R_t=r | S_{t−1}=s, A_{t−1}=a} completely specifies a finite MDP's dynamics. Everything else (state-transition probabilities, expected rewards) can be derived from it.",
  },
  {
    q: "Because p defines a probability distribution, for each (s,a) the sum over all s' and r of p(s',r|s,a) equals...",
    options: ["0", "1", "γ", "the reward"],
    answer: 1,
    explain: "For each state–action pair, p(s',r|s,a) sums to 1 over all next states and rewards, since it is a proper probability distribution over outcomes.",
  },
  {
    q: "The agent–environment boundary represents the limit of the agent's...",
    options: [
      "knowledge",
      "absolute control (not its knowledge)",
      "reward",
      "memory",
    ],
    answer: 1,
    explain: "The boundary is drawn at the limit of the agent's absolute control, not its knowledge. The agent may know a lot about the environment (even reward computation) yet still not control it, so it is 'outside.'",
  },
  {
    q: "In an episodic task, interaction breaks into episodes that each end in a special...",
    options: ["Start state", "Terminal state", "Reward state", "Absorbing action"],
    answer: 1,
    explain: "Episodic tasks have a terminal state ending each episode (e.g., end of a game), after which the environment resets. Continuing tasks go on without terminal states.",
  },
  {
    q: "The discounted return is G_t = R_{t+1} + γR_{t+2} + γ²R_{t+3} + …. For γ < 1 and bounded rewards, this sum is...",
    options: ["Infinite", "Finite", "Zero", "Negative"],
    answer: 1,
    explain: "With 0 ≤ γ < 1 and bounded rewards, the geometric weighting makes the infinite sum finite, which is essential for continuing tasks where there is no terminal time.",
  },
  {
    q: "The recursive relationship among returns is G_t = ...",
    options: [
      "R_{t+1} − γG_{t+1}",
      "R_{t+1} + γG_{t+1}",
      "γR_{t+1} + G_{t+1}",
      "R_{t+1} · G_{t+1}",
    ],
    answer: 1,
    explain: "G_t = R_{t+1} + γG_{t+1} is the key recursion: today's return is the next reward plus the discounted return from the next step. It underlies the Bellman equations.",
  },
  {
    q: "If γ = 1 in a continuing task, the (undiscounted) return can be...",
    options: [
      "Always finite",
      "Infinite, which is why discounting (or the average-reward formulation) is used",
      "Zero",
      "Negative only",
    ],
    answer: 1,
    explain: "With γ=1 and no terminal state, the sum of rewards can diverge. Discounting (γ<1) or the average-reward setting keeps the objective well-defined for continuing tasks.",
  },
  {
    q: "The unified notation for episodic and continuing tasks treats episode termination as entering a(n)...",
    options: [
      "Random state",
      "Absorbing state that transitions only to itself with reward 0",
      "New episode immediately",
      "Optimal state",
    ],
    answer: 1,
    explain: "By modeling the terminal state as an absorbing state (self-loop, zero reward), the same discounted-return formula covers both episodic and continuing tasks with one notation.",
  },
  {
    q: "The action-value function q_π(s,a) is the expected return after...",
    options: [
      "Following π from s",
      "Taking action a in state s and thereafter following π",
      "Taking the greedy action forever",
      "Reaching a terminal state",
    ],
    answer: 1,
    explain: "q_π(s,a) = E_π[G_t | S_t=s, A_t=a]: the expected return starting in s, taking a first, then following policy π. It is the value of a specific action in a state.",
  },
  {
    q: "The relationship v_π(s) = Σ_a π(a|s) q_π(s,a) says that a state's value is...",
    options: [
      "The maximum action value",
      "The policy-weighted average of the action values in that state",
      "The reward in that state",
      "Independent of the policy",
    ],
    answer: 1,
    explain: "Under policy π, the state value is the expectation of the action values over the actions π chooses: v_π(s) = Σ_a π(a|s) q_π(s,a).",
  },
  {
    q: "A backup diagram depicts...",
    options: [
      "The reward function",
      "The relationships (transitions and actions) used to update/back up value estimates",
      "The neural network architecture",
      "The exploration policy",
    ],
    answer: 1,
    explain: "Backup diagrams show how value information flows from successor states/actions back to a state or state–action node — the structure of an update. Open circles are states; solid circles are actions.",
  },
  {
    q: "The Bellman equation for v_π is v_π(s) = Σ_a π(a|s) Σ_{s',r} p(s',r|s,a)[ __ ].",
    options: [
      "r",
      "r + γ v_π(s')",
      "γ v_π(s')",
      "max_a q_π(s,a)",
    ],
    answer: 1,
    explain: "The bracket is r + γ v_π(s'): the immediate reward plus the discounted value of the successor state. Averaging over actions (via π) and outcomes (via p) gives v_π(s).",
  },
  {
    q: "A policy π* is optimal if and only if its value function equals...",
    options: [
      "Zero everywhere",
      "v*, the maximum over policies of v_π(s) for all s",
      "The reward function",
      "q_π for some other policy",
    ],
    answer: 1,
    explain: "Optimal policies share the optimal state-value function v*(s) = max_π v_π(s) (and optimal action-value q*). Any policy achieving v* is optimal.",
  },
  {
    q: "The Bellman optimality equation for v* is v*(s) = max_a Σ_{s',r} p(s',r|s,a)[ __ ].",
    options: [
      "r",
      "r + γ v*(s')",
      "γ q*(s',a')",
      "v_π(s')",
    ],
    answer: 1,
    explain: "v*(s) = max_a Σ p(s',r|s,a)[r + γ v*(s')]. Unlike v_π's equation, it maximizes over actions rather than averaging under a policy — expressing that optimal value picks the best action.",
  },
  {
    q: "The Bellman optimality equation for q* is q*(s,a) = Σ_{s',r} p(s',r|s,a)[r + γ · __ ].",
    options: [
      "q*(s',a)",
      "max_{a'} q*(s',a')",
      "Σ_{a'} q*(s',a')",
      "v_π(s')",
    ],
    answer: 1,
    explain: "q*(s,a) = E[R_{t+1} + γ max_{a'} q*(S_{t+1},a')]. The max over next actions appears inside because after the first action a, optimal behavior selects the best next action.",
  },
  {
    q: "One reason the Bellman optimality equation is not always directly solvable in practice is that it...",
    options: [
      "Is nonlinear (due to the max) and requires knowing the dynamics, with computation infeasible for large state spaces",
      "Has no solution",
      "Requires a supervisor",
      "Ignores rewards",
    ],
    answer: 0,
    explain: "The optimality equations are a nonlinear system (because of the max) and solving them exactly needs the full dynamics plus enough compute and memory — infeasible for large problems, motivating approximate/learning methods.",
  },
  {
    q: "Given v*, a one-step greedy policy (act greedily w.r.t. v*) is...",
    options: [
      "Suboptimal",
      "Optimal — greedy action selection with respect to v* yields an optimal policy",
      "Random",
      "Undefined",
    ],
    answer: 1,
    explain: "Because v* already accounts for the long-run consequences of actions, acting greedily (one step) with respect to it is optimal. With v* you still need the model to look ahead; with q* you don't.",
  },
  {
    q: "Why is having q* especially convenient compared to having v*?",
    options: [
      "q* is smaller to store",
      "With q* the agent can choose optimal actions without any model or one-step lookahead — just argmax_a q*(s,a)",
      "q* needs the reward function",
      "q* is always deterministic",
    ],
    answer: 1,
    explain: "q*(s,a) caches the value of each action, so optimal action selection is argmax_a q*(s,a) — no environment model or lookahead search required, unlike acting from v*.",
  },
  {
    q: "The state signal is said to have the Markov property if it...",
    options: [
      "Contains the full raw sensory history",
      "Summarizes past sensations so that all relevant information for predicting the future is retained",
      "Is always low-dimensional",
      "Ignores rewards",
    ],
    answer: 1,
    explain: "A Markov state need not include all history, but it must retain everything relevant: the future depends on the past only through the current state. The MDP framework assumes this property.",
  },
  {
    q: "The expected reward for a state–action pair, r(s,a), is computed as...",
    options: [
      "The single last reward",
      "Σ_r r Σ_{s'} p(s',r|s,a) — the reward averaged over outcomes",
      "The maximum reward",
      "Always 1",
    ],
    answer: 1,
    explain: "r(s,a) = E[R_t | S_{t−1}=s, A_{t−1}=a] = Σ_r r Σ_{s'} p(s',r|s,a), the expected immediate reward marginalized over next states and reward values.",
  },
  {
    q: "A reward of +1 for each time step until escape (and 0 on escape) in an episodic task encourages the agent to...",
    options: [
      "Take as long as possible",
      "Escape as quickly as possible (maximize count of +1s is actually maximized by... consider carefully)",
      "Escape as quickly as possible when reward is −1 per step",
      "Ignore time",
    ],
    answer: 2,
    explain: "To encourage fast escape you reward −1 per step (so fewer steps = higher return). Rewarding +1 per step would incentivize delaying escape. This shows reward sign must match the intended goal.",
  },
  {
    q: "Discounting with γ closer to 1 makes the agent...",
    options: [
      "More myopic",
      "More far-sighted, valuing long-term rewards more strongly",
      "Ignore rewards",
      "Deterministic",
    ],
    answer: 1,
    explain: "Larger γ weights future rewards more, making the agent far-sighted. Smaller γ makes it myopic, focusing on near-term reward.",
  },
  {
    q: "In the MDP framework, the reward R_{t+1} for action A_t at S_t is delivered...",
    options: [
      "At the same time step t",
      "At the next time step, together with the next state S_{t+1}",
      "Only at episode end",
      "Never",
    ],
    answer: 1,
    explain: "The convention pairs the reward with the resulting next state: taking A_t in S_t yields R_{t+1} and S_{t+1} at the next step. This indexing keeps the return recursion clean.",
  },
  {
    q: "Which is a valid way to place the agent–environment boundary for a person riding a bicycle?",
    options: [
      "The agent includes the road",
      "The agent is the decision-making process; muscles, skeleton, and bicycle can be treated as part of the environment",
      "The agent includes other cyclists' brains",
      "There is no boundary",
    ],
    answer: 1,
    explain: "The boundary is a modeling choice at the limit of control. It is legitimate to treat the body's mechanics and the bicycle as environment, with only the decision process as the agent.",
  },
  {
    q: "The Bellman equation for v_π constitutes a system of equations that (for a finite MDP with known dynamics) is...",
    options: [
      "Nonlinear and unsolvable",
      "Linear in the unknowns v_π(s), and has a unique solution",
      "Independent of π",
      "Only approximate",
    ],
    answer: 1,
    explain: "For a fixed policy the Bellman equations are linear in the state values and have a unique solution v_π — solvable directly (or by iterative policy evaluation). The optimality equations, with a max, are nonlinear.",
  },
  {
    q: "Which correctly distinguishes v_π and v*?",
    options: [
      "v_π averages actions under π; v* takes the best action (max)",
      "They are always equal",
      "v* averages under π; v_π takes the max",
      "Neither depends on actions",
    ],
    answer: 0,
    explain: "v_π(s) uses the policy-weighted average of action outcomes, whereas v*(s) uses the maximum over actions. v* ≥ v_π for all states, with equality only when π is optimal.",
  },
  {
    q: "In many MDPs there can be more than one optimal policy. What do all optimal policies necessarily share?",
    options: [
      "The same action in every state",
      "The same optimal value functions v* and q*",
      "The same random seed",
      "The same reward function only",
    ],
    answer: 1,
    explain: "There may be multiple optimal policies (e.g., ties between equally good actions), but they all achieve the same optimal value functions v* and q*.",
  },
  {
    q: "The 'expected update' in DP (used to define the Bellman equations) considers...",
    options: [
      "One sampled successor",
      "All possible successor states and rewards, weighted by their probabilities",
      "Only the greedy successor",
      "No successors",
    ],
    answer: 1,
    explain: "Expected (full) updates average over all possible next states and rewards using the model p. This contrasts with sample updates (Monte Carlo/TD) that use a single sampled successor.",
  },
  {
    q: "Which is TRUE about the reward signal's placement relative to the agent?",
    options: [
      "The reward source is inside the agent and freely adjustable by it",
      "The reward source is always considered part of the environment, even if it is computed 'inside' a physical body",
      "Rewards come from the value function",
      "Rewards are chosen by the policy",
    ],
    answer: 1,
    explain: "The reward computation is defined to be part of the environment (outside the agent's arbitrary control), so the agent cannot simply set its own rewards — otherwise maximizing reward would be trivial and meaningless.",
  },
  {
    q: "For a continuing task, the average reward per step used as an alternative objective is defined (informally) as...",
    options: [
      "The last reward",
      "The long-run average of the reward per time step under the policy",
      "The maximum reward",
      "The discounted return",
    ],
    answer: 1,
    explain: "The average-reward criterion (developed more fully in Ch. 10) maximizes the long-run average reward per step, an alternative to discounting for continuing tasks.",
  },
  {
    q: "The state-transition probability p(s'|s,a) is obtained from p(s',r|s,a) by...",
    options: [
      "Taking the max over r",
      "Summing over all rewards r",
      "Multiplying by γ",
      "Ignoring s'",
    ],
    answer: 1,
    explain: "p(s'|s,a) = Σ_r p(s',r|s,a): marginalize out the reward to get the pure state-transition probability. The dynamics function contains both transition and reward information.",
  },
  {
    q: "Why does the book emphasize that the MDP formulation, despite its simplicity, is broadly applicable?",
    options: [
      "Because it requires no reward",
      "Because states, actions, and rewards can be defined flexibly to model a huge range of goal-directed problems",
      "Because it only models games",
      "Because it forbids stochasticity",
    ],
    answer: 1,
    explain: "The three signals (state, action, reward) are abstract and flexible: time steps need not be fixed intervals, actions can be high or low level, and states can be abstract — letting MDPs model very diverse problems.",
  },
  {
    q: "If a problem's 'state' fails the Markov property, one common remedy is to...",
    options: [
      "Remove the reward",
      "Augment the state (e.g., include more history) so that it becomes (approximately) Markov",
      "Increase γ to 1",
      "Use a deterministic policy",
    ],
    answer: 1,
    explain: "When the immediate observation is non-Markov, adding relevant history/features to form a richer state can restore (or approximate) the Markov property, making MDP methods applicable.",
  },
  {
    q: "The value of a terminal state is defined to be...",
    options: ["Undefined", "Zero", "The maximum reward", "One"],
    answer: 1,
    explain: "Terminal states have value 0 by convention (no future reward). This makes returns and Bellman updates behave correctly at the ends of episodes.",
  },
  {
    q: "Which statement about optimal policies and the Bellman optimality equation is correct?",
    options: [
      "Optimal policies violate the optimality equation",
      "The optimality equation's solution v* corresponds to any policy that is greedy with respect to it, and such a policy is optimal",
      "The optimality equation has no relation to policies",
      "Only stochastic policies can be optimal",
    ],
    answer: 1,
    explain: "Solving the Bellman optimality equation yields v* (or q*); a policy greedy with respect to v*/q* is optimal. For finite MDPs an optimal deterministic policy always exists.",
  },
  {
    q: "The discount factor γ is typically restricted to the range...",
    options: ["γ < 0", "0 ≤ γ ≤ 1", "γ > 1", "γ = 2"],
    answer: 1,
    explain: "γ lies in [0,1]. γ=0 gives a myopic agent; γ→1 gives a far-sighted one. For continuing tasks γ<1 keeps the return finite.",
  },
  {
    q: "A key insight of the return recursion G_t = R_{t+1} + γG_{t+1} is that it enables value functions to satisfy...",
    options: [
      "A supervised loss",
      "Recursive (Bellman) consistency conditions relating a state's value to successor values",
      "The law of large numbers only",
      "No useful structure",
    ],
    answer: 1,
    explain: "Because returns are recursive, expected returns (values) satisfy recursive Bellman equations linking each state's value to its successors' — the backbone of DP, TD, and most RL methods.",
  },
  {
    q: "Which of the following is NOT part of the standard finite-MDP tuple?",
    options: [
      "A set of states",
      "A set of actions",
      "A dynamics function p and a discount γ",
      "A labeled training set of correct actions",
    ],
    answer: 3,
    explain: "An MDP is defined by states, actions, the dynamics p(s',r|s,a), and (for the objective) a discount γ. There is no labeled set of correct actions — that would be supervised learning.",
  },
  {
    q: "Expected reward for a full transition, r(s,a,s'), differs from r(s,a) in that it...",
    options: [
      "Ignores the action",
      "Conditions additionally on the resulting next state s'",
      "Ignores the reward",
      "Uses the value function",
    ],
    answer: 1,
    explain: "r(s,a,s') = E[R_t | S_{t−1}=s, A_{t−1}=a, S_t=s'] conditions on the next state as well, whereas r(s,a) averages over next states. Both are derivable from p(s',r|s,a).",
  },
  {
    q: "Overall, Chapter 3 establishes the MDP as...",
    options: [
      "A special case of supervised learning",
      "The formal mathematical framework (states, actions, rewards, dynamics, returns, value functions, optimality) underlying the rest of the book",
      "An approximate heuristic with no theory",
      "A model only for bandits",
    ],
    answer: 1,
    explain: "Chapter 3 formalizes the RL problem as a finite MDP and defines returns, value functions, Bellman (optimality) equations, and optimal policies — the theoretical foundation for all later methods.",
  }
);
